/** Deduped admin tool search index. routePath = navigate to standalone; else scroll/collapse in hub. */
export const SEARCHABLE_TOOLS = [
  { label: "Target Username", categoryId: "admin-operations", scrollToId: "admin-target-username", keywords: ["target","username","player","command"] },
  { label: "Search Users", categoryId: "admin-players", scrollToId: "admin-search-users", keywords: ["search","users","email","find"] },
  { label: "Change Rank", categoryId: "admin-players", collapseKey: "rank", keywords: ["rank","change","prestige","level"] },
  { label: "Add Points", categoryId: "admin-players", collapseKey: "points", keywords: ["points","add","give"] },
  { label: "Remove points", categoryId: "admin-players", collapseKey: "points", keywords: ["points","remove","deduct","take"] },
  { label: "Point sources audit", categoryId: "admin-players", collapseKey: "player", keywords: ["points","sources","audit","where","breakdown","ledger","stripe","transfers"] },
  { label: "Add respect points", categoryId: "admin-players", collapseKey: "player", keywords: ["respect","add","grant","give","points"] },
  { label: "Remove respect points", categoryId: "admin-players", collapseKey: "player", keywords: ["respect","remove","deduct","take"] },
  { label: "Points Provenance", categoryId: "admin-donations", collapseKey: "donationsProvenance", keywords: ["chargeback","provenance","payment session","points tree"], adminOnly: true },
  { label: "Add Tokens", categoryId: "admin-players", collapseKey: "tokens", keywords: ["tokens","crime","gta","melt","booze","travel","oc","racket","jailbust"] },
  { label: "Token Inspector", categoryId: "admin-players", collapseKey: "tokens", keywords: ["token","inspect","balance","boost","expiry","held","used","purchased","active"] },
  { label: "Clear pool cue upgrades", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-user-adjust-hub", keywords: ["pool","8-ball","8 ball","cue","upgrades","reset","minigame"] },
  { label: "Reset kill inflation", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-user-adjust-hub", keywords: ["kill","inflation","combat","attack","bullets","reset","zero","0%"], adminOnly: true },
  { label: "Remove Bodyguard Find Clock", categoryId: "admin-players", collapseKey: "player", keywords: ["bodyguard","find","clock","find clock","perk","store","attack","search","remove"], adminOnly: true },
  { label: "Auto Rank email entitlement", categoryId: "admin-players", collapseKey: "userAdjustHub", keywords: ["auto rank","email","entitlement","stripe","permanent","20"], adminOnly: true },
  { label: "New player tutorial", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-new-player-tutorial", keywords: ["tutorial","new player","onboarding","coach","reset tutorial","start tutorial"], adminOnly: true },
  { label: "Founding Member", categoryId: "admin-players", collapseKey: "founding", keywords: ["founding","member","badge","founder"] },
  { label: "Add Money", categoryId: "admin-players", collapseKey: "money", keywords: ["money","cash","add","give"] },
  { label: "Remove money (user)", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-user-adjust-hub", keywords: ["remove","money","cash","take","deduct","subtract","wallet"] },
  { label: "Log all users out", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-user-adjust-hub", keywords: ["log all users","logout everyone","site wide","invalidate sessions","sessions","jwt","token","invalidate all","site wide sessions"], adminOnly: true },
  { label: "Add Bullets", categoryId: "admin-players", collapseKey: "bullets", keywords: ["bullets","ammo","add"] },
  { label: "Give Car", categoryId: "admin-players", collapseKey: "cars", keywords: ["car","vehicle","give"] },
  { label: "Drop common/uncommon cars", categoryId: "admin-players", collapseKey: "cars", keywords: ["car","vehicle","drop","purge","common","uncommon","garage","dealership","stock"], adminOnly: true },
  { label: "Ghost Mode", categoryId: "admin-players", collapseKey: "ghost", keywords: ["ghost","invisible","hide"] },
  { label: "Lock Account", categoryId: "admin-moderation", collapseKey: "moderationPlayer", keywords: ["lock","ban","account","player","investigation"] },
  { label: "Kill Player", categoryId: "admin-moderation", collapseKey: "moderationPlayer", keywords: ["kill","death","player","modkill"] },
  { label: "Modkill (wipe)", categoryId: "admin-moderation", collapseKey: "moderationPlayer", keywords: ["modkill","wipe","shame","honours","leaderboard","rat","prestige","game pass","revive"] },
  { label: "Revive Player", categoryId: "admin-moderation", collapseKey: "moderationPlayer", keywords: ["revive","resurrect","alive"], adminOnly: true },
  { label: "User Details", categoryId: "admin-players", collapseKey: "userDetails", keywords: ["user","details","info","profile","jail","bust","reward"] },
  { label: "User give / take & leaderboards", categoryId: "admin-players", collapseKey: "userAdjustHub", keywords: ["leaderboard","adjust","strip","username","crimes","scores","gta","busts","kills","minigame","money","points","respect","bullets","weekly","alltime","preview","partial","bootleg","racing lifetime","lifetime earnings"] },
  { label: "Missions & tribute (user)", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-missions-ladder", keywords: ["mission","tribute","ladder","progress","daily tribute","m_first","story"] },
  { label: "Referrals & prereg heal", categoryId: "admin-players", collapseKey: "referralsReport", keywords: ["referral","referrer","referee","invite","earnings","ref","heal","prereg","backfill","manual","assign","link","remove","unlink","clear"] },
  { label: "Respect points log", categoryId: "admin-players", collapseKey: "respectPointsLog", keywords: ["respect","points","log","earned","audit","player"] },
  { label: "Prestige points rewards", categoryId: "admin-players", collapseKey: "prestigePointsRewards", scrollToId: "admin-prestige-points-rewards", keywords: ["prestige","points","reward","grant","p1","p2","store points","backfill"] },
  { label: "Gambling Log", categoryId: "admin-logs", collapseKey: "gamblingLog", keywords: ["gambling","log","casino","bet"] },
  { label: "Casino seizures", categoryId: "admin-logs", collapseKey: "casinoSeizures", keywords: ["casino","seizure","won","ownership","transfer"] },
  { label: "Casino buy-back history", categoryId: "admin-logs", collapseKey: "casinoBuybackHistory", keywords: ["buyback","buy-back","casino","escrow","points","held","offer"] },
  { label: "Sports open stake cap", categoryId: "admin-logs", collapseKey: "sportsOpenStakeCap", keywords: ["sports","betting","underground","open stake","cap","max bet"] },
  { label: "Sports bets ledger", categoryId: "admin-logs", collapseKey: "sportsBetsLedger", keywords: ["sports","betting","bets","football","ledger"] },
  { label: "Activity Log", categoryId: "admin-logs", collapseKey: "activityLog", keywords: ["activity","log","history"] },
  { label: "Donations Payments Log", categoryId: "admin-donations", collapseKey: "donationsPayments", keywords: ["donations","payments","stripe","credit"], adminOnly: true },
  { label: "Store Point Crediting", categoryId: "admin-donations", collapseKey: "donationsStore", keywords: ["store","crediting","manual","eta","payments"], adminOnly: true },
  { label: "Store item rollout", categoryId: "admin-donations", collapseKey: "donationsStore", keywords: ["store","rollout","feature flag","coming soon","auto-collect","bailout","cooldown skip","profile glow","family crest","safe deposit","phase 1","enable","test"], adminOnly: true },
  { label: "Pre-order Settings", categoryId: "admin-donations", collapseKey: "donationsStore", keywords: ["preorder","points","release","manual","store","credit"], adminOnly: true },
  { label: "Store cash purchase logs", categoryId: "admin-donations", collapseKey: "pointsCashLogs", keywords: ["points","cash","store","ip","email","monthly","quick trade","token","bundle"], adminOnly: true },
  { label: "Release Preorder Points", categoryId: "admin-donations", collapseKey: "donationsStore", keywords: ["release","preorder","points","credit"], adminOnly: true },
  { label: "Quick Trade admin", categoryId: "admin-economy-progression", collapseKey: "quicktradeTool", keywords: ["quicktrade","trade","offers","escrow","cancel","listings","tokens","property"], adminOnly: true },
  { label: "Racket progress", categoryId: "admin-economy-progression", keywords: ["racket","distillery","illegal business","progress","vault","guards","security","ladder","booze","ibm"], adminOnly: true, routePath: "/tjjeujr3wa/racket-progress" },
  { label: "Weed sell audit", categoryId: "admin-economy-progression", keywords: ["weed","empire","sell","spam","stash","clawback","exploit","audit","heat","reset heat"], adminOnly: true, routePath: "/tjjeujr3wa/weed-sell-audit" },
  { label: "Dead estates", categoryId: "admin-economy-progression", keywords: ["dead","estate","inheritance","points","cash","swiss","linked","alt","email"], adminOnly: true, routePath: "/tjjeujr3wa/dead-estates" },
  { label: "Game Events", categoryId: "admin-gameworld", collapseKey: "events", keywords: ["events","toggle","enable","disable","random","bundle","daily","modifiers","roll"], adminOnly: true },
  { label: "World Cup 2026 (archive)", categoryId: "admin-gameworld", collapseKey: "worldCup", keywords: ["world cup","2026","predictions","fifa","draft","fixtures","sync","archive","leaderboard","history"], adminOnly: true },
  { label: "Booze Run rotation & global discount", categoryId: "admin-gameworld", collapseKey: "boozeRun", keywords: ["booze","run","rotation","prices","discount","listed","nudge","global","jail","bust","prohibition"], adminOnly: true },
  { label: "Booze Run analytics", categoryId: "admin-analytics-monitoring", collapseKey: "boozeRunAnalytics", keywords: ["booze","analytics","economy","events","profit","revenue","jail","leaderboard"] },
  { label: "Coin Flip economy", categoryId: "admin-analytics-monitoring", collapseKey: "coinFlipEconomy", keywords: ["coin","flip","casino","economy","heads","tails","bets","winners","house"] },
  { label: "Global properties profit", categoryId: "admin-analytics-monitoring", collapseKey: "globalPropertiesEconomy", keywords: ["car","dealership","sports","betting","book","global","property","owner","profit","pending","house","percent","share"], adminOnly: true },
  { label: "Keno economy", categoryId: "admin-analytics-monitoring", collapseKey: "kenoEconomy", keywords: ["keno","casino","economy","payout","gambling","state","max bet","keno settings","top wins","player"] },
  { label: "Presence simulator", categoryId: "admin-gameworld", collapseKey: "presenceSimulator", keywords: ["presence","simulator","online","active","fake","last_seen"], adminOnly: true },
  { label: "Slots Draw", categoryId: "admin-gameworld", collapseKey: "slotsDraw", keywords: ["slots","draw","lottery"] },
  { label: "Lottery money trail", categoryId: "admin-gameworld", collapseKey: "lotteryMoneyTrail", keywords: ["lottery","money","payout","winner","pot","audit","trail","twice","wed","sun"], adminOnly: true },
  { label: "Bootleg Runs economy", categoryId: "admin-gameworld", collapseKey: "racingEconomy", keywords: ["racing","bootleg","crew","bank","adjust crew","crew bank","lifetime","earnings","payout","wallet","runs","audit"], adminOnly: true },
  { label: "Crack the Safe jackpot", categoryId: "admin-gameworld", collapseKey: "crackSafeJackpot", keywords: ["crack","safe","jackpot","pot","lower"] },
  { label: "State Heads", categoryId: "admin-gameworld", collapseKey: "stateHeads", keywords: ["state","heads","family","territory"] },
  { label: "Game Pass season end", categoryId: "admin-gameworld", collapseKey: "gamePassSeason", keywords: ["game pass","season","end","countdown","date","time","global"], adminOnly: true },
  { label: "Reset Racket Cooldown", categoryId: "admin-gameworld", collapseKey: "racketReset", keywords: ["racket","cooldown","reset","family"], adminOnly: true },
  { label: "Casino limits (global caps)", categoryId: "admin-gameworld", collapseKey: "casinoLimits", keywords: ["casino","limits","caps","max bet","buyback","poker","blind"] },
  { label: "Claim costs (casino, airport, armoury)", categoryId: "admin-gameworld", collapseKey: "claimCosts", keywords: ["claim","cost","casino","airport","armoury","bullet","factory","dice","roulette"], adminOnly: true },
  { label: "Casino per-game max bets", categoryId: "admin-gameworld", collapseKey: "casinoMaxBets", keywords: ["casino","max bet","per game","slots","blackjack","roulette"] },
  { label: "Dead owner properties", categoryId: "admin-gameworld", collapseKey: "casinosDeadOwners", keywords: ["dead","casino","armoury","airport","ownership","stuck","invalid","takeover","killer"] },
  { label: "Admin display & signup", categoryId: "admin-gameworld", collapseKey: "adminDisplay", keywords: ["admin","display","colour","color","online","email","verification","vpn","proxy","user agent","signup"], adminOnly: true },
  { label: "Sustained page pacing (jail, forum, entertainer, kill)", categoryId: "admin-gameworld", collapseKey: "sustainedPageRl", keywords: ["sustained","pacing","rate","forum","entertainer","jail","kill","attack","429","cooldown","bot","gap","sustain"], adminOnly: true },
  { label: "Swiss & interest bank limits", categoryId: "admin-gameworld", collapseKey: "bankEconomy", keywords: ["swiss","interest","bank","limit","deposit","maturity","principal"], adminOnly: true },
  { label: "Launch & login lock", categoryId: "admin-gameworld", collapseKey: "launchSettings", keywords: ["login","lock","launch","store","preorder","preregister","banner","landing"], adminOnly: true },
  { label: "Maintenance banner", categoryId: "admin-gameworld", collapseKey: "maintenanceBanner", keywords: ["maintenance","banner","downtime"] },
  { label: "Security Summary", categoryId: "admin-security", collapseKey: "security", keywords: ["security","summary","flags","rate","ban","ip","lockout","telegram"] },
  { label: "Session stats", categoryId: "admin-security", collapseKey: "sessionStats", keywords: ["session","sessions","active","log out","revoke","24h"] },
  { label: "Staff tool denials (401/403)", categoryId: "admin-security", collapseKey: "staffAccessDenials", keywords: ["403","401","denied","forbidden","staff","access","audit","login"], adminOnly: false },
  { label: "Staff tool access (history + live)", categoryId: "admin-security", collapseKey: "toolAccessAudit", keywords: ["staff","admin","tool","access","audit","history","presence","who","used","shell"], adminOnly: false },
  { label: "Sustained pacing 429 log", categoryId: "admin-security", collapseKey: "sustainedRl429Log", keywords: ["429","rate","limit","pacing","sustained","inbox","spam","throttle"], adminOnly: true },
  { label: "IP Bans", categoryId: "admin-security", collapseKey: "ipBans", scrollToId: "admin-ip-bans", hubRoute: "safety", keywords: ["ip","ban","block","unban","restore","ip ban","ban ip","ban user","duration","weeks","shame"] },
  { label: "Rate Limits", categoryId: "admin-security", collapseKey: "security", keywords: ["rate","limit","throttle","violations","cooldown"] },
  { label: "Cloudflare Bot Block", categoryId: "admin-security", collapseKey: "cfBotBlock", keywords: ["cloudflare","bot","block","cf"] },
  { label: "Cloudflare auto block", categoryId: "admin-security", collapseKey: "cfAutoBlock", keywords: ["cloudflare","auto","block","cf"] },
  { label: "Security panel", categoryId: "admin-security", collapseKey: "security", keywords: ["security","flags","threat","monitor"] },
  { label: "Cheat Detection", categoryId: "admin-cheat", collapseKey: "cheat", keywords: ["cheat","detection","suspicious","mod"] },
  { label: "Bot / script investigation", categoryId: "admin-cheat", collapseKey: "botInvestigation", keywords: ["bot","script","automation","investigation","cheat","suspicious","ip","network","mobile","isp","vpn","attack","execute_token","spoof","ua","kill"] },
  { label: "Find Duplicates", categoryId: "admin-cheat", collapseKey: "duplicates", keywords: ["duplicate","multi","account","dupe"] },
  { label: "Proxy farm investigation", categoryId: "admin-cheat", collapseKey: "cheat", keywords: ["proxy","proxyroyal","iproyal","residential","vpn","multi","account","farm","rotator"] },
  { label: "Cheater kill impact", categoryId: "admin-cheat", collapseKey: "cheaterKillImpact", keywords: ["cheater","kill","impact","bodyguard","refund","hire"], adminOnly: true },
  { label: "Login page unique visitors", categoryId: "admin-analytics", collapseKey: "loginPageVisitors", keywords: ["login","visitors","unique","page","stats"] },
  { label: "Casino Ownership Profits", categoryId: "admin-analytics", collapseKey: "ownershipProfits", keywords: ["casino","ownership","profit","owner","earnings"] },
  { label: "Interest bank by player", categoryId: "admin-analytics", collapseKey: "interestBankPlayers", keywords: ["interest","bank","deposits","holders"] },
  { label: "Swiss Bank Overview", categoryId: "admin-analytics", collapseKey: "swissBank", keywords: ["swiss","bank","balance","hidden","money","wipe"] },
  { label: "Points purchases (store spends)", categoryId: "admin-analytics", collapseKey: "pointsStoreSpends", keywords: ["points","store","spend","bought","purchases","refund"] },
  { label: "Store points purchase log", categoryId: "admin-analytics", collapseKey: "storePointsPurchaseLogs", keywords: ["points","store","robot","auto-search","bodyguard","silencer","armour","token","purchase log"], adminOnly: true },
  { label: "Analytics V2 workspace", categoryId: "admin-analytics-monitoring", collapseKey: "analyticsWorkspaceV2", keywords: ["analytics","v2","workspace","rollup","rollups","stats","users","events"] },
  { label: "Economy overview", categoryId: "admin-analytics-monitoring", collapseKey: "economyOverview", keywords: ["economy","overview","gdp","money","circulation","cash","holders","wallet","distribution","drill","accounts"] },
  { label: "Cash gain threshold audit", categoryId: "admin-analytics-monitoring", collapseKey: "economySpikeAudit", keywords: ["spike","inflation","cash jump","cash increase","wallet","threshold","50 million","points","audit","ledger","gambling","payout","suspicious","economy"] },
  { label: "Capital breakdown", categoryId: "admin-analytics-monitoring", collapseKey: "capitalBreakdown", keywords: ["capital","breakdown","wealth"] },
  { label: "Player activity", categoryId: "admin-analytics-monitoring", collapseKey: "playerActivity", keywords: ["player","activity","dau","mau"] },
  { label: "Attack analytics", categoryId: "admin-analytics-monitoring", collapseKey: "attackAnalytics", keywords: ["attack","analytics","pvp","kills"] },
  { label: "Crime analytics", categoryId: "admin-analytics-monitoring", collapseKey: "crimeAnalytics", keywords: ["crime","analytics"] },
  { label: "Casino analytics", categoryId: "admin-analytics-monitoring", collapseKey: "casinoAnalytics", keywords: ["casino","analytics","house"] },
  { label: "Trades analytics", categoryId: "admin-analytics-monitoring", collapseKey: "tradesAnalytics", keywords: ["trades","analytics","stock","market"] },
  { label: "Hitlist & bodyguards analytics", categoryId: "admin-analytics-monitoring", collapseKey: "hitlistBodyguardsAnalytics", keywords: ["hitlist","bodyguard","analytics"] },
  { label: "Economy analytics", categoryId: "admin-analytics-monitoring", collapseKey: "economyAnalytics", keywords: ["economy","analytics","sink","faucet"] },
  { label: "Loot box opens log", categoryId: "admin-analytics-monitoring", collapseKey: "lootBoxOpens", keywords: ["loot","box","opens","rewards","username"] },
  { label: "Player compare", categoryId: "admin-analytics-monitoring", collapseKey: "playerCompare", keywords: ["compare","players","side by side"], adminOnly: true },
  { label: "Toast notifications", categoryId: "admin-logs", collapseKey: "toastNotifications", keywords: ["toast","notifications","popup","message","error","success"] },
  { label: "Wallet activity", categoryId: "admin-logs", collapseKey: "walletActivity", keywords: ["wallet","money","points","cash","transfer","mdg","bank","ledger"] },
  { label: "Live Activity Feed", categoryId: "admin-logs", collapseKey: "activityFeed", keywords: ["activity","feed","live","real-time","actions","gambling","bank","transfer"] },
  { label: "Minigame Payouts", categoryId: "admin-logs", collapseKey: "minigamePayouts", keywords: ["minigame","payout","reward","cash","mini","game"] },
  { label: "Weekly Leaderboard Payouts", categoryId: "admin-logs", collapseKey: "weeklyLeaderboardPayouts", keywords: ["leaderboard","weekly","payout","respect","points","top 10","fix","deduction","negative points"] },
  { label: "Attack Logs", categoryId: "admin-logs", keywords: ["attack","log","kill"], routePath: "/tjjeujr3wa/attack-logs" },
  { label: "BG hire logs", categoryId: "admin-logs", keywords: ["bodyguard","hire","robot","rvk","bot","log"], routePath: "/tjjeujr3wa/bodyguard-hire-logs" },
  { label: "Bodyguard audit", categoryId: "admin-logs", collapseKey: "bodyguardAudit", keywords: ["bodyguard","guard","hire","drop","inflation","robot hire history","last 100 robot","searching time","find time","overpay","stale inflation"] },
  { label: "Mod Action Logs", categoryId: "admin-logs", collapseKey: "modLogs", keywords: ["mod","action","log"] },
  { label: "Crime logs", categoryId: "admin-logs", collapseKey: "crimeLogs", keywords: ["crime","log","heist"] },
  { label: "GTA logs", categoryId: "admin-logs", collapseKey: "gtaLogs", keywords: ["gta","log","theft","car"] },
  { label: "Jail logs", categoryId: "admin-logs", collapseKey: "jailLogs", keywords: ["jail","log","sentence"] },
  { label: "Bank logs", categoryId: "admin-logs", collapseKey: "bankLogs", keywords: ["bank","log","transfer"] },
  { label: "Stock logs", categoryId: "admin-logs", collapseKey: "stockLogs", keywords: ["stock","log","shares"] },
  { label: "Search & Attack Tools", categoryId: "admin-testing", collapseKey: "search", keywords: ["search","attack","time"] },
  { label: "Set Search Time", categoryId: "admin-testing", collapseKey: "search", keywords: ["search","time","minutes"], adminOnly: true },
  { label: "Clear All Searches", categoryId: "admin-testing", collapseKey: "search", keywords: ["clear","searches","delete"], adminOnly: true },
  { label: "Fix login fields (user)", categoryId: "admin-testing", collapseKey: "search", keywords: ["login","fix","repair","sessions","ip","lockout"] },
  { label: "Clear OC invites (user)", categoryId: "admin-testing", collapseKey: "search", keywords: ["oc","organised","crime","invite","clear","user"] },
  { label: "Clear minigame records (user)", categoryId: "admin-players", collapseKey: "userAdjustHub", keywords: ["minigame","records","clear","user","scores"], adminOnly: true },
  { label: "Minigame weekly leaderboard strip/add", categoryId: "admin-players", collapseKey: "userAdjustHub", keywords: ["minigame","leaderboard","weekly","strip","add","score","flappy","gauntlet"], adminOnly: true },
  { label: "Main leaderboards strip (respect melt stock booze)", categoryId: "admin-players", collapseKey: "userAdjustHub", keywords: ["leaderboard","weekly","respect","melt","stock","booze","strip","top 10"], adminOnly: true },
  { label: "Reconcile Game Pass tiers", categoryId: "admin-players", collapseKey: "userAdjustHub", keywords: ["game pass","reconcile","tier","vip","rank xp","micro tier","force grant","rewards"], adminOnly: true },
  { label: "Game Pass inspector", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-game-pass-inspector", keywords: ["game pass","inspector","vip","token","stripe","rank xp","micro tier","entitlement"], adminOnly: true },
  { label: "Game Pass points diagnostic", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-game-pass-inspector", keywords: ["game pass","points","diagnostic","ledger","stripe","purchase source","catch up pending"], adminOnly: true },
  { label: "Game Pass stuck cursors", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-game-pass-inspector", keywords: ["game pass","stuck","cursor","broken","fix","repair","rewards"], adminOnly: true },
  { label: "First Game Pass VIP completion", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-first-gp-vip-completion", keywords: ["game pass","first","vip","completion","bulk","tier","100","bonus","one time"], adminOnly: true },
  { label: "Complete remaining VIP (season)", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-complete-remaining-vip", keywords: ["game pass","vip","complete","remaining","season","bulk","tier","100"], adminOnly: true },
  { label: "Disable Atlantic City", categoryId: "admin-operations", collapseKey: "stateHeads", scrollToId: "admin-disable-state", keywords: ["atlantic city","disable state","remove city","migration","relinquish"], adminOnly: true },
  { label: "User inbox (live)", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-user-inbox", keywords: ["inbox","notifications","dm","messages","mail","social"], adminOnly: true },
  { label: "Deleted messages", categoryId: "admin-players", collapseKey: "userAdjustHub", scrollToId: "admin-deleted-messages", keywords: ["deleted","messages","archive","forum","chat","dm","notification","history"], adminOnly: true },
  { label: "Reset OC Timers", categoryId: "admin-testing", collapseKey: "search", keywords: ["oc","organised","crime","timer"] },
  { label: "Reset Daily Rewards Timer", categoryId: "admin-testing", collapseKey: "search", keywords: ["daily","rewards","timer","rps"] },
  { label: "Bodyguard Tools", categoryId: "admin-testing", collapseKey: "bodyguards", keywords: ["bodyguard","robot","generate","sync","location","hacked","replace","hire inflation","clear inflation","payout","test"] },
  { label: "Hitman Tools", categoryId: "admin-testing", collapseKey: "hitman", keywords: ["hitman","cooldown","protection","victim","reset","for hire","hire log","contracts","staff hire","hire","contract","log","bodyguard killed","who hired"] },
  { label: "GTA exclusive pool & dealer", categoryId: "admin-world-systems", collapseKey: "gtaPool", keywords: ["gta","exclusive","loot exclusive","car intel","timeline","war lock","marketplace","pool","dealer","cars","values"], adminOnly: true },
  { label: "Last Man Standing", categoryId: "admin-world-systems", routePath: "/tjjeujr3wa/last-man-standing", keywords: ["lms","last man standing","premier","football","season","pot"], adminOnly: true },
  { label: "System health", categoryId: "admin-operations", collapseKey: "systemHealth", keywords: ["system","health","uptime","status","db"] },
  { label: "Moderation related accounts", categoryId: "admin-operations", collapseKey: "moderationRelated", keywords: ["moderation","related","linked","accounts"] },
  { label: "Page locks (admin)", categoryId: "admin-world-systems", collapseKey: "pageLocks", scrollToId: "admin-page-locks", keywords: ["page","lock","route","maintenance"] },
  { label: "Family war — force truce", categoryId: "admin-operations", collapseKey: "familyWarTruce", scrollToId: "admin-family-war-truce", keywords: ["family","war","truce","crew","end war","peace"], adminOnly: true },
  { label: "Mod display", categoryId: "admin-operations", collapseKey: "modDisplay", keywords: ["mod","display","colour","color","badge","online","palette"] },
  { label: "Give All Points", categoryId: "admin-quick", collapseKey: "quick", keywords: ["give","all","points","bulk"] },
  { label: "Give All Money", categoryId: "admin-quick", collapseKey: "quick", keywords: ["give","all","money","bulk"] },
  { label: "Bulk User Action", categoryId: "admin-quick", collapseKey: "bulkAction", keywords: ["bulk","action","multiple","users"] },
  { label: "Redeem Codes", categoryId: "admin-quick", collapseKey: "redeemCodes", keywords: ["redeem","code","reward","cash","points","cars","bullets","player redeem","token gift"] },
  { label: "Image host (user uploads)", categoryId: "admin-database", collapseKey: "imageHostAdmin", keywords: ["image","host","upload","picture","imgur","photo"], adminOnly: true },
  { label: "Staff Management", categoryId: "admin-staff", collapseKey: "staff", keywords: ["staff","mod","helper","promote"] },
  { label: "Add Moderator", categoryId: "admin-staff", collapseKey: "staff", keywords: ["mod","moderator","add","promote"] },
  { label: "Add Helper", categoryId: "admin-staff", collapseKey: "staff", keywords: ["helper","help desk","add","promote"] },
  { label: "Distillery progress", categoryId: "admin-economy-progression", routePath: "/tjjeujr3wa/distillery-progress", keywords: ["distillery","still","booze","heat","equipment","special upgrades"], adminOnly: true },
  { label: "VIP Pass cars", categoryId: "admin-world-systems", routePath: "/tjjeujr3wa/vip-cars", keywords: ["vip","pass","car","owners","remove","stock"], adminOnly: true },
  { label: "Locked accounts", categoryId: "admin-world-systems", routePath: "/tjjeujr3wa/locked", keywords: ["locked","accounts","investigation","lock"] },
  { label: "Online dupe screen", categoryId: "admin-analytics-monitoring", routePath: "/tjjeujr3wa/users-online", keywords: ["online","dupe","proxy","fingerprint","live"] },
  { label: "Account access", categoryId: "admin-analytics-monitoring", routePath: "/tjjeujr3wa/ip-history", keywords: ["ip","history","device","hacked","access"] },
  { label: "Dead > Alive log", categoryId: "admin-analytics-monitoring", routePath: "/tjjeujr3wa/dead-alive-log", keywords: ["dead","alive","retrieve","revive","transfer"] },
  { label: "Account compare", categoryId: "admin-analytics-monitoring", routePath: "/tjjeujr3wa/account-compare", keywords: ["compare","accounts","shared","ip"] },
  { label: "Exclusive cars", categoryId: "admin-world-systems", routePath: "/tjjeujr3wa/exclusive-cars", keywords: ["exclusive","al capone","loot","cars"], adminOnly: true },
  { label: "Crew recovery", categoryId: "admin-operations", routePath: "/tjjeujr3wa/crew-recovery", keywords: ["crew","family","recovery","revive"], adminOnly: true },
  { label: "Witness statements", categoryId: "admin-operations", routePath: "/tjjeujr3wa/witness-statements", keywords: ["witness","statements"] },
  { label: "Ammo circulation", categoryId: "admin-world-systems", routePath: "/tjjeujr3wa/molotovs", keywords: ["molotov","ammo","bullets"], adminOnly: true },
  { label: "Armoury / airport", categoryId: "admin-world-systems", routePath: "/tjjeujr3wa/property-transfer", keywords: ["armoury","airport","transfer","property"], adminOnly: true },
  { label: "E-Games audit", categoryId: "admin-analytics-monitoring", routePath: "/tjjeujr3wa/ent-games", keywords: ["entertainer","dice","gbox","hangman","e-games"], adminOnly: true },
];
