/**
 * Theme presets: colours and textures for the app.
 * Changing theme updates Rank Progress bar, panel headers, buttons, sidebar, and all accent UI.
 */

/** Hex colour presets: { id, name, primary, primaryBright, primaryDark, foregroundOnPrimary } */
export const THEME_COLOURS = [
  { id: 'gold', name: 'Gold', primary: '#d4af37', primaryBright: '#e6c229', primaryDark: '#b8860b', foregroundOnPrimary: '#ffffff' },
  { id: 'amber', name: 'Amber', primary: '#f59e0b', primaryBright: '#fbbf24', primaryDark: '#d97706', foregroundOnPrimary: '#000000' },
  { id: 'yellow', name: 'Yellow', primary: '#eab308', primaryBright: '#facc15', primaryDark: '#ca8a04', foregroundOnPrimary: '#000000' },
  { id: 'orange', name: 'Orange', primary: '#ea580c', primaryBright: '#f97316', primaryDark: '#c2410c', foregroundOnPrimary: '#ffffff' },
  { id: 'red', name: 'Red', primary: '#dc2626', primaryBright: '#ef4444', primaryDark: '#b91c1c', foregroundOnPrimary: '#ffffff' },
  { id: 'rose', name: 'Rose', primary: '#e11d48', primaryBright: '#f43f5e', primaryDark: '#be123c', foregroundOnPrimary: '#ffffff' },
  { id: 'crimson', name: 'Crimson', primary: '#be185d', primaryBright: '#ec4899', primaryDark: '#9d174d', foregroundOnPrimary: '#ffffff' },
  { id: 'fuchsia', name: 'Fuchsia', primary: '#c026d3', primaryBright: '#d946ef', primaryDark: '#a21caf', foregroundOnPrimary: '#ffffff' },
  { id: 'violet', name: 'Violet', primary: '#7c3aed', primaryBright: '#8b5cf6', primaryDark: '#6d28d9', foregroundOnPrimary: '#ffffff' },
  { id: 'purple', name: 'Purple', primary: '#9333ea', primaryBright: '#a855f7', primaryDark: '#7e22ce', foregroundOnPrimary: '#ffffff' },
  { id: 'indigo', name: 'Indigo', primary: '#4f46e5', primaryBright: '#6366f1', primaryDark: '#4338ca', foregroundOnPrimary: '#ffffff' },
  { id: 'blue', name: 'Blue', primary: '#2563eb', primaryBright: '#3b82f6', primaryDark: '#1d4ed8', foregroundOnPrimary: '#ffffff' },
  { id: 'sky', name: 'Sky', primary: '#0ea5e9', primaryBright: '#38bdf8', primaryDark: '#0284c7', foregroundOnPrimary: '#000000' },
  { id: 'cyan', name: 'Cyan', primary: '#0891b2', primaryBright: '#22d3ee', primaryDark: '#0e7490', foregroundOnPrimary: '#000000' },
  { id: 'teal', name: 'Teal', primary: '#0d9488', primaryBright: '#2dd4bf', primaryDark: '#0f766e', foregroundOnPrimary: '#ffffff' },
  { id: 'emerald', name: 'Emerald', primary: '#059669', primaryBright: '#10b981', primaryDark: '#047857', foregroundOnPrimary: '#ffffff' },
  { id: 'green', name: 'Green', primary: '#16a34a', primaryBright: '#22c55e', primaryDark: '#15803d', foregroundOnPrimary: '#ffffff' },
  { id: 'lime', name: 'Lime', primary: '#65a30d', primaryBright: '#84cc16', primaryDark: '#4d7c0f', foregroundOnPrimary: '#000000' },
  { id: 'olive', name: 'Olive', primary: '#84cc16', primaryBright: '#a3e635', primaryDark: '#65a30d', foregroundOnPrimary: '#000000' },
  { id: 'bronze', name: 'Bronze', primary: '#b45309', primaryBright: '#d97706', primaryDark: '#92400e', foregroundOnPrimary: '#ffffff' },
  { id: 'copper', name: 'Copper', primary: '#b45309', primaryBright: '#ea580c', primaryDark: '#9a3412', foregroundOnPrimary: '#ffffff' },
  { id: 'rust', name: 'Rust', primary: '#c2410c', primaryBright: '#ea580c', primaryDark: '#9a3412', foregroundOnPrimary: '#ffffff' },
  { id: 'wine', name: 'Wine', primary: '#9f1239', primaryBright: '#be123c', primaryDark: '#881337', foregroundOnPrimary: '#ffffff' },
  { id: 'plum', name: 'Plum', primary: '#701a75', primaryBright: '#86198f', primaryDark: '#581c87', foregroundOnPrimary: '#ffffff' },
  { id: 'slate', name: 'Slate', primary: '#475569', primaryBright: '#64748b', primaryDark: '#334155', foregroundOnPrimary: '#ffffff' },
  { id: 'zinc', name: 'Zinc', primary: '#71717a', primaryBright: '#a1a1aa', primaryDark: '#52525b', foregroundOnPrimary: '#ffffff' },
  { id: 'neutral', name: 'Neutral', primary: '#737373', primaryBright: '#a3a3a3', primaryDark: '#525252', foregroundOnPrimary: '#ffffff' },
  { id: 'stone', name: 'Stone', primary: '#78716c', primaryBright: '#a8a29e', primaryDark: '#57534e', foregroundOnPrimary: '#ffffff' },
  { id: 'mint', name: 'Mint', primary: '#10b981', primaryBright: '#34d399', primaryDark: '#059669', foregroundOnPrimary: '#000000' },
  { id: 'coral', name: 'Coral', primary: '#f43f5e', primaryBright: '#fb7185', primaryDark: '#e11d48', foregroundOnPrimary: '#ffffff' },
  { id: 'peach', name: 'Peach', primary: '#fb923c', primaryBright: '#fdba74', primaryDark: '#ea580c', foregroundOnPrimary: '#000000' },
  { id: 'honey', name: 'Honey', primary: '#eab308', primaryBright: '#fde047', primaryDark: '#ca8a04', foregroundOnPrimary: '#000000' },
  { id: 'mustard', name: 'Mustard', primary: '#ca8a04', primaryBright: '#eab308', primaryDark: '#a16207', foregroundOnPrimary: '#000000' },
  { id: 'saffron', name: 'Saffron', primary: '#f59e0b', primaryBright: '#fbbf24', primaryDark: '#d97706', foregroundOnPrimary: '#000000' },
  { id: 'burgundy', name: 'Burgundy', primary: '#881337', primaryBright: '#9f1239', primaryDark: '#701a75', foregroundOnPrimary: '#ffffff' },
  { id: 'maroon', name: 'Maroon', primary: '#9f1239', primaryBright: '#be123c', primaryDark: '#881337', foregroundOnPrimary: '#ffffff' },
  { id: 'magenta', name: 'Magenta', primary: '#c026d3', primaryBright: '#e879f9', primaryDark: '#a21caf', foregroundOnPrimary: '#ffffff' },
  { id: 'lavender', name: 'Lavender', primary: '#8b5cf6', primaryBright: '#a78bfa', primaryDark: '#7c3aed', foregroundOnPrimary: '#ffffff' },
  { id: 'periwinkle', name: 'Periwinkle', primary: '#6366f1', primaryBright: '#818cf8', primaryDark: '#4f46e5', foregroundOnPrimary: '#ffffff' },
  { id: 'navy', name: 'Navy', primary: '#1e40af', primaryBright: '#2563eb', primaryDark: '#1e3a8a', foregroundOnPrimary: '#ffffff' },
  { id: 'ocean', name: 'Ocean', primary: '#0369a1', primaryBright: '#0ea5e9', primaryDark: '#075985', foregroundOnPrimary: '#ffffff' },
  { id: 'aqua', name: 'Aqua', primary: '#06b6d4', primaryBright: '#22d3ee', primaryDark: '#0891b2', foregroundOnPrimary: '#000000' },
  { id: 'jade', name: 'Jade', primary: '#0d9488', primaryBright: '#14b8a6', primaryDark: '#0f766e', foregroundOnPrimary: '#ffffff' },
  { id: 'forest', name: 'Forest', primary: '#166534', primaryBright: '#22c55e', primaryDark: '#14532d', foregroundOnPrimary: '#ffffff' },
  { id: 'sage', name: 'Sage', primary: '#4d7c0f', primaryBright: '#65a30d', primaryDark: '#3f6212', foregroundOnPrimary: '#ffffff' },
  { id: 'chartreuse', name: 'Chartreuse', primary: '#65a30d', primaryBright: '#84cc16', primaryDark: '#4d7c0f', foregroundOnPrimary: '#000000' },
  { id: 'cream', name: 'Cream', primary: '#e7e5e4', primaryBright: '#f5f5f4', primaryDark: '#d6d3d1', foregroundOnPrimary: '#000000' },
  { id: 'ivory', name: 'Ivory', primary: '#fafaf9', primaryBright: '#ffffff', primaryDark: '#e7e5e4', foregroundOnPrimary: '#000000' },
  { id: 'silver', name: 'Silver', primary: '#a8a29e', primaryBright: '#d6d3d1', primaryDark: '#78716c', foregroundOnPrimary: '#000000' },
  { id: 'chrome', name: 'Chrome', primary: '#94a3b8', primaryBright: '#cbd5e1', primaryDark: '#64748b', foregroundOnPrimary: '#000000' },
  { id: 'steel', name: 'Steel', primary: '#64748b', primaryBright: '#94a3b8', primaryDark: '#475569', foregroundOnPrimary: '#ffffff' },
  { id: 'graphite', name: 'Graphite', primary: '#44403c', primaryBright: '#57534e', primaryDark: '#292524', foregroundOnPrimary: '#ffffff' },
  { id: 'charcoal', name: 'Charcoal', primary: '#3f3f46', primaryBright: '#52525b', primaryDark: '#27272a', foregroundOnPrimary: '#ffffff' },
  { id: 'midnight', name: 'Midnight', primary: '#312e81', primaryBright: '#4338ca', primaryDark: '#1e1b4b', foregroundOnPrimary: '#ffffff' },
  { id: 'twilight', name: 'Twilight', primary: '#4c1d95', primaryBright: '#6d28d9', primaryDark: '#3b0764', foregroundOnPrimary: '#ffffff' },
  { id: 'sunset', name: 'Sunset', primary: '#c2410c', primaryBright: '#ea580c', primaryDark: '#9a3412', foregroundOnPrimary: '#ffffff' },
  { id: 'sunrise', name: 'Sunrise', primary: '#ea580c', primaryBright: '#fb923c', primaryDark: '#c2410c', foregroundOnPrimary: '#000000' },
  { id: 'blood', name: 'Blood', primary: '#991b1b', primaryBright: '#b91c1c', primaryDark: '#7f1d1d', foregroundOnPrimary: '#ffffff' },
  { id: 'royal', name: 'Royal', primary: '#3730a3', primaryBright: '#4f46e5', primaryDark: '#312e81', foregroundOnPrimary: '#ffffff' },
  { id: 'electric', name: 'Electric', primary: '#2563eb', primaryBright: '#60a5fa', primaryDark: '#1d4ed8', foregroundOnPrimary: '#ffffff' },
  { id: 'neon-green', name: 'Neon Green', primary: '#22c55e', primaryBright: '#4ade80', primaryDark: '#16a34a', foregroundOnPrimary: '#000000' },
  { id: 'neon-pink', name: 'Neon Pink', primary: '#ec4899', primaryBright: '#f472b6', primaryDark: '#db2777', foregroundOnPrimary: '#000000' },
  { id: 'neon-blue', name: 'Neon Blue', primary: '#3b82f6', primaryBright: '#60a5fa', primaryDark: '#2563eb', foregroundOnPrimary: '#ffffff' },
  { id: 'neon-orange', name: 'Neon Orange', primary: '#f97316', primaryBright: '#fb923c', primaryDark: '#ea580c', foregroundOnPrimary: '#000000' },
  { id: 'pastel-pink', name: 'Pastel Pink', primary: '#f9a8d4', primaryBright: '#fbcfe8', primaryDark: '#ec4899', foregroundOnPrimary: '#000000' },
  { id: 'pastel-blue', name: 'Pastel Blue', primary: '#93c5fd', primaryBright: '#bfdbfe', primaryDark: '#3b82f6', foregroundOnPrimary: '#000000' },
  { id: 'pastel-green', name: 'Pastel Green', primary: '#86efac', primaryBright: '#bbf7d0', primaryDark: '#22c55e', foregroundOnPrimary: '#000000' },
  { id: 'pastel-purple', name: 'Pastel Purple', primary: '#c4b5fd', primaryBright: '#ddd6fe', primaryDark: '#8b5cf6', foregroundOnPrimary: '#000000' },
  { id: 'pastel-yellow', name: 'Pastel Yellow', primary: '#fde047', primaryBright: '#fef08a', primaryDark: '#eab308', foregroundOnPrimary: '#000000' },
  { id: 'deep-red', name: 'Deep Red', primary: '#7f1d1d', primaryBright: '#991b1b', primaryDark: '#450a0a', foregroundOnPrimary: '#ffffff' },
  { id: 'deep-blue', name: 'Deep Blue', primary: '#1e3a8a', primaryBright: '#1d4ed8', primaryDark: '#172554', foregroundOnPrimary: '#ffffff' },
  { id: 'deep-green', name: 'Deep Green', primary: '#14532d', primaryBright: '#166534', primaryDark: '#052e16', foregroundOnPrimary: '#ffffff' },
  { id: 'deep-purple', name: 'Deep Purple', primary: '#581c87', primaryBright: '#6d28d9', primaryDark: '#3b0764', foregroundOnPrimary: '#ffffff' },
  { id: 'pale-gold', name: 'Pale Gold', primary: '#fcd34d', primaryBright: '#fde68a', primaryDark: '#f59e0b', foregroundOnPrimary: '#000000' },
  { id: 'antique-brass', name: 'Antique Brass', primary: '#b8860b', primaryBright: '#d4af37', primaryDark: '#8b6914', foregroundOnPrimary: '#000000' },
  { id: 'gunmetal', name: 'Gunmetal', primary: '#2d3748', primaryBright: '#4a5568', primaryDark: '#1a202c', foregroundOnPrimary: '#ffffff' },
  { id: 'ash', name: 'Ash', primary: '#6b7280', primaryBright: '#9ca3af', primaryDark: '#4b5563', foregroundOnPrimary: '#ffffff' },
  { id: 'smoke', name: 'Smoke', primary: '#6b7280', primaryBright: '#9ca3af', primaryDark: '#4b5563', foregroundOnPrimary: '#ffffff' },
  { id: 'pewter', name: 'Pewter', primary: '#78716c', primaryBright: '#a8a29e', primaryDark: '#57534e', foregroundOnPrimary: '#ffffff' },
  { id: 'titanium', name: 'Titanium', primary: '#71717a', primaryBright: '#a1a1aa', primaryDark: '#52525b', foregroundOnPrimary: '#ffffff' },
  { id: 'carbon', name: 'Carbon', primary: '#3f3f46', primaryBright: '#52525b', primaryDark: '#27272a', foregroundOnPrimary: '#ffffff' },
  { id: 'obsidian', name: 'Obsidian', primary: '#27272a', primaryBright: '#3f3f46', primaryDark: '#18181b', foregroundOnPrimary: '#ffffff' },

  /* Mixed / blended colours */
  { id: 'rose-gold', name: 'Rose Gold', primary: '#b76e79', primaryBright: '#d4a0a8', primaryDark: '#9a5a64', foregroundOnPrimary: '#ffffff' },
  { id: 'copper-rose', name: 'Copper Rose', primary: '#996872', primaryBright: '#b8838c', primaryDark: '#7a5260', foregroundOnPrimary: '#ffffff' },
  { id: 'gold-amber', name: 'Gold Amber', primary: '#d4a574', primaryBright: '#e8c49a', primaryDark: '#b8864a', foregroundOnPrimary: '#000000' },
  { id: 'teal-blue', name: 'Teal Blue', primary: '#0d7a8c', primaryBright: '#1899ad', primaryDark: '#0a5c6b', foregroundOnPrimary: '#ffffff' },
  { id: 'violet-blue', name: 'Violet Blue', primary: '#5b4bb5', primaryBright: '#7260d4', primaryDark: '#453899', foregroundOnPrimary: '#ffffff' },
  { id: 'blue-teal', name: 'Blue Teal', primary: '#2a7b8a', primaryBright: '#3596a6', primaryDark: '#1f5d6a', foregroundOnPrimary: '#ffffff' },
  { id: 'sunset-blend', name: 'Sunset Blend', primary: '#d4694a', primaryBright: '#e88a6e', primaryDark: '#a84f34', foregroundOnPrimary: '#ffffff' },
  { id: 'forest-teal', name: 'Forest Teal', primary: '#1a6b5c', primaryBright: '#228b79', primaryDark: '#124d42', foregroundOnPrimary: '#ffffff' },
  { id: 'lavender-rose', name: 'Lavender Rose', primary: '#b87ba8', primaryBright: '#d19bc4', primaryDark: '#8f5d82', foregroundOnPrimary: '#ffffff' },
  { id: 'peach-gold', name: 'Peach Gold', primary: '#e5a86a', primaryBright: '#f0c08e', primaryDark: '#c48348', foregroundOnPrimary: '#000000' },
  { id: 'coral-pink', name: 'Coral Pink', primary: '#e85d6e', primaryBright: '#f07d8c', primaryDark: '#c94a5a', foregroundOnPrimary: '#ffffff' },
  { id: 'mint-blue', name: 'Mint Blue', primary: '#3db5a0', primaryBright: '#5ac9b5', primaryDark: '#2d8f7e', foregroundOnPrimary: '#000000' },
  { id: 'plum-violet', name: 'Plum Violet', primary: '#7e4d8e', primaryBright: '#9664a8', primaryDark: '#623a70', foregroundOnPrimary: '#ffffff' },
  { id: 'amber-copper', name: 'Amber Copper', primary: '#c4783a', primaryBright: '#d9945a', primaryDark: '#9d5c28', foregroundOnPrimary: '#ffffff' },
  { id: 'olive-gold', name: 'Olive Gold', primary: '#9a9b4a', primaryBright: '#b4b562', primaryDark: '#78793a', foregroundOnPrimary: '#000000' },
  { id: 'sage-blue', name: 'Sage Blue', primary: '#5a7a7a', primaryBright: '#739696', primaryDark: '#445d5d', foregroundOnPrimary: '#ffffff' },
  { id: 'dusty-rose', name: 'Dusty Rose', primary: '#c49a9a', primaryBright: '#dbb5b5', primaryDark: '#9a7272', foregroundOnPrimary: '#000000' },
  { id: 'muted-teal', name: 'Muted Teal', primary: '#4a7c7c', primaryBright: '#5e9999', primaryDark: '#385d5d', foregroundOnPrimary: '#ffffff' },
  { id: 'blush', name: 'Blush', primary: '#d4a5a5', primaryBright: '#e8c2c2', primaryDark: '#a67a7a', foregroundOnPrimary: '#000000' },
  { id: 'sea-green', name: 'Sea Green', primary: '#2e8b7a', primaryBright: '#3aa896', primaryDark: '#236b5d', foregroundOnPrimary: '#ffffff' },
  { id: 'berry', name: 'Berry', primary: '#8b4a6b', primaryBright: '#a65f85', primaryDark: '#6a3952', foregroundOnPrimary: '#ffffff' },
  { id: 'slate-blue', name: 'Slate Blue', primary: '#5c6b8a', primaryBright: '#7486a8', primaryDark: '#45526a', foregroundOnPrimary: '#ffffff' },
  { id: 'dusty-lavender', name: 'Dusty Lavender', primary: '#8b7a9a', primaryBright: '#a594b5', primaryDark: '#6a5c78', foregroundOnPrimary: '#ffffff' },
  { id: 'terracotta', name: 'Terracotta', primary: '#c4724a', primaryBright: '#d98e68', primaryDark: '#9a5736', foregroundOnPrimary: '#ffffff' },
  { id: 'honey-rose', name: 'Honey Rose', primary: '#d4957a', primaryBright: '#e8b09a', primaryDark: '#a86d52', foregroundOnPrimary: '#000000' },
  { id: 'emerald-teal', name: 'Emerald Teal', primary: '#1b8b73', primaryBright: '#22a88b', primaryDark: '#146858', foregroundOnPrimary: '#ffffff' },
  { id: 'indigo-violet', name: 'Indigo Violet', primary: '#5c4db8', primaryBright: '#7262d9', primaryDark: '#45399a', foregroundOnPrimary: '#ffffff' },
  { id: 'rust-gold', name: 'Rust Gold', primary: '#b87a3a', primaryBright: '#d49952', primaryDark: '#8f5c28', foregroundOnPrimary: '#ffffff' },
  { id: 'wine-plum', name: 'Wine Plum', primary: '#7e3d5c', primaryBright: '#9a5278', primaryDark: '#5e2d45', foregroundOnPrimary: '#ffffff' },
  { id: 'frost-blue', name: 'Frost Blue', primary: '#6b9bb5', primaryBright: '#85b5ce', primaryDark: '#507890', foregroundOnPrimary: '#000000' },
  { id: 'moss', name: 'Moss', primary: '#5c7a4a', primaryBright: '#739662', primaryDark: '#445d36', foregroundOnPrimary: '#ffffff' },

  /* More single & mixed */
  { id: 'salmon', name: 'Salmon', primary: '#f9736e', primaryBright: '#fb9a96', primaryDark: '#e85a55', foregroundOnPrimary: '#000000' },
  { id: 'mauve', name: 'Mauve', primary: '#9d7a9e', primaryBright: '#b894b9', primaryDark: '#7a5c7b', foregroundOnPrimary: '#ffffff' },
  { id: 'sepia', name: 'Sepia', primary: '#8b7355', primaryBright: '#a88b6a', primaryDark: '#6b5842', foregroundOnPrimary: '#ffffff' },
  { id: 'denim', name: 'Denim', primary: '#4a6fa5', primaryBright: '#5e86c4', primaryDark: '#385582', foregroundOnPrimary: '#ffffff' },
  { id: 'clay', name: 'Clay', primary: '#a67c52', primaryBright: '#c4996a', primaryDark: '#805c3a', foregroundOnPrimary: '#ffffff' },
  { id: 'moonlight', name: 'Moonlight', primary: '#7b8aa8', primaryBright: '#9aa8c4', primaryDark: '#5c6a85', foregroundOnPrimary: '#ffffff' },
  { id: 'camel', name: 'Camel', primary: '#c4a574', primaryBright: '#d9bc8f', primaryDark: '#9a7d52', foregroundOnPrimary: '#000000' },
  { id: 'aubergine', name: 'Aubergine', primary: '#5c3d5c', primaryBright: '#735073', primaryDark: '#452e45', foregroundOnPrimary: '#ffffff' },
  { id: 'spruce', name: 'Spruce', primary: '#2d5a4a', primaryBright: '#387562', primaryDark: '#224438', foregroundOnPrimary: '#ffffff' },
  { id: 'merlot', name: 'Merlot', primary: '#6b2d4a', primaryBright: '#853d62', primaryDark: '#502238', foregroundOnPrimary: '#ffffff' },
  { id: 'pewter-blue', name: 'Pewter Blue', primary: '#6b7a8a', primaryBright: '#8596a8', primaryDark: '#505d6b', foregroundOnPrimary: '#ffffff' },
  { id: 'apricot', name: 'Apricot', primary: '#e8a86a', primaryBright: '#f0c08e', primaryDark: '#c48348', foregroundOnPrimary: '#000000' },
  { id: 'thistle', name: 'Thistle', primary: '#a87ab0', primaryBright: '#c49bcc', primaryDark: '#825c8a', foregroundOnPrimary: '#ffffff' },
  { id: 'cedar', name: 'Cedar', primary: '#6b5344', primaryBright: '#856a5a', primaryDark: '#4d3d32', foregroundOnPrimary: '#ffffff' },
  { id: 'lagoon', name: 'Lagoon', primary: '#2a8b82', primaryBright: '#35a89e', primaryDark: '#1f6b64', foregroundOnPrimary: '#ffffff' },
  { id: 'mulberry', name: 'Mulberry', primary: '#7b4a7b', primaryBright: '#966296', primaryDark: '#5a385a', foregroundOnPrimary: '#ffffff' },
  { id: 'tangerine', name: 'Tangerine', primary: '#f07838', primaryBright: '#f59a5c', primaryDark: '#c45c28', foregroundOnPrimary: '#000000' },
  { id: 'steel-blue', name: 'Steel Blue', primary: '#4a6b8a', primaryBright: '#5e86aa', primaryDark: '#38526b', foregroundOnPrimary: '#ffffff' },
  { id: 'rose-quartz', name: 'Rose Quartz', primary: '#b8a0a8', primaryBright: '#d4bcc6', primaryDark: '#8a767e', foregroundOnPrimary: '#000000' },
  { id: 'bronze-green', name: 'Bronze Green', primary: '#5c6b4a', primaryBright: '#738662', primaryDark: '#445236', foregroundOnPrimary: '#ffffff' },

  /* Vivid gradients (editable vivid set – two-tone) */
  { id: 'gradient-green-teal', name: 'Green → Teal', primary: '#4de8bf', primaryBright: '#73ff8d', primaryDark: '#29cdb2', foregroundOnPrimary: '#000000' },
  { id: 'gradient-teal-pink', name: 'Teal → Pink', primary: '#6a84b7', primaryBright: '#26d6a6', primaryDark: '#cf3388', foregroundOnPrimary: '#ffffff' },
  { id: 'gradient-orange-yellow', name: 'Orange → Yellow', primary: '#ffc72f', primaryBright: '#ffe900', primaryDark: '#ffab5e', foregroundOnPrimary: '#000000' },
  { id: 'gradient-lime', name: 'Lime', primary: '#18ff29', primaryBright: '#2aff2c', primaryDark: '#01ff25', foregroundOnPrimary: '#000000' },
  { id: 'gradient-blue-deep', name: 'Blue → Deep Blue', primary: '#004faa', primaryBright: '#008faa', primaryDark: '#000faa', foregroundOnPrimary: '#ffffff' },
  { id: 'gradient-yellow-gold', name: 'Yellow → Gold', primary: '#e6d625', primaryBright: '#eeff2a', primaryDark: '#deac21', foregroundOnPrimary: '#000000' },
  { id: 'gradient-blue-orange', name: 'Blue → Orange', primary: '#6b70ff', primaryBright: '#0089ff', primaryDark: '#d75700', foregroundOnPrimary: '#ffffff' },
  { id: 'gradient-blue-sky', name: 'Blue → Sky', primary: '#3075d0', primaryBright: '#5fffec', primaryDark: '#008bff', foregroundOnPrimary: '#000000' },
  { id: 'gradient-green-forest', name: 'Green → Forest', primary: '#53dd22', primaryBright: '#5aff00', primaryDark: '#4c7a45', foregroundOnPrimary: '#000000' },
  { id: 'gradient-magenta-lavender', name: 'Magenta → Lavender', primary: '#b458c8', primaryBright: '#8f71ff', primaryDark: '#da4097', foregroundOnPrimary: '#ffffff' },
  { id: 'gradient-pink-purple', name: 'Pink → Purple', primary: '#e963f0', primaryBright: '#cd87ff', primaryDark: '#ff40e1', foregroundOnPrimary: '#ffffff' },
  { id: 'gradient-peach-pink', name: 'Peach → Pink', primary: '#fe8c9a', primaryBright: '#fec183', primaryDark: '#ff1572', foregroundOnPrimary: '#000000' },

  /* Multi-tone: 2–4 colour stops (stops array drives gradient) */
  { id: 'tone-2-sunset', name: '2-tone Sunset', stops: ['#ff6b4a', '#ffb347'], primary: '#ff6b4a', primaryBright: '#ff6b4a', primaryDark: '#ffb347', foregroundOnPrimary: '#000000' },
  { id: 'tone-2-ocean', name: '2-tone Ocean', stops: ['#0077b6', '#00b4d8'], primary: '#0077b6', primaryBright: '#0077b6', primaryDark: '#00b4d8', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-2-forest', name: '2-tone Forest', stops: ['#2d6a4f', '#95d5b2'], primary: '#2d6a4f', primaryBright: '#2d6a4f', primaryDark: '#95d5b2', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-2-berry', name: '2-tone Berry', stops: ['#7b2cbf', '#e0aaff'], primary: '#7b2cbf', primaryBright: '#7b2cbf', primaryDark: '#e0aaff', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-fire', name: '3-tone Fire', stops: ['#ff0000', '#ff9500', '#ffea00'], primary: '#ff0000', primaryBright: '#ff0000', primaryDark: '#ffea00', foregroundOnPrimary: '#000000' },
  { id: 'tone-3-ocean-deep', name: '3-tone Ocean', stops: ['#03045e', '#0077b6', '#00b4d8'], primary: '#03045e', primaryBright: '#03045e', primaryDark: '#00b4d8', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-sunset', name: '3-tone Sunset', stops: ['#ff6b6b', '#ffa94d', '#ffd93d'], primary: '#ff6b6b', primaryBright: '#ff6b6b', primaryDark: '#ffd93d', foregroundOnPrimary: '#000000' },
  { id: 'tone-3-aurora', name: '3-tone Aurora', stops: ['#06ffa5', '#00d4ff', '#7b2cbf'], primary: '#06ffa5', primaryBright: '#06ffa5', primaryDark: '#7b2cbf', foregroundOnPrimary: '#000000' },
  { id: 'tone-3-raspberry', name: '3-tone Raspberry', stops: ['#9d0208', '#dc2f02', '#e85d04'], primary: '#9d0208', primaryBright: '#9d0208', primaryDark: '#e85d04', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-mint', name: '3-tone Mint', stops: ['#2d6a4f', '#40916c', '#95d5b2'], primary: '#2d6a4f', primaryBright: '#2d6a4f', primaryDark: '#95d5b2', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-lavender', name: '3-tone Lavender', stops: ['#5a189a', '#9d4edd', '#e0aaff'], primary: '#5a189a', primaryBright: '#5a189a', primaryDark: '#e0aaff', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-rainbow', name: '4-tone Rainbow', stops: ['#ff0000', '#ffaa00', '#00ff00', '#0088ff'], primary: '#ff0000', primaryBright: '#ff0000', primaryDark: '#0088ff', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-sunset', name: '4-tone Sunset', stops: ['#1a1a2e', '#e94560', '#ff6b6b', '#ffd93d'], primary: '#1a1a2e', primaryBright: '#1a1a2e', primaryDark: '#ffd93d', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-ocean', name: '4-tone Ocean', stops: ['#03045e', '#0077b6', '#00b4d8', '#90e0ef'], primary: '#03045e', primaryBright: '#03045e', primaryDark: '#90e0ef', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-forest', name: '4-tone Forest', stops: ['#1b4332', '#2d6a4f', '#40916c', '#95d5b2'], primary: '#1b4332', primaryBright: '#1b4332', primaryDark: '#95d5b2', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-candy', name: '4-tone Candy', stops: ['#ff006e', '#ff4081', '#ff79b0', '#ffb3d9'], primary: '#ff006e', primaryBright: '#ff006e', primaryDark: '#ffb3d9', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-neon', name: '4-tone Neon', stops: ['#00f5d4', '#00bbf9', '#9b5de5', '#f15bb5'], primary: '#00f5d4', primaryBright: '#00f5d4', primaryDark: '#f15bb5', foregroundOnPrimary: '#000000' },
  { id: 'tone-4-ember', name: '4-tone Ember', stops: ['#370617', '#9d0208', '#dc2f02', '#e85d04'], primary: '#370617', primaryBright: '#370617', primaryDark: '#e85d04', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-ice', name: '4-tone Ice', stops: ['#012a4a', '#013a63', '#014f86', '#89c2d9'], primary: '#012a4a', primaryBright: '#012a4a', primaryDark: '#89c2d9', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-wine', name: '4-tone Wine', stops: ['#3c096c', '#5a189a', '#7b2cbf', '#c77dff'], primary: '#3c096c', primaryBright: '#3c096c', primaryDark: '#c77dff', foregroundOnPrimary: '#ffffff' },

  /* Dark teals + oranges / warm combos */
  { id: 'tone-2-teal-orange', name: 'Teal → Orange', stops: ['#0d9488', '#ea580c'], primary: '#0d9488', primaryBright: '#0d9488', primaryDark: '#ea580c', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-2-dark-teal-amber', name: 'Dark Teal → Amber', stops: ['#134e4a', '#f59e0b'], primary: '#134e4a', primaryBright: '#134e4a', primaryDark: '#f59e0b', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-2-deep-teal-orange', name: 'Deep Teal → Orange', stops: ['#0f766e', '#f97316'], primary: '#0f766e', primaryBright: '#0f766e', primaryDark: '#f97316', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-teal-orange', name: '3-tone Teal Orange', stops: ['#0f766e', '#14b8a6', '#f97316'], primary: '#0f766e', primaryBright: '#0f766e', primaryDark: '#f97316', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-dark-teal-amber', name: '3-tone Dark Teal Amber', stops: ['#134e4a', '#0d9488', '#fbbf24'], primary: '#134e4a', primaryBright: '#134e4a', primaryDark: '#fbbf24', foregroundOnPrimary: '#000000' },
  { id: 'tone-3-navy-teal-orange', name: '3-tone Navy Teal Orange', stops: ['#0c4a6e', '#0d9488', '#ea580c'], primary: '#0c4a6e', primaryBright: '#0c4a6e', primaryDark: '#ea580c', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-teal-orange', name: '4-tone Teal Orange', stops: ['#134e4a', '#0d9488', '#14b8a6', '#f97316'], primary: '#134e4a', primaryBright: '#134e4a', primaryDark: '#f97316', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-dark-teal-warm', name: '4-tone Dark Teal Warm', stops: ['#042f2e', '#0d9488', '#f59e0b', '#fbbf24'], primary: '#042f2e', primaryBright: '#042f2e', primaryDark: '#fbbf24', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-2-cyan-amber', name: 'Cyan → Amber', stops: ['#0891b2', '#f59e0b'], primary: '#0891b2', primaryBright: '#0891b2', primaryDark: '#f59e0b', foregroundOnPrimary: '#000000' },
  { id: 'tone-2-slate-orange', name: 'Slate → Orange', stops: ['#475569', '#ea580c'], primary: '#475569', primaryBright: '#475569', primaryDark: '#ea580c', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-midnight-teal-amber', name: '3-tone Midnight Teal Amber', stops: ['#0f172a', '#0d9488', '#f59e0b'], primary: '#0f172a', primaryBright: '#0f172a', primaryDark: '#f59e0b', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-ocean-fire', name: '4-tone Ocean Fire', stops: ['#0c4a6e', '#0284c7', '#0d9488', '#ea580c'], primary: '#0c4a6e', primaryBright: '#0c4a6e', primaryDark: '#ea580c', foregroundOnPrimary: '#ffffff' },
];

/** Texture presets: applied as body overlay. id used for body[data-texture] and swatch preview. */
export const THEME_TEXTURES = [
  { id: 'none', name: 'None' },
  { id: 'noise', name: 'Noise' },
  { id: 'grid', name: 'Grid' },
  { id: 'dots', name: 'Dots' },
  { id: 'lines', name: 'Lines' },
  { id: 'crosshatch', name: 'Crosshatch' },
  { id: 'paper', name: 'Paper' },
  { id: 'carbon', name: 'Carbon' },
  { id: 'fabric', name: 'Fabric' },
  { id: 'grain', name: 'Grain' },
  { id: 'mesh', name: 'Mesh' },
  { id: 'stipple', name: 'Stipple' },
  { id: 'weave', name: 'Weave' },
  { id: 'brushed', name: 'Brushed' },
  { id: 'sand', name: 'Sand' },
  { id: 'diagonal', name: 'Diagonal' },
  { id: 'herringbone', name: 'Herringbone' },
  { id: 'speckle', name: 'Speckle' },
  { id: 'linen', name: 'Linen' },
  { id: 'hexagons', name: 'Hexagons' },
  { id: 'circuit', name: 'Circuit' },
  { id: 'waves', name: 'Waves' },
  { id: 'brick', name: 'Brick' },
  { id: 'concrete', name: 'Concrete' },
  { id: 'subtle-dots', name: 'Subtle Dots' },
  { id: 'fine-lines', name: 'Fine Lines' },
  { id: 'scatter', name: 'Scatter' },
];

export const DEFAULT_COLOUR_ID = 'gold';
export const DEFAULT_TEXTURE_ID = 'none';

export function getThemeColour(id) {
  return THEME_COLOURS.find((c) => c.id === id) || THEME_COLOURS[0];
}

export function getThemeTexture(id) {
  return THEME_TEXTURES.find((t) => t.id === id) || THEME_TEXTURES[0];
}
