/**
 * Theme presets: colours and textures for the app.
 * Changing theme updates Rank Progress bar, panel headers, buttons, sidebar, and all accent UI.
 */

/** Hex colour presets: { id, name, primary, primaryBright, primaryDark, foregroundOnPrimary } */
export const THEME_COLOURS = [
  { id: 'gold', name: 'Gold', primary: '#d4af37', primaryBright: '#e6c229', primaryDark: '#b8860b', foregroundOnPrimary: '#ffffff' },
  { id: 'amber', name: 'Amber', primary: '#f59e0b', primaryBright: '#fbbf24', primaryDark: '#d97706', foregroundOnPrimary: '#000000' },
  { id: 'yellow', name: 'Yellow', primary: '#eab308', primaryBright: '#facc15', primaryDark: '#ca8a04', foregroundOnPrimary: '#000000' },
  { id: 'orange', name: 'Orange', primary: '#ea580c', primaryBright: '#f97316', primaryDark: '#c2410c', foregroundOnPrimary: '#ffffff' },
  { id: 'red', name: 'Red', primary: '#dc2626', primaryBright: '#ef4444', primaryDark: '#b91c1c', foregroundOnPrimary: '#ffffff' },
  { id: 'rose', name: 'Rose', primary: '#e11d48', primaryBright: '#f43f5e', primaryDark: '#be123c', foregroundOnPrimary: '#ffffff' },
  { id: 'crimson', name: 'Crimson', primary: '#be185d', primaryBright: '#ec4899', primaryDark: '#9d174d', foregroundOnPrimary: '#ffffff' },
  { id: 'fuchsia', name: 'Fuchsia', primary: '#c026d3', primaryBright: '#d946ef', primaryDark: '#a21caf', foregroundOnPrimary: '#ffffff' },
  { id: 'violet', name: 'Violet', primary: '#7c3aed', primaryBright: '#8b5cf6', primaryDark: '#6d28d9', foregroundOnPrimary: '#ffffff' },
  { id: 'purple', name: 'Purple', primary: '#9333ea', primaryBright: '#a855f7', primaryDark: '#7e22ce', foregroundOnPrimary: '#ffffff' },
  { id: 'indigo', name: 'Indigo', primary: '#4f46e5', primaryBright: '#6366f1', primaryDark: '#4338ca', foregroundOnPrimary: '#ffffff' },
  { id: 'blue', name: 'Blue', primary: '#2563eb', primaryBright: '#3b82f6', primaryDark: '#1d4ed8', foregroundOnPrimary: '#ffffff' },
  { id: 'sky', name: 'Sky', primary: '#0ea5e9', primaryBright: '#38bdf8', primaryDark: '#0284c7', foregroundOnPrimary: '#000000' },
  { id: 'cyan', name: 'Cyan', primary: '#0891b2', primaryBright: '#22d3ee', primaryDark: '#0e7490', foregroundOnPrimary: '#000000' },
  { id: 'teal', name: 'Teal', primary: '#0d9488', primaryBright: '#2dd4bf', primaryDark: '#0f766e', foregroundOnPrimary: '#ffffff' },
  { id: 'emerald', name: 'Emerald', primary: '#059669', primaryBright: '#10b981', primaryDark: '#047857', foregroundOnPrimary: '#ffffff' },
  { id: 'green', name: 'Green', primary: '#16a34a', primaryBright: '#22c55e', primaryDark: '#15803d', foregroundOnPrimary: '#ffffff' },
  { id: 'lime', name: 'Lime', primary: '#65a30d', primaryBright: '#84cc16', primaryDark: '#4d7c0f', foregroundOnPrimary: '#000000' },
  { id: 'olive', name: 'Olive', primary: '#84cc16', primaryBright: '#a3e635', primaryDark: '#65a30d', foregroundOnPrimary: '#000000' },
  { id: 'bronze', name: 'Bronze', primary: '#b45309', primaryBright: '#d97706', primaryDark: '#92400e', foregroundOnPrimary: '#ffffff' },
  { id: 'copper', name: 'Copper', primary: '#b45309', primaryBright: '#ea580c', primaryDark: '#9a3412', foregroundOnPrimary: '#ffffff' },
  { id: 'rust', name: 'Rust', primary: '#c2410c', primaryBright: '#ea580c', primaryDark: '#9a3412', foregroundOnPrimary: '#ffffff' },
  { id: 'wine', name: 'Wine', primary: '#9f1239', primaryBright: '#be123c', primaryDark: '#881337', foregroundOnPrimary: '#ffffff' },
  { id: 'plum', name: 'Plum', primary: '#701a75', primaryBright: '#86198f', primaryDark: '#581c87', foregroundOnPrimary: '#ffffff' },
  { id: 'slate', name: 'Slate', primary: '#475569', primaryBright: '#64748b', primaryDark: '#334155', foregroundOnPrimary: '#ffffff' },
  { id: 'zinc', name: 'Zinc', primary: '#71717a', primaryBright: '#a1a1aa', primaryDark: '#52525b', foregroundOnPrimary: '#ffffff' },
  { id: 'neutral', name: 'Neutral', primary: '#737373', primaryBright: '#a3a3a3', primaryDark: '#525252', foregroundOnPrimary: '#ffffff' },
  { id: 'stone', name: 'Stone', primary: '#78716c', primaryBright: '#a8a29e', primaryDark: '#57534e', foregroundOnPrimary: '#ffffff' },
  { id: 'mint', name: 'Mint', primary: '#10b981', primaryBright: '#34d399', primaryDark: '#059669', foregroundOnPrimary: '#000000' },
  { id: 'coral', name: 'Coral', primary: '#f43f5e', primaryBright: '#fb7185', primaryDark: '#e11d48', foregroundOnPrimary: '#ffffff' },
  { id: 'peach', name: 'Peach', primary: '#fb923c', primaryBright: '#fdba74', primaryDark: '#ea580c', foregroundOnPrimary: '#000000' },
  { id: 'honey', name: 'Honey', primary: '#eab308', primaryBright: '#fde047', primaryDark: '#ca8a04', foregroundOnPrimary: '#000000' },
  { id: 'mustard', name: 'Mustard', primary: '#ca8a04', primaryBright: '#eab308', primaryDark: '#a16207', foregroundOnPrimary: '#000000' },
  { id: 'saffron', name: 'Saffron', primary: '#f59e0b', primaryBright: '#fbbf24', primaryDark: '#d97706', foregroundOnPrimary: '#000000' },
  { id: 'burgundy', name: 'Burgundy', primary: '#881337', primaryBright: '#9f1239', primaryDark: '#701a75', foregroundOnPrimary: '#ffffff' },
  { id: 'maroon', name: 'Maroon', primary: '#9f1239', primaryBright: '#be123c', primaryDark: '#881337', foregroundOnPrimary: '#ffffff' },
  { id: 'magenta', name: 'Magenta', primary: '#c026d3', primaryBright: '#e879f9', primaryDark: '#a21caf', foregroundOnPrimary: '#ffffff' },
  { id: 'lavender', name: 'Lavender', primary: '#8b5cf6', primaryBright: '#a78bfa', primaryDark: '#7c3aed', foregroundOnPrimary: '#ffffff' },
  { id: 'periwinkle', name: 'Periwinkle', primary: '#6366f1', primaryBright: '#818cf8', primaryDark: '#4f46e5', foregroundOnPrimary: '#ffffff' },
  { id: 'navy', name: 'Navy', primary: '#1e40af', primaryBright: '#2563eb', primaryDark: '#1e3a8a', foregroundOnPrimary: '#ffffff' },
  { id: 'ocean', name: 'Ocean', primary: '#0369a1', primaryBright: '#0ea5e9', primaryDark: '#075985', foregroundOnPrimary: '#ffffff' },
  { id: 'aqua', name: 'Aqua', primary: '#06b6d4', primaryBright: '#22d3ee', primaryDark: '#0891b2', foregroundOnPrimary: '#000000' },
  { id: 'jade', name: 'Jade', primary: '#0d9488', primaryBright: '#14b8a6', primaryDark: '#0f766e', foregroundOnPrimary: '#ffffff' },
  { id: 'forest', name: 'Forest', primary: '#166534', primaryBright: '#22c55e', primaryDark: '#14532d', foregroundOnPrimary: '#ffffff' },
  { id: 'sage', name: 'Sage', primary: '#4d7c0f', primaryBright: '#65a30d', primaryDark: '#3f6212', foregroundOnPrimary: '#ffffff' },
  { id: 'chartreuse', name: 'Chartreuse', primary: '#65a30d', primaryBright: '#84cc16', primaryDark: '#4d7c0f', foregroundOnPrimary: '#000000' },
  { id: 'cream', name: 'Cream', primary: '#e7e5e4', primaryBright: '#f5f5f4', primaryDark: '#d6d3d1', foregroundOnPrimary: '#000000' },
  { id: 'ivory', name: 'Ivory', primary: '#fafaf9', primaryBright: '#ffffff', primaryDark: '#e7e5e4', foregroundOnPrimary: '#000000' },
  { id: 'silver', name: 'Silver', primary: '#a8a29e', primaryBright: '#d6d3d1', primaryDark: '#78716c', foregroundOnPrimary: '#000000' },
  { id: 'chrome', name: 'Chrome', primary: '#94a3b8', primaryBright: '#cbd5e1', primaryDark: '#64748b', foregroundOnPrimary: '#000000' },
  { id: 'steel', name: 'Steel', primary: '#64748b', primaryBright: '#94a3b8', primaryDark: '#475569', foregroundOnPrimary: '#ffffff' },
  { id: 'graphite', name: 'Graphite', primary: '#44403c', primaryBright: '#57534e', primaryDark: '#292524', foregroundOnPrimary: '#ffffff' },
  { id: 'charcoal', name: 'Charcoal', primary: '#3f3f46', primaryBright: '#52525b', primaryDark: '#27272a', foregroundOnPrimary: '#ffffff' },
  { id: 'midnight', name: 'Midnight', primary: '#312e81', primaryBright: '#4338ca', primaryDark: '#1e1b4b', foregroundOnPrimary: '#ffffff' },
  { id: 'twilight', name: 'Twilight', primary: '#4c1d95', primaryBright: '#6d28d9', primaryDark: '#3b0764', foregroundOnPrimary: '#ffffff' },
  { id: 'sunset', name: 'Sunset', primary: '#c2410c', primaryBright: '#ea580c', primaryDark: '#9a3412', foregroundOnPrimary: '#ffffff' },
  { id: 'sunrise', name: 'Sunrise', primary: '#ea580c', primaryBright: '#fb923c', primaryDark: '#c2410c', foregroundOnPrimary: '#000000' },
  { id: 'blood', name: 'Blood', primary: '#991b1b', primaryBright: '#b91c1c', primaryDark: '#7f1d1d', foregroundOnPrimary: '#ffffff' },
  { id: 'royal', name: 'Royal', primary: '#3730a3', primaryBright: '#4f46e5', primaryDark: '#312e81', foregroundOnPrimary: '#ffffff' },
  { id: 'electric', name: 'Electric', primary: '#2563eb', primaryBright: '#60a5fa', primaryDark: '#1d4ed8', foregroundOnPrimary: '#ffffff' },
  { id: 'neon-green', name: 'Neon Green', primary: '#22c55e', primaryBright: '#4ade80', primaryDark: '#16a34a', foregroundOnPrimary: '#000000' },
  { id: 'neon-pink', name: 'Neon Pink', primary: '#ec4899', primaryBright: '#f472b6', primaryDark: '#db2777', foregroundOnPrimary: '#000000' },
  { id: 'neon-blue', name: 'Neon Blue', primary: '#3b82f6', primaryBright: '#60a5fa', primaryDark: '#2563eb', foregroundOnPrimary: '#ffffff' },
  { id: 'neon-orange', name: 'Neon Orange', primary: '#f97316', primaryBright: '#fb923c', primaryDark: '#ea580c', foregroundOnPrimary: '#000000' },
  { id: 'pastel-pink', name: 'Pastel Pink', primary: '#f9a8d4', primaryBright: '#fbcfe8', primaryDark: '#ec4899', foregroundOnPrimary: '#000000' },
  { id: 'pastel-blue', name: 'Pastel Blue', primary: '#93c5fd', primaryBright: '#bfdbfe', primaryDark: '#3b82f6', foregroundOnPrimary: '#000000' },
  { id: 'pastel-green', name: 'Pastel Green', primary: '#86efac', primaryBright: '#bbf7d0', primaryDark: '#22c55e', foregroundOnPrimary: '#000000' },
  { id: 'pastel-purple', name: 'Pastel Purple', primary: '#c4b5fd', primaryBright: '#ddd6fe', primaryDark: '#8b5cf6', foregroundOnPrimary: '#000000' },
  { id: 'pastel-yellow', name: 'Pastel Yellow', primary: '#fde047', primaryBright: '#fef08a', primaryDark: '#eab308', foregroundOnPrimary: '#000000' },
  { id: 'deep-red', name: 'Deep Red', primary: '#7f1d1d', primaryBright: '#991b1b', primaryDark: '#450a0a', foregroundOnPrimary: '#ffffff' },
  { id: 'deep-blue', name: 'Deep Blue', primary: '#1e3a8a', primaryBright: '#1d4ed8', primaryDark: '#172554', foregroundOnPrimary: '#ffffff' },
  { id: 'deep-green', name: 'Deep Green', primary: '#14532d', primaryBright: '#166534', primaryDark: '#052e16', foregroundOnPrimary: '#ffffff' },
  { id: 'deep-purple', name: 'Deep Purple', primary: '#581c87', primaryBright: '#6d28d9', primaryDark: '#3b0764', foregroundOnPrimary: '#ffffff' },
  { id: 'pale-gold', name: 'Pale Gold', primary: '#fcd34d', primaryBright: '#fde68a', primaryDark: '#f59e0b', foregroundOnPrimary: '#000000' },
  { id: 'antique-brass', name: 'Antique Brass', primary: '#b8860b', primaryBright: '#d4af37', primaryDark: '#8b6914', foregroundOnPrimary: '#000000' },
  { id: 'gunmetal', name: 'Gunmetal', primary: '#2d3748', primaryBright: '#4a5568', primaryDark: '#1a202c', foregroundOnPrimary: '#ffffff' },
  { id: 'ash', name: 'Ash', primary: '#6b7280', primaryBright: '#9ca3af', primaryDark: '#4b5563', foregroundOnPrimary: '#ffffff' },
  { id: 'smoke', name: 'Smoke', primary: '#6b7280', primaryBright: '#9ca3af', primaryDark: '#4b5563', foregroundOnPrimary: '#ffffff' },
  { id: 'pewter', name: 'Pewter', primary: '#78716c', primaryBright: '#a8a29e', primaryDark: '#57534e', foregroundOnPrimary: '#ffffff' },
  { id: 'titanium', name: 'Titanium', primary: '#71717a', primaryBright: '#a1a1aa', primaryDark: '#52525b', foregroundOnPrimary: '#ffffff' },
  { id: 'carbon', name: 'Carbon', primary: '#3f3f46', primaryBright: '#52525b', primaryDark: '#27272a', foregroundOnPrimary: '#ffffff' },
  { id: 'obsidian', name: 'Obsidian', primary: '#27272a', primaryBright: '#3f3f46', primaryDark: '#18181b', foregroundOnPrimary: '#ffffff' },

  /* Mixed / blended colours */
  { id: 'rose-gold', name: 'Rose Gold', primary: '#b76e79', primaryBright: '#d4a0a8', primaryDark: '#9a5a64', foregroundOnPrimary: '#ffffff' },
  { id: 'copper-rose', name: 'Copper Rose', primary: '#996872', primaryBright: '#b8838c', primaryDark: '#7a5260', foregroundOnPrimary: '#ffffff' },
  { id: 'gold-amber', name: 'Gold Amber', primary: '#d4a574', primaryBright: '#e8c49a', primaryDark: '#b8864a', foregroundOnPrimary: '#000000' },
  { id: 'teal-blue', name: 'Teal Blue', primary: '#0d7a8c', primaryBright: '#1899ad', primaryDark: '#0a5c6b', foregroundOnPrimary: '#ffffff' },
  { id: 'violet-blue', name: 'Violet Blue', primary: '#5b4bb5', primaryBright: '#7260d4', primaryDark: '#453899', foregroundOnPrimary: '#ffffff' },
  { id: 'blue-teal', name: 'Blue Teal', primary: '#2a7b8a', primaryBright: '#3596a6', primaryDark: '#1f5d6a', foregroundOnPrimary: '#ffffff' },
  { id: 'sunset-blend', name: 'Sunset Blend', primary: '#d4694a', primaryBright: '#e88a6e', primaryDark: '#a84f34', foregroundOnPrimary: '#ffffff' },
  { id: 'forest-teal', name: 'Forest Teal', primary: '#1a6b5c', primaryBright: '#228b79', primaryDark: '#124d42', foregroundOnPrimary: '#ffffff' },
  { id: 'lavender-rose', name: 'Lavender Rose', primary: '#b87ba8', primaryBright: '#d19bc4', primaryDark: '#8f5d82', foregroundOnPrimary: '#ffffff' },
  { id: 'peach-gold', name: 'Peach Gold', primary: '#e5a86a', primaryBright: '#f0c08e', primaryDark: '#c48348', foregroundOnPrimary: '#000000' },
  { id: 'coral-pink', name: 'Coral Pink', primary: '#e85d6e', primaryBright: '#f07d8c', primaryDark: '#c94a5a', foregroundOnPrimary: '#ffffff' },
  { id: 'mint-blue', name: 'Mint Blue', primary: '#3db5a0', primaryBright: '#5ac9b5', primaryDark: '#2d8f7e', foregroundOnPrimary: '#000000' },
  { id: 'plum-violet', name: 'Plum Violet', primary: '#7e4d8e', primaryBright: '#9664a8', primaryDark: '#623a70', foregroundOnPrimary: '#ffffff' },
  { id: 'amber-copper', name: 'Amber Copper', primary: '#c4783a', primaryBright: '#d9945a', primaryDark: '#9d5c28', foregroundOnPrimary: '#ffffff' },
  { id: 'olive-gold', name: 'Olive Gold', primary: '#9a9b4a', primaryBright: '#b4b562', primaryDark: '#78793a', foregroundOnPrimary: '#000000' },
  { id: 'sage-blue', name: 'Sage Blue', primary: '#5a7a7a', primaryBright: '#739696', primaryDark: '#445d5d', foregroundOnPrimary: '#ffffff' },
  { id: 'dusty-rose', name: 'Dusty Rose', primary: '#c49a9a', primaryBright: '#dbb5b5', primaryDark: '#9a7272', foregroundOnPrimary: '#000000' },
  { id: 'muted-teal', name: 'Muted Teal', primary: '#4a7c7c', primaryBright: '#5e9999', primaryDark: '#385d5d', foregroundOnPrimary: '#ffffff' },
  { id: 'blush', name: 'Blush', primary: '#d4a5a5', primaryBright: '#e8c2c2', primaryDark: '#a67a7a', foregroundOnPrimary: '#000000' },
  { id: 'sea-green', name: 'Sea Green', primary: '#2e8b7a', primaryBright: '#3aa896', primaryDark: '#236b5d', foregroundOnPrimary: '#ffffff' },
  { id: 'berry', name: 'Berry', primary: '#8b4a6b', primaryBright: '#a65f85', primaryDark: '#6a3952', foregroundOnPrimary: '#ffffff' },
  { id: 'slate-blue', name: 'Slate Blue', primary: '#5c6b8a', primaryBright: '#7486a8', primaryDark: '#45526a', foregroundOnPrimary: '#ffffff' },
  { id: 'dusty-lavender', name: 'Dusty Lavender', primary: '#8b7a9a', primaryBright: '#a594b5', primaryDark: '#6a5c78', foregroundOnPrimary: '#ffffff' },
  { id: 'terracotta', name: 'Terracotta', primary: '#c4724a', primaryBright: '#d98e68', primaryDark: '#9a5736', foregroundOnPrimary: '#ffffff' },
  { id: 'honey-rose', name: 'Honey Rose', primary: '#d4957a', primaryBright: '#e8b09a', primaryDark: '#a86d52', foregroundOnPrimary: '#000000' },
  { id: 'emerald-teal', name: 'Emerald Teal', primary: '#1b8b73', primaryBright: '#22a88b', primaryDark: '#146858', foregroundOnPrimary: '#ffffff' },
  { id: 'indigo-violet', name: 'Indigo Violet', primary: '#5c4db8', primaryBright: '#7262d9', primaryDark: '#45399a', foregroundOnPrimary: '#ffffff' },
  { id: 'rust-gold', name: 'Rust Gold', primary: '#b87a3a', primaryBright: '#d49952', primaryDark: '#8f5c28', foregroundOnPrimary: '#ffffff' },
  { id: 'wine-plum', name: 'Wine Plum', primary: '#7e3d5c', primaryBright: '#9a5278', primaryDark: '#5e2d45', foregroundOnPrimary: '#ffffff' },
  { id: 'frost-blue', name: 'Frost Blue', primary: '#6b9bb5', primaryBright: '#85b5ce', primaryDark: '#507890', foregroundOnPrimary: '#000000' },
  { id: 'moss', name: 'Moss', primary: '#5c7a4a', primaryBright: '#739662', primaryDark: '#445d36', foregroundOnPrimary: '#ffffff' },

  /* More single & mixed */
  { id: 'salmon', name: 'Salmon', primary: '#f9736e', primaryBright: '#fb9a96', primaryDark: '#e85a55', foregroundOnPrimary: '#000000' },
  { id: 'mauve', name: 'Mauve', primary: '#9d7a9e', primaryBright: '#b894b9', primaryDark: '#7a5c7b', foregroundOnPrimary: '#ffffff' },
  { id: 'sepia', name: 'Sepia', primary: '#8b7355', primaryBright: '#a88b6a', primaryDark: '#6b5842', foregroundOnPrimary: '#ffffff' },
  { id: 'denim', name: 'Denim', primary: '#4a6fa5', primaryBright: '#5e86c4', primaryDark: '#385582', foregroundOnPrimary: '#ffffff' },
  { id: 'clay', name: 'Clay', primary: '#a67c52', primaryBright: '#c4996a', primaryDark: '#805c3a', foregroundOnPrimary: '#ffffff' },
  { id: 'moonlight', name: 'Moonlight', primary: '#7b8aa8', primaryBright: '#9aa8c4', primaryDark: '#5c6a85', foregroundOnPrimary: '#ffffff' },
  { id: 'camel', name: 'Camel', primary: '#c4a574', primaryBright: '#d9bc8f', primaryDark: '#9a7d52', foregroundOnPrimary: '#000000' },
  { id: 'aubergine', name: 'Aubergine', primary: '#5c3d5c', primaryBright: '#735073', primaryDark: '#452e45', foregroundOnPrimary: '#ffffff' },
  { id: 'spruce', name: 'Spruce', primary: '#2d5a4a', primaryBright: '#387562', primaryDark: '#224438', foregroundOnPrimary: '#ffffff' },
  { id: 'merlot', name: 'Merlot', primary: '#6b2d4a', primaryBright: '#853d62', primaryDark: '#502238', foregroundOnPrimary: '#ffffff' },
  { id: 'pewter-blue', name: 'Pewter Blue', primary: '#6b7a8a', primaryBright: '#8596a8', primaryDark: '#505d6b', foregroundOnPrimary: '#ffffff' },
  { id: 'apricot', name: 'Apricot', primary: '#e8a86a', primaryBright: '#f0c08e', primaryDark: '#c48348', foregroundOnPrimary: '#000000' },
  { id: 'thistle', name: 'Thistle', primary: '#a87ab0', primaryBright: '#c49bcc', primaryDark: '#825c8a', foregroundOnPrimary: '#ffffff' },
  { id: 'cedar', name: 'Cedar', primary: '#6b5344', primaryBright: '#856a5a', primaryDark: '#4d3d32', foregroundOnPrimary: '#ffffff' },
  { id: 'lagoon', name: 'Lagoon', primary: '#2a8b82', primaryBright: '#35a89e', primaryDark: '#1f6b64', foregroundOnPrimary: '#ffffff' },
  { id: 'mulberry', name: 'Mulberry', primary: '#7b4a7b', primaryBright: '#966296', primaryDark: '#5a385a', foregroundOnPrimary: '#ffffff' },
  { id: 'tangerine', name: 'Tangerine', primary: '#f07838', primaryBright: '#f59a5c', primaryDark: '#c45c28', foregroundOnPrimary: '#000000' },
  { id: 'steel-blue', name: 'Steel Blue', primary: '#4a6b8a', primaryBright: '#5e86aa', primaryDark: '#38526b', foregroundOnPrimary: '#ffffff' },
  { id: 'rose-quartz', name: 'Rose Quartz', primary: '#b8a0a8', primaryBright: '#d4bcc6', primaryDark: '#8a767e', foregroundOnPrimary: '#000000' },
  { id: 'bronze-green', name: 'Bronze Green', primary: '#5c6b4a', primaryBright: '#738662', primaryDark: '#445236', foregroundOnPrimary: '#ffffff' },

  /* Vivid gradients (editable vivid set – two-tone) */
  { id: 'gradient-green-teal', name: 'Green → Teal', primary: '#4de8bf', primaryBright: '#73ff8d', primaryDark: '#29cdb2', foregroundOnPrimary: '#000000' },
  { id: 'gradient-teal-pink', name: 'Teal → Pink', primary: '#6a84b7', primaryBright: '#26d6a6', primaryDark: '#cf3388', foregroundOnPrimary: '#ffffff' },
  { id: 'gradient-orange-yellow', name: 'Orange → Yellow', primary: '#ffc72f', primaryBright: '#ffe900', primaryDark: '#ffab5e', foregroundOnPrimary: '#000000' },
  { id: 'gradient-lime', name: 'Lime', primary: '#18ff29', primaryBright: '#2aff2c', primaryDark: '#01ff25', foregroundOnPrimary: '#000000' },
  { id: 'gradient-blue-deep', name: 'Blue → Deep Blue', primary: '#004faa', primaryBright: '#008faa', primaryDark: '#000faa', foregroundOnPrimary: '#ffffff' },
  { id: 'gradient-yellow-gold', name: 'Yellow → Gold', primary: '#e6d625', primaryBright: '#eeff2a', primaryDark: '#deac21', foregroundOnPrimary: '#000000' },
  { id: 'gradient-blue-orange', name: 'Blue → Orange', primary: '#6b70ff', primaryBright: '#0089ff', primaryDark: '#d75700', foregroundOnPrimary: '#ffffff' },
  { id: 'gradient-blue-sky', name: 'Blue → Sky', primary: '#3075d0', primaryBright: '#5fffec', primaryDark: '#008bff', foregroundOnPrimary: '#000000' },
  { id: 'gradient-green-forest', name: 'Green → Forest', primary: '#53dd22', primaryBright: '#5aff00', primaryDark: '#4c7a45', foregroundOnPrimary: '#000000' },
  { id: 'gradient-magenta-lavender', name: 'Magenta → Lavender', primary: '#b458c8', primaryBright: '#8f71ff', primaryDark: '#da4097', foregroundOnPrimary: '#ffffff' },
  { id: 'gradient-pink-purple', name: 'Pink → Purple', primary: '#e963f0', primaryBright: '#cd87ff', primaryDark: '#ff40e1', foregroundOnPrimary: '#ffffff' },
  { id: 'gradient-peach-pink', name: 'Peach → Pink', primary: '#fe8c9a', primaryBright: '#fec183', primaryDark: '#ff1572', foregroundOnPrimary: '#000000' },

  /* Multi-tone: 2–4 colour stops (stops array drives gradient) */
  { id: 'tone-2-sunset', name: '2-tone Sunset', stops: ['#ff6b4a', '#ffb347'], primary: '#ff6b4a', primaryBright: '#ff6b4a', primaryDark: '#ffb347', foregroundOnPrimary: '#000000' },
  { id: 'tone-2-ocean', name: '2-tone Ocean', stops: ['#0077b6', '#00b4d8'], primary: '#0077b6', primaryBright: '#0077b6', primaryDark: '#00b4d8', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-2-forest', name: '2-tone Forest', stops: ['#2d6a4f', '#95d5b2'], primary: '#2d6a4f', primaryBright: '#2d6a4f', primaryDark: '#95d5b2', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-2-berry', name: '2-tone Berry', stops: ['#7b2cbf', '#e0aaff'], primary: '#7b2cbf', primaryBright: '#7b2cbf', primaryDark: '#e0aaff', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-fire', name: '3-tone Fire', stops: ['#ff0000', '#ff9500', '#ffea00'], primary: '#ff0000', primaryBright: '#ff0000', primaryDark: '#ffea00', foregroundOnPrimary: '#000000' },
  { id: 'tone-3-ocean-deep', name: '3-tone Ocean', stops: ['#03045e', '#0077b6', '#00b4d8'], primary: '#03045e', primaryBright: '#03045e', primaryDark: '#00b4d8', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-sunset', name: '3-tone Sunset', stops: ['#ff6b6b', '#ffa94d', '#ffd93d'], primary: '#ff6b6b', primaryBright: '#ff6b6b', primaryDark: '#ffd93d', foregroundOnPrimary: '#000000' },
  { id: 'tone-3-aurora', name: '3-tone Aurora', stops: ['#06ffa5', '#00d4ff', '#7b2cbf'], primary: '#06ffa5', primaryBright: '#06ffa5', primaryDark: '#7b2cbf', foregroundOnPrimary: '#000000' },
  { id: 'tone-3-raspberry', name: '3-tone Raspberry', stops: ['#9d0208', '#dc2f02', '#e85d04'], primary: '#9d0208', primaryBright: '#9d0208', primaryDark: '#e85d04', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-mint', name: '3-tone Mint', stops: ['#2d6a4f', '#40916c', '#95d5b2'], primary: '#2d6a4f', primaryBright: '#2d6a4f', primaryDark: '#95d5b2', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-lavender', name: '3-tone Lavender', stops: ['#5a189a', '#9d4edd', '#e0aaff'], primary: '#5a189a', primaryBright: '#5a189a', primaryDark: '#e0aaff', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-rainbow', name: '4-tone Rainbow', stops: ['#ff0000', '#ffaa00', '#00ff00', '#0088ff'], primary: '#ff0000', primaryBright: '#ff0000', primaryDark: '#0088ff', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-sunset', name: '4-tone Sunset', stops: ['#1a1a2e', '#e94560', '#ff6b6b', '#ffd93d'], primary: '#1a1a2e', primaryBright: '#1a1a2e', primaryDark: '#ffd93d', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-ocean', name: '4-tone Ocean', stops: ['#03045e', '#0077b6', '#00b4d8', '#90e0ef'], primary: '#03045e', primaryBright: '#03045e', primaryDark: '#90e0ef', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-forest', name: '4-tone Forest', stops: ['#1b4332', '#2d6a4f', '#40916c', '#95d5b2'], primary: '#1b4332', primaryBright: '#1b4332', primaryDark: '#95d5b2', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-candy', name: '4-tone Candy', stops: ['#ff006e', '#ff4081', '#ff79b0', '#ffb3d9'], primary: '#ff006e', primaryBright: '#ff006e', primaryDark: '#ffb3d9', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-neon', name: '4-tone Neon', stops: ['#00f5d4', '#00bbf9', '#9b5de5', '#f15bb5'], primary: '#00f5d4', primaryBright: '#00f5d4', primaryDark: '#f15bb5', foregroundOnPrimary: '#000000' },
  { id: 'tone-4-ember', name: '4-tone Ember', stops: ['#370617', '#9d0208', '#dc2f02', '#e85d04'], primary: '#370617', primaryBright: '#370617', primaryDark: '#e85d04', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-ice', name: '4-tone Ice', stops: ['#012a4a', '#013a63', '#014f86', '#89c2d9'], primary: '#012a4a', primaryBright: '#012a4a', primaryDark: '#89c2d9', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-wine', name: '4-tone Wine', stops: ['#3c096c', '#5a189a', '#7b2cbf', '#c77dff'], primary: '#3c096c', primaryBright: '#3c096c', primaryDark: '#c77dff', foregroundOnPrimary: '#ffffff' },

  /* Dark teals + oranges / warm combos */
  { id: 'tone-2-teal-orange', name: 'Teal → Orange', stops: ['#0d9488', '#ea580c'], primary: '#0d9488', primaryBright: '#0d9488', primaryDark: '#ea580c', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-2-dark-teal-amber', name: 'Dark Teal → Amber', stops: ['#134e4a', '#f59e0b'], primary: '#134e4a', primaryBright: '#134e4a', primaryDark: '#f59e0b', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-2-deep-teal-orange', name: 'Deep Teal → Orange', stops: ['#0f766e', '#f97316'], primary: '#0f766e', primaryBright: '#0f766e', primaryDark: '#f97316', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-teal-orange', name: '3-tone Teal Orange', stops: ['#0f766e', '#14b8a6', '#f97316'], primary: '#0f766e', primaryBright: '#0f766e', primaryDark: '#f97316', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-dark-teal-amber', name: '3-tone Dark Teal Amber', stops: ['#134e4a', '#0d9488', '#fbbf24'], primary: '#134e4a', primaryBright: '#134e4a', primaryDark: '#fbbf24', foregroundOnPrimary: '#000000' },
  { id: 'tone-3-navy-teal-orange', name: '3-tone Navy Teal Orange', stops: ['#0c4a6e', '#0d9488', '#ea580c'], primary: '#0c4a6e', primaryBright: '#0c4a6e', primaryDark: '#ea580c', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-teal-orange', name: '4-tone Teal Orange', stops: ['#134e4a', '#0d9488', '#14b8a6', '#f97316'], primary: '#134e4a', primaryBright: '#134e4a', primaryDark: '#f97316', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-dark-teal-warm', name: '4-tone Dark Teal Warm', stops: ['#042f2e', '#0d9488', '#f59e0b', '#fbbf24'], primary: '#042f2e', primaryBright: '#042f2e', primaryDark: '#fbbf24', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-2-cyan-amber', name: 'Cyan → Amber', stops: ['#0891b2', '#f59e0b'], primary: '#0891b2', primaryBright: '#0891b2', primaryDark: '#f59e0b', foregroundOnPrimary: '#000000' },
  { id: 'tone-2-slate-orange', name: 'Slate → Orange', stops: ['#475569', '#ea580c'], primary: '#475569', primaryBright: '#475569', primaryDark: '#ea580c', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-3-midnight-teal-amber', name: '3-tone Midnight Teal Amber', stops: ['#0f172a', '#0d9488', '#f59e0b'], primary: '#0f172a', primaryBright: '#0f172a', primaryDark: '#f59e0b', foregroundOnPrimary: '#ffffff' },
  { id: 'tone-4-ocean-fire', name: '4-tone Ocean Fire', stops: ['#0c4a6e', '#0284c7', '#0d9488', '#ea580c'], primary: '#0c4a6e', primaryBright: '#0c4a6e', primaryDark: '#ea580c', foregroundOnPrimary: '#ffffff' },

  /* Glossy – richer, saturated, reflective feel */
  { id: 'glossy-gold', name: 'Glossy Gold', primary: '#e6c229', primaryBright: '#f5d654', primaryDark: '#c9a227', foregroundOnPrimary: '#000000' },
  { id: 'glossy-teal', name: 'Glossy Teal', primary: '#14b8a6', primaryBright: '#2dd4bf', primaryDark: '#0d9488', foregroundOnPrimary: '#000000' },
  { id: 'glossy-blue', name: 'Glossy Blue', primary: '#3b82f6', primaryBright: '#60a5fa', primaryDark: '#2563eb', foregroundOnPrimary: '#ffffff' },
  { id: 'glossy-rose', name: 'Glossy Rose', primary: '#f43f5e', primaryBright: '#fb7185', primaryDark: '#e11d48', foregroundOnPrimary: '#ffffff' },
  { id: 'glossy-emerald', name: 'Glossy Emerald', primary: '#10b981', primaryBright: '#34d399', primaryDark: '#059669', foregroundOnPrimary: '#000000' },
  { id: 'glossy-violet', name: 'Glossy Violet', primary: '#8b5cf6', primaryBright: '#a78bfa', primaryDark: '#7c3aed', foregroundOnPrimary: '#ffffff' },
  /* Matte – muted, flat, soft */
  { id: 'matte-slate', name: 'Matte Slate', primary: '#64748b', primaryBright: '#94a3b8', primaryDark: '#475569', foregroundOnPrimary: '#ffffff' },
  { id: 'matte-sage', name: 'Matte Sage', primary: '#5a6b5a', primaryBright: '#739673', primaryDark: '#445d44', foregroundOnPrimary: '#ffffff' },
  { id: 'matte-dust', name: 'Matte Dust', primary: '#a8a29e', primaryBright: '#d6d3d1', primaryDark: '#78716c', foregroundOnPrimary: '#000000' },
  { id: 'matte-mauve', name: 'Matte Mauve', primary: '#8b7a8e', primaryBright: '#a594a8', primaryDark: '#6a5c6e', foregroundOnPrimary: '#ffffff' },
  { id: 'matte-navy', name: 'Matte Navy', primary: '#334155', primaryBright: '#475569', primaryDark: '#1e293b', foregroundOnPrimary: '#ffffff' },
  { id: 'matte-terracotta', name: 'Matte Terracotta', primary: '#a67c6b', primaryBright: '#c49a8a', primaryDark: '#7a5a4a', foregroundOnPrimary: '#ffffff' },

  /* Extra deep darks */
  { id: 'deep-ink', name: 'Deep Ink', primary: '#0f172a', primaryBright: '#1e293b', primaryDark: '#020617', foregroundOnPrimary: '#ffffff' },
  { id: 'pitch', name: 'Pitch', primary: '#18181b', primaryBright: '#27272a', primaryDark: '#09090b', foregroundOnPrimary: '#ffffff' },
  { id: 'deep-navy', name: 'Deep Navy', primary: '#0c1929', primaryBright: '#1e3a5f', primaryDark: '#051018', foregroundOnPrimary: '#ffffff' },
  { id: 'deep-forest', name: 'Deep Forest', primary: '#052e16', primaryBright: '#14532d', primaryDark: '#021c0e', foregroundOnPrimary: '#ffffff' },
  { id: 'deep-wine', name: 'Deep Wine', primary: '#450a0a', primaryBright: '#7f1d1d', primaryDark: '#2a0606', foregroundOnPrimary: '#ffffff' },
  { id: 'deep-plum', name: 'Deep Plum', primary: '#3b0764', primaryBright: '#581c87', primaryDark: '#1e0332', foregroundOnPrimary: '#ffffff' },
  { id: 'shadow-dark', name: 'Shadow Dark', primary: '#1f2937', primaryBright: '#374151', primaryDark: '#111827', foregroundOnPrimary: '#ffffff' },
  { id: 'iron-dark', name: 'Iron Dark', primary: '#27272a', primaryBright: '#3f3f46', primaryDark: '#18181b', foregroundOnPrimary: '#ffffff' },
  { id: 'slate-deep', name: 'Slate Deep', primary: '#0f172a', primaryBright: '#1e293b', primaryDark: '#020617', foregroundOnPrimary: '#ffffff' },
  { id: 'teal-deep', name: 'Teal Deep', primary: '#042f2e', primaryBright: '#134e4a', primaryDark: '#021c1b', foregroundOnPrimary: '#ffffff' },
  /* Extra deep lights */
  { id: 'silk', name: 'Silk', primary: '#fefefe', primaryBright: '#ffffff', primaryDark: '#f5f5f5', foregroundOnPrimary: '#000000' },
  { id: 'snow-white', name: 'Snow White', primary: '#fffefe', primaryBright: '#ffffff', primaryDark: '#fafafa', foregroundOnPrimary: '#000000' },
  { id: 'linen-light', name: 'Linen Light', primary: '#fdf8f3', primaryBright: '#fefaf5', primaryDark: '#f5ebe0', foregroundOnPrimary: '#000000' },
  { id: 'pearl-white', name: 'Pearl White', primary: '#fcfcfb', primaryBright: '#ffffff', primaryDark: '#f0f0ee', foregroundOnPrimary: '#000000' },
  { id: 'ivory-light', name: 'Ivory Light', primary: '#fffff0', primaryBright: '#fffffa', primaryDark: '#f5f5e6', foregroundOnPrimary: '#000000' },
  { id: 'cream-light', name: 'Cream Light', primary: '#fffef5', primaryBright: '#fffffb', primaryDark: '#faf8eb', foregroundOnPrimary: '#000000' },
  { id: 'frost-white', name: 'Frost White', primary: '#f0faff', primaryBright: '#f8fcff', primaryDark: '#e0f2fe', foregroundOnPrimary: '#000000' },
  { id: 'blush-white', name: 'Blush White', primary: '#fff5f8', primaryBright: '#fffafc', primaryDark: '#fce7ef', foregroundOnPrimary: '#000000' },
  { id: 'mint-white', name: 'Mint White', primary: '#f0fff8', primaryBright: '#f7fffc', primaryDark: '#d1fae5', foregroundOnPrimary: '#000000' },
  /* Extra mid tones */
  { id: 'storm', name: 'Storm', primary: '#4b5563', primaryBright: '#6b7280', primaryDark: '#374151', foregroundOnPrimary: '#ffffff' },
  { id: 'fog', name: 'Fog', primary: '#9ca3af', primaryBright: '#d1d5db', primaryDark: '#6b7280', foregroundOnPrimary: '#000000' },
  { id: 'dove', name: 'Dove', primary: '#e5e7eb', primaryBright: '#f3f4f6', primaryDark: '#d1d5db', foregroundOnPrimary: '#000000' },
  { id: 'flint', name: 'Flint', primary: '#57534e', primaryBright: '#78716c', primaryDark: '#44403c', foregroundOnPrimary: '#ffffff' },
  { id: 'battleship', name: 'Battleship', primary: '#64748b', primaryBright: '#94a3b8', primaryDark: '#475569', foregroundOnPrimary: '#ffffff' },
  { id: 'mink', name: 'Mink', primary: '#78716c', primaryBright: '#a8a29e', primaryDark: '#57534e', foregroundOnPrimary: '#ffffff' },
  { id: 'taupe', name: 'Taupe', primary: '#8b7355', primaryBright: '#a88b6a', primaryDark: '#6b5842', foregroundOnPrimary: '#ffffff' },
  { id: 'sage-mid', name: 'Sage Mid', primary: '#6b7c6b', primaryBright: '#8a9e8a', primaryDark: '#4d5c4d', foregroundOnPrimary: '#ffffff' },
  { id: 'dust', name: 'Dust', primary: '#a8a29e', primaryBright: '#d6d3d1', primaryDark: '#78716c', foregroundOnPrimary: '#000000' },
];

/** Display order: sections for main/button/line colours. Colours not listed go in "More". */
export const THEME_COLOUR_SECTIONS = [
  { label: 'Default', ids: ['gold'] },
  { label: 'Deep dark', ids: ['obsidian', 'carbon', 'gunmetal', 'deep-red', 'deep-blue', 'deep-green', 'deep-purple', 'deep-ink', 'pitch', 'deep-navy', 'deep-forest', 'deep-wine', 'deep-plum', 'shadow-dark', 'iron-dark', 'slate-deep', 'teal-deep', 'midnight', 'twilight'] },
  { label: 'Dark', ids: ['charcoal', 'graphite', 'blood', 'navy', 'ocean', 'forest', 'wine', 'plum', 'ash', 'smoke', 'pewter', 'titanium', 'steel', 'aubergine', 'spruce', 'merlot', 'cedar'] },
  { label: 'Mid', ids: ['slate', 'zinc', 'neutral', 'stone', 'storm', 'fog', 'flint', 'battleship', 'mink', 'taupe', 'sage-mid', 'dust', 'denim', 'moonlight', 'pewter-blue', 'mauve', 'sepia', 'clay', 'rose-quartz', 'bronze-green'] },
  { label: 'Light', ids: ['cream', 'ivory', 'silver', 'chrome', 'dove', 'silk', 'snow-white', 'linen-light', 'pearl-white', 'ivory-light', 'cream-light', 'frost-white', 'blush-white', 'mint-white'] },
  { label: 'Bright & vivid', ids: ['amber', 'yellow', 'orange', 'red', 'rose', 'crimson', 'fuchsia', 'violet', 'purple', 'indigo', 'blue', 'sky', 'cyan', 'teal', 'emerald', 'green', 'lime', 'olive', 'electric', 'royal', 'coral', 'peach', 'honey', 'mustard', 'saffron', 'tangerine', 'salmon'] },
  { label: 'Pastel', ids: ['pastel-pink', 'pastel-blue', 'pastel-green', 'pastel-purple', 'pastel-yellow'] },
  { label: 'Neon', ids: ['neon-green', 'neon-pink', 'neon-blue', 'neon-orange'] },
  { label: 'Mixed & blends', ids: ['rose-gold', 'copper-rose', 'gold-amber', 'teal-blue', 'violet-blue', 'blue-teal', 'sunset-blend', 'forest-teal', 'lavender-rose', 'peach-gold', 'coral-pink', 'mint-blue', 'plum-violet', 'amber-copper', 'olive-gold', 'sage-blue', 'dusty-rose', 'muted-teal', 'blush', 'sea-green', 'berry', 'slate-blue', 'dusty-lavender', 'terracotta', 'honey-rose', 'emerald-teal', 'indigo-violet', 'rust-gold', 'wine-plum', 'frost-blue', 'moss', 'thistle', 'apricot', 'camel', 'bronze', 'copper', 'rust', 'magenta', 'lavender', 'periwinkle', 'aqua', 'jade', 'sage', 'chartreuse', 'mint'] },
  { label: 'Gradients', ids: ['gradient-green-teal', 'gradient-teal-pink', 'gradient-orange-yellow', 'gradient-lime', 'gradient-blue-deep', 'gradient-yellow-gold', 'gradient-blue-orange', 'gradient-blue-sky', 'gradient-green-forest', 'gradient-magenta-lavender', 'gradient-pink-purple', 'gradient-peach-pink', 'tone-2-sunset', 'tone-2-ocean', 'tone-2-forest', 'tone-2-berry', 'tone-3-fire', 'tone-3-ocean-deep', 'tone-3-sunset', 'tone-3-aurora', 'tone-3-raspberry', 'tone-3-mint', 'tone-3-lavender', 'tone-4-rainbow', 'tone-4-sunset', 'tone-4-ocean', 'tone-4-forest', 'tone-4-candy', 'tone-4-neon', 'tone-4-ember', 'tone-4-ice', 'tone-4-wine', 'tone-2-teal-orange', 'tone-2-dark-teal-amber', 'tone-2-deep-teal-orange', 'tone-3-teal-orange', 'tone-3-dark-teal-amber', 'tone-3-navy-teal-orange', 'tone-4-teal-orange', 'tone-4-dark-teal-warm', 'tone-2-cyan-amber', 'tone-2-slate-orange', 'tone-3-midnight-teal-amber', 'tone-4-ocean-fire'] },
  { label: 'Glossy & matte', ids: ['glossy-gold', 'glossy-teal', 'glossy-blue', 'glossy-rose', 'glossy-emerald', 'glossy-violet', 'matte-slate', 'matte-sage', 'matte-dust', 'matte-mauve', 'matte-navy', 'matte-terracotta'] },
  { label: 'More', ids: ['sunset', 'sunrise', 'pale-gold', 'antique-brass', 'lagoon', 'mulberry', 'steel-blue'] },
];

/** Texture presets: applied as body overlay. id used for body[data-texture] and swatch preview. */
export const THEME_TEXTURES = [
  { id: 'none', name: 'None' },
  { id: 'grid', name: 'Grid' },
  { id: 'lines', name: 'Lines' },
  { id: 'crosshatch', name: 'Crosshatch' },
  { id: 'hexagons', name: 'Hexagons' },
  { id: 'fine-lines', name: 'Fine Lines' },
];

/** Writing style: heading + body font family (CSS font-family value). */
export const THEME_FONTS = [
  { id: 'classic', name: 'Classic', heading: '"Playfair Display", Georgia, serif', body: 'Inter, system-ui, sans-serif' },
  { id: 'modern', name: 'Modern', heading: 'system-ui, -apple-system, sans-serif', body: 'system-ui, -apple-system, sans-serif' },
  { id: 'newspaper', name: 'Newspaper', heading: 'Georgia, "Times New Roman", serif', body: 'Georgia, "Times New Roman", serif' },
  { id: 'clean', name: 'Clean', heading: '"Segoe UI", system-ui, sans-serif', body: '"Segoe UI", system-ui, sans-serif' },
  { id: 'compact', name: 'Compact', heading: 'Inter, system-ui, sans-serif', body: 'Inter, system-ui, sans-serif' },
];

/** Text style: weight and slant (applies to body/heading base). */
export const THEME_TEXT_STYLES = [
  { id: 'normal', name: 'Normal', fontWeight: '400', fontStyle: 'normal' },
  { id: 'bold', name: 'Bold', fontWeight: '700', fontStyle: 'normal' },
  { id: 'italic', name: 'Italic', fontWeight: '400', fontStyle: 'italic' },
  { id: 'bold-italic', name: 'Bold italic', fontWeight: '700', fontStyle: 'italic' },
  { id: 'light', name: 'Light', fontWeight: '300', fontStyle: 'normal' },
  { id: 'medium', name: 'Medium', fontWeight: '500', fontStyle: 'normal' },
  { id: 'semibold', name: 'Semibold', fontWeight: '600', fontStyle: 'normal' },
];

/** Button style: look and feel of primary buttons. */
export const THEME_BUTTON_STYLES = [
  { id: 'original', name: 'Original' },
  { id: 'glossy', name: 'Glossy' },
  { id: 'shaded', name: 'Shaded' },
  { id: 'opaque', name: 'Opaque' },
  { id: 'shadow', name: 'Shadow' },
  { id: 'raised', name: 'Raised' },
  { id: 'flat', name: 'Flat' },
  { id: 'outline', name: 'Outline' },
];

/** Writing (text) colour: main body and muted text. { id, name, foreground, muted } hex. */
export const THEME_WRITING_COLOURS = [
  /* Default & light */
  { id: 'default', name: 'Default', foreground: '#f5f5f5', muted: '#a1a1aa' },
  { id: 'snow', name: 'Snow', foreground: '#fafafa', muted: '#d4d4d4' },
  { id: 'pearl', name: 'Pearl', foreground: '#f5f5f4', muted: '#a8a29e' },
  { id: 'ivory-text', name: 'Ivory', foreground: '#fefce8', muted: '#e7e5e4' },
  { id: 'cream-text', name: 'Cream', foreground: '#fffbeb', muted: '#d6d3d1' },
  { id: 'warm-white', name: 'Warm White', foreground: '#fef3c7', muted: '#fde68a' },
  { id: 'cool-white', name: 'Cool White', foreground: '#f0f9ff', muted: '#bae6fd' },
  { id: 'bone', name: 'Bone', foreground: '#faf6f0', muted: '#e8e2d8' },
  { id: 'eggshell', name: 'Eggshell', foreground: '#f0ebe3', muted: '#c9c2b5' },
  { id: 'linen', name: 'Linen', foreground: '#faf0e6', muted: '#e8dcc8' },
  { id: 'vanilla', name: 'Vanilla', foreground: '#fef9e7', muted: '#f5e6b3' },
  { id: 'honeydew', name: 'Honeydew', foreground: '#f0fff0', muted: '#c6f6c6' },
  { id: 'azure', name: 'Azure', foreground: '#f0f8ff', muted: '#b8daff' },
  { id: 'alabaster', name: 'Alabaster', foreground: '#fafafa', muted: '#e8e8e8' },
  { id: 'chalk', name: 'Chalk', foreground: '#f7f7f7', muted: '#d0d0d0' },
  { id: 'milk', name: 'Milk', foreground: '#fefefe', muted: '#e0e0e0' },
  /* Grays – light to dark */
  { id: 'gray-50', name: 'Gray 50', foreground: '#f9fafb', muted: '#e5e7eb' },
  { id: 'gray-100', name: 'Gray 100', foreground: '#f3f4f6', muted: '#d1d5db' },
  { id: 'gray-200', name: 'Gray 200', foreground: '#e5e7eb', muted: '#9ca3af' },
  { id: 'gray-300', name: 'Gray 300', foreground: '#d1d5db', muted: '#6b7280' },
  { id: 'gray-400', name: 'Gray 400', foreground: '#9ca3af', muted: '#4b5563' },
  { id: 'gray-500', name: 'Gray 500', foreground: '#6b7280', muted: '#374151' },
  { id: 'zinc-100', name: 'Zinc 100', foreground: '#f4f4f5', muted: '#a1a1aa' },
  { id: 'zinc-200', name: 'Zinc 200', foreground: '#e4e4e7', muted: '#71717a' },
  { id: 'zinc-300', name: 'Zinc 300', foreground: '#d4d4d8', muted: '#52525b' },
  { id: 'zinc-400', name: 'Zinc 400', foreground: '#a1a1aa', muted: '#3f3f46' },
  { id: 'zinc-500', name: 'Zinc 500', foreground: '#71717a', muted: '#27272a' },
  { id: 'slate-200', name: 'Slate 200', foreground: '#e2e8f0', muted: '#94a3b8' },
  { id: 'slate-300', name: 'Slate 300', foreground: '#cbd5e1', muted: '#64748b' },
  { id: 'slate-400', name: 'Slate 400', foreground: '#94a3b8', muted: '#475569' },
  { id: 'slate-500', name: 'Slate 500', foreground: '#64748b', muted: '#334155' },
  { id: 'stone-200', name: 'Stone 200', foreground: '#e7e5e4', muted: '#a8a29e' },
  { id: 'stone-300', name: 'Stone 300', foreground: '#d6d3d1', muted: '#78716c' },
  { id: 'stone-400', name: 'Stone 400', foreground: '#a8a29e', muted: '#57534e' },
  { id: 'neutral-300', name: 'Neutral 300', foreground: '#d4d4d4', muted: '#737373' },
  { id: 'neutral-400', name: 'Neutral 400', foreground: '#a3a3a3', muted: '#525252' },
  /* Dark */
  { id: 'charcoal-text', name: 'Charcoal', foreground: '#3f3f46', muted: '#71717a' },
  { id: 'graphite-text', name: 'Graphite', foreground: '#44403c', muted: '#57534e' },
  { id: 'smoke-text', name: 'Smoke', foreground: '#52525b', muted: '#3f3f46' },
  { id: 'carbon-text', name: 'Carbon', foreground: '#3f3f46', muted: '#27272a' },
  { id: 'obsidian-text', name: 'Obsidian', foreground: '#27272a', muted: '#18181b' },
  { id: 'ink', name: 'Ink', foreground: '#1f2937', muted: '#374151' },
  { id: 'midnight-text', name: 'Midnight', foreground: '#1e1b4b', muted: '#312e81' },
  { id: 'iron', name: 'Iron', foreground: '#434343', muted: '#5c5c5c' },
  { id: 'lead', name: 'Lead', foreground: '#4a4a4a', muted: '#6b6b6b' },
  { id: 'ash-dark', name: 'Ash Dark', foreground: '#3d3d3d', muted: '#525252' },
  /* Tinted – warm */
  { id: 'warm-gray', name: 'Warm Gray', foreground: '#f5f5f4', muted: '#a8a29e' },
  { id: 'sepia-text', name: 'Sepia', foreground: '#f5f0e6', muted: '#d4c4a8' },
  { id: 'parchment', name: 'Parchment', foreground: '#faf8f5', muted: '#c9b896' },
  { id: 'amber-text', name: 'Amber', foreground: '#fffbeb', muted: '#fde68a' },
  { id: 'saffron-text', name: 'Saffron', foreground: '#fef3c7', muted: '#fcd34d' },
  { id: 'butter', name: 'Butter', foreground: '#fefce8', muted: '#fef08a' },
  { id: 'wheat', name: 'Wheat', foreground: '#faf0dc', muted: '#e8d4a8' },
  { id: 'sand', name: 'Sand', foreground: '#f5e6d3', muted: '#d4b896' },
  { id: 'caramel', name: 'Caramel', foreground: '#f5e6d3', muted: '#c9a86c' },
  { id: 'toast', name: 'Toast', foreground: '#e8dcc8', muted: '#c4b098' },
  { id: 'terracotta-text', name: 'Terracotta', foreground: '#f5e6e0', muted: '#d4a090' },
  { id: 'clay', name: 'Clay', foreground: '#ede0d4', muted: '#c4a090' },
  /* Tinted – cool */
  { id: 'cool-gray', name: 'Cool Gray', foreground: '#f1f5f9', muted: '#94a3b8' },
  { id: 'blue-gray', name: 'Blue Gray', foreground: '#e2e8f0', muted: '#64748b' },
  { id: 'frost', name: 'Frost', foreground: '#ecfeff', muted: '#a5f3fc' },
  { id: 'ice', name: 'Ice', foreground: '#f0f9ff', muted: '#7dd3fc' },
  { id: 'mist', name: 'Mist', foreground: '#f0f4f8', muted: '#94a3b8' },
  { id: 'steel-text', name: 'Steel', foreground: '#e8eef4', muted: '#94a3b8' },
  { id: 'silver-text', name: 'Silver', foreground: '#f4f4f5', muted: '#a1a1aa' },
  /* Tinted – pastels */
  { id: 'blush-text', name: 'Blush', foreground: '#fdf2f8', muted: '#f9a8d4' },
  { id: 'rose-text', name: 'Rose', foreground: '#fff1f2', muted: '#fecdd3' },
  { id: 'pink-text', name: 'Pink', foreground: '#fce7f3', muted: '#fbcfe8' },
  { id: 'lavender-text', name: 'Lavender', foreground: '#f5f3ff', muted: '#c4b5fd' },
  { id: 'lilac', name: 'Lilac', foreground: '#faf5ff', muted: '#e9d5ff' },
  { id: 'violet-text', name: 'Violet', foreground: '#f5f3ff', muted: '#ddd6fe' },
  { id: 'mauve', name: 'Mauve', foreground: '#f5f0ff', muted: '#d4c4f0' },
  { id: 'mint-text', name: 'Mint', foreground: '#f0fdf4', muted: '#86efac' },
  { id: 'sage-text', name: 'Sage', foreground: '#f0fdf4', muted: '#bbf7d0' },
  { id: 'seafoam', name: 'Seafoam', foreground: '#f0fdfa', muted: '#99f6e4' },
  { id: 'aqua-text', name: 'Aqua', foreground: '#ecfeff', muted: '#67e8f9' },
  { id: 'sky-text', name: 'Sky', foreground: '#f0f9ff', muted: '#bae6fd' },
  { id: 'powder-blue', name: 'Powder Blue', foreground: '#eff6ff', muted: '#bfdbfe' },
  { id: 'periwinkle-text', name: 'Periwinkle', foreground: '#eef2ff', muted: '#c7d2fe' },
  /* Stronger tints */
  { id: 'gold-text', name: 'Gold', foreground: '#fef9c3', muted: '#fde047' },
  { id: 'cream-gold', name: 'Cream Gold', foreground: '#fefce8', muted: '#fde68a' },
  { id: 'peach-text', name: 'Peach', foreground: '#fff7ed', muted: '#fed7aa' },
  { id: 'coral-text', name: 'Coral', foreground: '#fff5f5', muted: '#fecaca' },
  { id: 'salmon', name: 'Salmon', foreground: '#fff0f0', muted: '#fecaca' },
  { id: 'melon', name: 'Melon', foreground: '#fff5f0', muted: '#fed7c4' },
  { id: 'lavender-rose-text', name: 'Lavender Rose', foreground: '#fdf4ff', muted: '#f5d0fe' },
  { id: 'thistle', name: 'Thistle', foreground: '#faf5ff', muted: '#e9d5ff' },
  { id: 'eucalyptus', name: 'Eucalyptus', foreground: '#ecfdf5', muted: '#a7f3d0' },
  { id: 'spearmint', name: 'Spearmint', foreground: '#f0fdf4', muted: '#bbf7d0' },
  { id: 'turquoise-text', name: 'Turquoise', foreground: '#ecfeff', muted: '#5eead4' },
  { id: 'arctic', name: 'Arctic', foreground: '#f0f9ff', muted: '#7dd3fc' },
  { id: 'cornflower', name: 'Cornflower', foreground: '#eff6ff', muted: '#93c5fd' },
  { id: 'bluebell', name: 'Bluebell', foreground: '#eef2ff', muted: '#a5b4fc' },
  /* Extra darks */
  { id: 'graphite-dark', name: 'Graphite Dark', foreground: '#292524', muted: '#44403c' },
  { id: 'slate-dark', name: 'Slate Dark', foreground: '#334155', muted: '#475569' },
  { id: 'navy-text', name: 'Navy', foreground: '#1e3a5f', muted: '#2563eb' },
  { id: 'forest-text', name: 'Forest', foreground: '#14532d', muted: '#166534' },
  { id: 'burgundy-text', name: 'Burgundy', foreground: '#4c0519', muted: '#881337' },
  { id: 'plum-dark', name: 'Plum Dark', foreground: '#3b0764', muted: '#6b21a8' },
  /* More lights – bright and clear */
  { id: 'pure-white', name: 'Pure White', foreground: '#ffffff', muted: '#e5e5e5' },
  { id: 'bright-white', name: 'Bright White', foreground: '#fefefe', muted: '#dcdcdc' },
  { id: 'paper', name: 'Paper', foreground: '#fafaf8', muted: '#e0e0dc' },
  { id: 'off-white', name: 'Off White', foreground: '#f8f8f6', muted: '#c8c8c4' },
  { id: 'light-1', name: 'Light 1', foreground: '#f5f5f5', muted: '#b0b0b0' },
  { id: 'light-2', name: 'Light 2', foreground: '#eeeeee', muted: '#9e9e9e' },
  { id: 'light-3', name: 'Light 3', foreground: '#e0e0e0', muted: '#757575' },
  { id: 'pearl-light', name: 'Pearl Light', foreground: '#fcfcfb', muted: '#d8d8d4' },
  { id: 'snow-light', name: 'Snow Light', foreground: '#fafafa', muted: '#cacaca' },
  { id: 'cloud', name: 'Cloud', foreground: '#f2f2f2', muted: '#a8a8a8' },
  /* More darks – deep and saturated */
  { id: 'dark-1', name: 'Dark 1', foreground: '#2d2d2d', muted: '#1a1a1a' },
  { id: 'dark-2', name: 'Dark 2', foreground: '#252525', muted: '#141414' },
  { id: 'dark-3', name: 'Dark 3', foreground: '#1c1c1c', muted: '#0d0d0d' },
  { id: 'dark-charcoal', name: 'Dark Charcoal', foreground: '#2a2a2a', muted: '#181818' },
  { id: 'dark-brown-grey', name: 'Dark Brown Grey', foreground: '#3d3835', muted: '#2a2624' },
  { id: 'dark-indigo', name: 'Dark Indigo', foreground: '#312e81', muted: '#1e1b4b' },
  { id: 'dark-blue', name: 'Dark Blue', foreground: '#1e3a8a', muted: '#172554' },
  { id: 'dark-purple', name: 'Dark Purple', foreground: '#581c87', muted: '#3b0764' },
  { id: 'dark-maroon', name: 'Dark Maroon', foreground: '#7f1d1d', muted: '#450a0a' },
  { id: 'dark-forest', name: 'Dark Forest', foreground: '#14532d', muted: '#052e16' },
  { id: 'dark-teal', name: 'Dark Teal', foreground: '#134e4a', muted: '#042f2e' },
  { id: 'dark-slate', name: 'Dark Slate', foreground: '#1e293b', muted: '#0f172a' },
  { id: 'shadow', name: 'Shadow', foreground: '#374151', muted: '#1f2937' },
  { id: 'onyx', name: 'Onyx', foreground: '#1c1c1e', muted: '#0a0a0b' },
  /* Vibrant – like the reference (neon orange, hot pink, royal blue, bright green) */
  { id: 'neon-orange', name: 'Neon Orange', foreground: '#f97316', muted: '#ea580c' },
  { id: 'neon-orange-light', name: 'Neon Orange Light', foreground: '#fb923c', muted: '#f97316' },
  { id: 'hot-pink', name: 'Hot Pink', foreground: '#ec4899', muted: '#db2777' },
  { id: 'hot-pink-light', name: 'Hot Pink Light', foreground: '#f472b6', muted: '#ec4899' },
  { id: 'royal-blue', name: 'Royal Blue', foreground: '#2563eb', muted: '#1d4ed8' },
  { id: 'royal-blue-light', name: 'Royal Blue Light', foreground: '#3b82f6', muted: '#2563eb' },
  { id: 'bright-green', name: 'Bright Green', foreground: '#22c55e', muted: '#16a34a' },
  { id: 'bright-green-light', name: 'Bright Green Light', foreground: '#4ade80', muted: '#22c55e' },
  { id: 'bright-yellow', name: 'Bright Yellow', foreground: '#eab308', muted: '#ca8a04' },
  { id: 'bright-yellow-light', name: 'Bright Yellow Light', foreground: '#facc15', muted: '#eab308' },
  { id: 'burnt-orange', name: 'Burnt Orange', foreground: '#c2410c', muted: '#9a3412' },
  { id: 'deep-red', name: 'Deep Red', foreground: '#b91c1c', muted: '#991b1b' },
  { id: 'vibrant-cyan', name: 'Vibrant Cyan', foreground: '#06b6d4', muted: '#0891b2' },
  { id: 'vibrant-purple', name: 'Vibrant Purple', foreground: '#a855f7', muted: '#9333ea' },
  { id: 'vibrant-rose', name: 'Vibrant Rose', foreground: '#f43f5e', muted: '#e11d48' },
  { id: 'electric-blue', name: 'Electric Blue', foreground: '#0ea5e9', muted: '#0284c7' },
  /* Pastel lights (like second ref – soft but distinct) */
  { id: 'pastel-orange', name: 'Pastel Orange', foreground: '#ffedd5', muted: '#fed7aa' },
  { id: 'pastel-yellow', name: 'Pastel Yellow', foreground: '#fef9c3', muted: '#fde047' },
  { id: 'pastel-pink-light', name: 'Pastel Pink', foreground: '#fce7f3', muted: '#f9a8d4' },
  { id: 'pastel-blue-light', name: 'Pastel Blue', foreground: '#dbeafe', muted: '#93c5fd' },
  { id: 'pastel-green-light', name: 'Pastel Green', foreground: '#dcfce7', muted: '#86efac' },
  { id: 'pastel-lavender', name: 'Pastel Lavender', foreground: '#ede9fe', muted: '#c4b5fd' },
  { id: 'pastel-mint', name: 'Pastel Mint', foreground: '#d1fae5', muted: '#6ee7b7' },
  { id: 'pastel-sky', name: 'Pastel Sky', foreground: '#e0f2fe', muted: '#7dd3fc' },
  { id: 'pastel-peach', name: 'Pastel Peach', foreground: '#fff7ed', muted: '#ffd6a5' },
  { id: 'pastel-rose', name: 'Pastel Rose', foreground: '#ffe4e6', muted: '#fda4af' },
  /* Mid greys – stepped light to dark */
  { id: 'grey-150', name: 'Grey 150', foreground: '#f1f1f1', muted: '#bdbdbd' },
  { id: 'grey-250', name: 'Grey 250', foreground: '#e0e0e0', muted: '#9e9e9e' },
  { id: 'grey-350', name: 'Grey 350', foreground: '#bdbdbd', muted: '#757575' },
  { id: 'grey-450', name: 'Grey 450', foreground: '#9e9e9e', muted: '#616161' },
  { id: 'grey-550', name: 'Grey 550', foreground: '#757575', muted: '#424242' },
  { id: 'grey-650', name: 'Grey 650', foreground: '#616161', muted: '#303030' },
  { id: 'grey-750', name: 'Grey 750', foreground: '#424242', muted: '#212121' },
  { id: 'grey-850', name: 'Grey 850', foreground: '#303030', muted: '#121212' },
  /* Extra deep darks */
  { id: 'ink-deep', name: 'Ink Deep', foreground: '#0f172a', muted: '#1e293b' },
  { id: 'pitch-text', name: 'Pitch', foreground: '#18181b', muted: '#27272a' },
  { id: 'obsidian-deep', name: 'Obsidian Deep', foreground: '#09090b', muted: '#18181b' },
  { id: 'midnight-ink', name: 'Midnight Ink', foreground: '#0c1929', muted: '#1e3a5f' },
  { id: 'forest-ink', name: 'Forest Ink', foreground: '#052e16', muted: '#14532d' },
  { id: 'wine-ink', name: 'Wine Ink', foreground: '#450a0a', muted: '#7f1d1d' },
  { id: 'plum-ink', name: 'Plum Ink', foreground: '#3b0764', muted: '#581c87' },
  { id: 'slate-ink', name: 'Slate Ink', foreground: '#0f172a', muted: '#334155' },
  { id: 'teal-ink', name: 'Teal Ink', foreground: '#042f2e', muted: '#134e4a' },
  { id: 'carbon-deep', name: 'Carbon Deep', foreground: '#27272a', muted: '#3f3f46' },
  /* Extra deep lights */
  { id: 'silk-text', name: 'Silk', foreground: '#fefefe', muted: '#e8e8e8' },
  { id: 'snow-deep', name: 'Snow Deep', foreground: '#fffefe', muted: '#f0f0f0' },
  { id: 'linen-text', name: 'Linen', foreground: '#fdf8f3', muted: '#f0e6dc' },
  { id: 'pearl-deep', name: 'Pearl Deep', foreground: '#fcfcfb', muted: '#e8e8e6' },
  { id: 'ivory-deep', name: 'Ivory Deep', foreground: '#fffff0', muted: '#f5f5e6' },
  { id: 'cream-deep', name: 'Cream Deep', foreground: '#fffef5', muted: '#f5f0e8' },
  { id: 'frost-text', name: 'Frost', foreground: '#f0faff', muted: '#bae6fd' },
  { id: 'blush-light', name: 'Blush Light', foreground: '#fff5f8', muted: '#fce7ef' },
  { id: 'mint-light', name: 'Mint Light', foreground: '#f0fff8', muted: '#a7f3d0' },
  /* Extra mid */
  { id: 'storm-text', name: 'Storm', foreground: '#4b5563', muted: '#6b7280' },
  { id: 'fog-text', name: 'Fog', foreground: '#9ca3af', muted: '#d1d5db' },
  { id: 'dove-text', name: 'Dove', foreground: '#e5e7eb', muted: '#9ca3af' },
  { id: 'flint-text', name: 'Flint', foreground: '#57534e', muted: '#78716c' },
  { id: 'battleship-text', name: 'Battleship', foreground: '#64748b', muted: '#94a3b8' },
  { id: 'mink-text', name: 'Mink', foreground: '#78716c', muted: '#a8a29e' },
  { id: 'taupe-text', name: 'Taupe', foreground: '#8b7355', muted: '#a88b6a' },
  { id: 'dust-text', name: 'Dust', foreground: '#a8a29e', muted: '#d6d3d1' },
];

/** Display order: sections for writing (text) colours. */
export const THEME_WRITING_SECTIONS = [
  { label: 'Default & light', ids: ['default', 'snow', 'pearl', 'ivory-text', 'cream-text', 'warm-white', 'cool-white', 'bone', 'eggshell', 'linen', 'vanilla', 'honeydew', 'azure', 'alabaster', 'chalk', 'milk', 'silk-text', 'snow-deep', 'linen-text', 'pearl-deep', 'ivory-deep', 'cream-deep', 'frost-text', 'blush-light', 'mint-light'] },
  { label: 'Grays', ids: ['gray-50', 'gray-100', 'gray-200', 'gray-300', 'gray-400', 'gray-500', 'zinc-100', 'zinc-200', 'zinc-300', 'zinc-400', 'zinc-500', 'slate-200', 'slate-300', 'slate-400', 'slate-500', 'stone-200', 'stone-300', 'stone-400', 'neutral-300', 'neutral-400', 'storm-text', 'fog-text', 'dove-text', 'flint-text', 'battleship-text', 'mink-text', 'taupe-text', 'dust-text'] },
  { label: 'Dark', ids: ['charcoal-text', 'graphite-text', 'smoke-text', 'carbon-text', 'obsidian-text', 'ink', 'midnight-text', 'iron', 'lead', 'ash-dark', 'graphite-dark', 'slate-dark', 'navy-text', 'forest-text', 'burgundy-text', 'plum-dark', 'dark-1', 'dark-2', 'dark-3', 'dark-charcoal', 'dark-brown-grey', 'dark-indigo', 'dark-blue', 'dark-purple', 'dark-maroon', 'dark-forest', 'dark-teal', 'dark-slate', 'shadow', 'onyx', 'ink-deep', 'pitch-text', 'obsidian-deep', 'midnight-ink', 'forest-ink', 'wine-ink', 'plum-ink', 'slate-ink', 'teal-ink', 'carbon-deep'] },
  { label: 'Tinted – warm', ids: ['warm-gray', 'sepia-text', 'parchment', 'amber-text', 'saffron-text', 'butter', 'wheat', 'sand', 'caramel', 'toast', 'terracotta-text', 'clay'] },
  { label: 'Tinted – cool', ids: ['cool-gray', 'blue-gray', 'frost', 'ice', 'mist', 'steel-text', 'silver-text'] },
  { label: 'Tinted – pastels', ids: ['blush-text', 'rose-text', 'pink-text', 'lavender-text', 'lilac', 'violet-text', 'mauve', 'mint-text', 'sage-text', 'seafoam', 'aqua-text', 'sky-text', 'powder-blue', 'periwinkle-text'] },
  { label: 'Stronger tints', ids: ['gold-text', 'cream-gold', 'peach-text', 'coral-text', 'salmon', 'melon', 'lavender-rose-text', 'thistle', 'eucalyptus', 'spearmint', 'turquoise-text', 'arctic', 'cornflower', 'bluebell'] },
  { label: 'More lights', ids: ['pure-white', 'bright-white', 'paper', 'off-white', 'light-1', 'light-2', 'light-3', 'pearl-light', 'snow-light', 'cloud'] },
  { label: 'Vibrant', ids: ['neon-orange', 'neon-orange-light', 'hot-pink', 'hot-pink-light', 'royal-blue', 'royal-blue-light', 'bright-green', 'bright-green-light', 'bright-yellow', 'bright-yellow-light', 'burnt-orange', 'deep-red', 'vibrant-cyan', 'vibrant-purple', 'vibrant-rose', 'electric-blue'] },
  { label: 'Pastel lights', ids: ['pastel-orange', 'pastel-yellow', 'pastel-pink-light', 'pastel-blue-light', 'pastel-green-light', 'pastel-lavender', 'pastel-mint', 'pastel-sky', 'pastel-peach', 'pastel-rose'] },
  { label: 'Mid greys', ids: ['grey-150', 'grey-250', 'grey-350', 'grey-450', 'grey-550', 'grey-650', 'grey-750', 'grey-850'] },
];

export const DEFAULT_COLOUR_ID = 'gold';
export const DEFAULT_WRITING_COLOUR_ID = 'default';
export const DEFAULT_TEXT_STYLE_ID = 'normal';
export const DEFAULT_FONT_ID = 'classic';
export const DEFAULT_BUTTON_STYLE_ID = 'original';
export const DEFAULT_TEXTURE_ID = 'none';

/**
 * Full presets: one-click theme bundles (colour + texture + optional button/accent/writing/buttonStyle).
 * buttonColourId / accentLineColourId: null = use main colour.
 * Optional: writingColourId, mutedWritingColourId, buttonStyleId, fontId, textStyleId, toastTextColourId for full presets.
 */
export const THEME_PRESETS = [
  { id: 'original', name: 'Original theme', description: 'Default look before custom themes', colourId: 'gold', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'default', name: 'Classic Mafia', description: 'Gold, no texture', colourId: 'gold', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'dark-mode', name: 'Dark Mode', description: 'Slate accents, clean', colourId: 'matte-slate', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'telegram', name: 'Telegram', description: 'Teal / sky blue', colourId: 'sky', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'facebook', name: 'Facebook', description: 'Blue accent', colourId: 'blue', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'glossy-gold', name: 'Glossy Gold', description: 'Rich gold', colourId: 'glossy-gold', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'glossy-teal', name: 'Glossy Teal', description: 'Shiny teal', colourId: 'glossy-teal', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'matte', name: 'Matte', description: 'Muted, flat look', colourId: 'matte-sage', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'midnight', name: 'Midnight', description: 'Deep blue / indigo', colourId: 'midnight', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'ocean', name: 'Ocean', description: 'Blue → teal gradient', colourId: 'tone-2-ocean', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'forest', name: 'Forest', description: 'Green tones', colourId: 'tone-2-forest', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'rose-gold', name: 'Rose Gold', description: 'Warm rose gold', colourId: 'rose-gold', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'ember', name: 'Ember', description: 'Dark red / orange', colourId: 'tone-4-ember', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'lavender-dream', name: 'Lavender Dream', description: 'Soft purple gradient', colourId: 'tone-3-lavender', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'noir-matte', name: 'Noir Matte', description: 'Charcoal, minimal', colourId: 'charcoal', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'vintage-paper', name: 'Vintage Paper', description: 'Sepia', colourId: 'sepia', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'carbon-pro', name: 'Carbon Pro', description: 'Dark carbon', colourId: 'carbon', textureId: 'none', buttonColourId: null, accentLineColourId: null },

  /* Mafia vibes */
  { id: 'old-school-mafia', name: 'Old School Mafia', description: '1920s gold', colourId: 'gold', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'old-school-mafia-noir', name: 'Old School Mafia Noir', description: 'Film noir, charcoal + gold', colourId: 'charcoal', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'modern-mafia', name: 'Modern Mafia', description: 'Clean slate blue', colourId: 'matte-slate', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'speakeasy', name: 'Speakeasy', description: 'Warm bronze', colourId: 'bronze', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'godfather', name: 'The Godfather', description: 'Deep amber', colourId: 'antique-brass', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'street-boss', name: 'Street Boss', description: 'Gunmetal + gold accent', colourId: 'gunmetal', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'sicilian', name: 'Sicilian', description: 'Terracotta warmth', colourId: 'terracotta', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'boardroom', name: 'Boardroom', description: 'Navy, minimal', colourId: 'navy', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'noir-gold', name: 'Noir Gold', description: 'Black & gold classic', colourId: 'gold', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'vintage-noir', name: 'Vintage Noir', description: 'Sepia noir', colourId: 'sepia', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'concrete-boss', name: 'Concrete Boss', description: 'Steel', colourId: 'steel', textureId: 'none', buttonColourId: null, accentLineColourId: null },
  { id: 'blood-money', name: 'Blood & Money', description: 'Wine red, dark', colourId: 'wine', textureId: 'none', buttonColourId: null, accentLineColourId: null },

  /* Full multicolored presets (accent + writing + buttons coordinated) */
  { id: 'neon-pink-full', name: 'Neon Pink', description: 'Pink accent, blush text, glossy', colourId: 'neon-pink', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'blush-text', mutedWritingColourId: 'hot-pink-light', buttonStyleId: 'glossy', toastTextColourId: 'blush-text', isFullPreset: true },
  { id: 'ocean-full', name: 'Ocean Blue', description: 'Teal accent, sky text, glossy', colourId: 'teal', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'sky-text', mutedWritingColourId: 'aqua-text', buttonStyleId: 'glossy', toastTextColourId: 'sky-text', isFullPreset: true },
  { id: 'forest-full', name: 'Forest Green', description: 'Green accent, mint text, flat', colourId: 'emerald', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'mint-text', mutedWritingColourId: 'sage-text', buttonStyleId: 'flat', toastTextColourId: 'mint-text', isFullPreset: true },
  { id: 'sunset-full', name: 'Sunset', description: 'Orange accent, peach text, shaded', colourId: 'sunset', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'peach-text', mutedWritingColourId: 'melon', buttonStyleId: 'shaded', toastTextColourId: 'peach-text', isFullPreset: true },
  { id: 'lavender-full', name: 'Lavender Dream', description: 'Purple accent, lavender text, glossy', colourId: 'lavender', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'lavender-text', mutedWritingColourId: 'lilac', buttonStyleId: 'glossy', toastTextColourId: 'lavender-text', isFullPreset: true },
  { id: 'gold-classic-full', name: 'Gold Classic', description: 'Gold accent, cream-gold text, raised', colourId: 'gold', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'cream-gold', mutedWritingColourId: 'warm-white', buttonStyleId: 'raised', toastTextColourId: 'cream-gold', isFullPreset: true },
  { id: 'coral-full', name: 'Coral', description: 'Coral accent, peach text, glossy', colourId: 'coral', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'coral-text', mutedWritingColourId: 'salmon', buttonStyleId: 'glossy', toastTextColourId: 'coral-text', isFullPreset: true },
  { id: 'electric-blue-full', name: 'Electric Blue', description: 'Blue accent, cool white text, glossy', colourId: 'electric', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'cool-white', mutedWritingColourId: 'powder-blue', buttonStyleId: 'glossy', toastTextColourId: 'cool-white', isFullPreset: true },
  { id: 'neon-green-full', name: 'Neon Green', description: 'Green accent, mint text, flat', colourId: 'neon-green', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'eucalyptus', mutedWritingColourId: 'spearmint', buttonStyleId: 'flat', toastTextColourId: 'eucalyptus', isFullPreset: true },
  { id: 'royal-purple-full', name: 'Royal Purple', description: 'Violet accent, periwinkle text, shadow', colourId: 'violet', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'periwinkle-text', mutedWritingColourId: 'lavender-text', buttonStyleId: 'shadow', toastTextColourId: 'periwinkle-text', isFullPreset: true },
  { id: 'blood-red-full', name: 'Blood Red', description: 'Deep red accent, warm text, shaded', colourId: 'blood', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'burgundy-text', mutedWritingColourId: null, buttonStyleId: 'shaded', toastTextColourId: 'burgundy-text', isFullPreset: true },
  { id: 'cyan-full', name: 'Cyan', description: 'Cyan accent, seafoam text, glossy', colourId: 'cyan', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'seafoam', mutedWritingColourId: 'aqua-text', buttonStyleId: 'glossy', toastTextColourId: 'seafoam', isFullPreset: true },

  /* Additional full presets (~15 more) */
  { id: 'amber-glow-full', name: 'Amber Glow', description: 'Amber accent, cream-gold text, raised', colourId: 'amber', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'cream-gold', mutedWritingColourId: 'warm-white', buttonStyleId: 'raised', toastTextColourId: 'cream-gold', isFullPreset: true },
  { id: 'rose-gold-full', name: 'Rose Gold', description: 'Rose gold accent, blush text, glossy', colourId: 'rose-gold', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'blush-text', mutedWritingColourId: 'coral-text', buttonStyleId: 'glossy', toastTextColourId: 'blush-text', isFullPreset: true },
  { id: 'midnight-blue-full', name: 'Midnight Blue', description: 'Deep indigo accent, cool white text, shadow', colourId: 'midnight', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'cool-white', mutedWritingColourId: 'powder-blue', buttonStyleId: 'shadow', toastTextColourId: 'cool-white', isFullPreset: true },
  { id: 'jade-garden-full', name: 'Jade Garden', description: 'Jade accent, mint text, flat', colourId: 'jade', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'mint-text', mutedWritingColourId: 'sage-text', buttonStyleId: 'flat', toastTextColourId: 'mint-text', isFullPreset: true },
  { id: 'honeycomb-full', name: 'Honeycomb', description: 'Honey accent, vanilla text, shaded', colourId: 'honey', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'vanilla', mutedWritingColourId: 'cream-gold', buttonStyleId: 'shaded', toastTextColourId: 'vanilla', isFullPreset: true },
  { id: 'peach-smoothie-full', name: 'Peach Smoothie', description: 'Peach accent, peach text, glossy', colourId: 'peach', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'peach-text', mutedWritingColourId: 'melon', buttonStyleId: 'glossy', toastTextColourId: 'peach-text', isFullPreset: true },
  { id: 'indigo-night-full', name: 'Indigo Night', description: 'Indigo accent, periwinkle text, shadow', colourId: 'indigo', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'periwinkle-text', mutedWritingColourId: 'lavender-text', buttonStyleId: 'shadow', toastTextColourId: 'periwinkle-text', isFullPreset: true },
  { id: 'saffron-full', name: 'Saffron', description: 'Saffron accent, cream-gold text, opaque', colourId: 'saffron', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'cream-gold', mutedWritingColourId: 'warm-white', buttonStyleId: 'opaque', toastTextColourId: 'cream-gold', isFullPreset: true },
  { id: 'pastel-pink-full', name: 'Pastel Pink', description: 'Pastel pink accent, blush text, glossy', colourId: 'pastel-pink', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'blush-text', mutedWritingColourId: 'lavender-rose-text', buttonStyleId: 'glossy', toastTextColourId: 'blush-text', isFullPreset: true },
  { id: 'deep-ocean-full', name: 'Deep Ocean', description: 'Navy accent, sky text, flat', colourId: 'navy', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'sky-text', mutedWritingColourId: 'powder-blue', buttonStyleId: 'flat', toastTextColourId: 'sky-text', isFullPreset: true },
  { id: 'dusty-rose-full', name: 'Dusty Rose', description: 'Dusty rose accent, coral text, shaded', colourId: 'dusty-rose', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'coral-text', mutedWritingColourId: 'blush-text', buttonStyleId: 'shaded', toastTextColourId: 'coral-text', isFullPreset: true },
  { id: 'sea-green-full', name: 'Sea Green', description: 'Sea green accent, seafoam text, glossy', colourId: 'sea-green', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'seafoam', mutedWritingColourId: 'aqua-text', buttonStyleId: 'glossy', toastTextColourId: 'seafoam', isFullPreset: true },
  { id: 'twilight-full', name: 'Twilight', description: 'Twilight purple accent, lavender text, shadow', colourId: 'twilight', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'lavender-text', mutedWritingColourId: 'lilac', buttonStyleId: 'shadow', toastTextColourId: 'lavender-text', isFullPreset: true },
  { id: 'amber-copper-full', name: 'Amber Copper', description: 'Amber copper accent, peach text, raised', colourId: 'amber-copper', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'peach-text', mutedWritingColourId: 'melon', buttonStyleId: 'raised', toastTextColourId: 'peach-text', isFullPreset: true },
  { id: 'muted-teal-full', name: 'Muted Teal', description: 'Muted teal accent, aqua text, flat', colourId: 'muted-teal', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'aqua-text', mutedWritingColourId: 'seafoam', buttonStyleId: 'flat', toastTextColourId: 'aqua-text', isFullPreset: true },
  { id: 'pastel-mint-full', name: 'Pastel Mint', description: 'Pastel green accent, mint text, glossy', colourId: 'pastel-green', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'mint-text', mutedWritingColourId: 'eucalyptus', buttonStyleId: 'glossy', toastTextColourId: 'mint-text', isFullPreset: true },
  { id: 'rust-full', name: 'Rust', description: 'Rust accent, peach text, shaded', colourId: 'rust', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'peach-text', mutedWritingColourId: 'coral-text', buttonStyleId: 'shaded', toastTextColourId: 'peach-text', isFullPreset: true },
  { id: 'royal-blue-full', name: 'Royal Blue', description: 'Royal blue accent, periwinkle text, shadow', colourId: 'royal', textureId: 'none', buttonColourId: null, accentLineColourId: null, writingColourId: 'periwinkle-text', mutedWritingColourId: 'powder-blue', buttonStyleId: 'shadow', toastTextColourId: 'periwinkle-text', isFullPreset: true },
];

export function getThemeColour(id) {
  return THEME_COLOURS.find((c) => c.id === id) || THEME_COLOURS[0];
}

export function getThemeTexture(id) {
  return THEME_TEXTURES.find((t) => t.id === id) || THEME_TEXTURES[0];
}

export function getThemePreset(id) {
  return THEME_PRESETS.find((p) => p.id === id) || THEME_PRESETS[0];
}

export function getThemeFont(id) {
  return THEME_FONTS.find((f) => f.id === id) || THEME_FONTS[0];
}

export function getThemeButtonStyle(id) {
  return THEME_BUTTON_STYLES.find((b) => b.id === id) || THEME_BUTTON_STYLES[0];
}

export function getThemeWritingColour(id) {
  return THEME_WRITING_COLOURS.find((w) => w.id === id) || THEME_WRITING_COLOURS[0];
}

export function getThemeTextStyle(id) {
  return THEME_TEXT_STYLES.find((t) => t.id === id) || THEME_TEXT_STYLES[0];
}
