# Disposable / throwaway email domain blocklist for registration.
# Domains are lowercase; add more as needed. See disposable-email-domains on GitHub for a full list.

DISPOSABLE_DOMAINS = frozenset({
    "0-mail.com", "10minutemail.com", "10minutemail.net", "10minutemail.org",
    "10minutemails.in", "123-m.com", "126.com", "139.com", "150ml.com",
    "163.com", "1chuan.com", "1pad.de", "1secmail.com", "1secmail.net",
    "1secmail.org", "1secmail.space", "1secmail.website", "1tk.eu",
    "20mail.eu", "20mail.it", "20minutemail.com", "21cn.com",
    "24hourmail.com", "24hourmail.net", "2fdgdfgdfgdf.tk", "2prong.com",
    "30minutemail.com", "33mail.com", "3d-painting.com", "3mail.ga",
    "4warding.com", "4warding.net", "4warding.org", "60minutemail.com",
    "675hosting.com", "675hosting.net", "675hosting.org", "6url.com",
    "75hosting.com", "75hosting.net", "75hosting.org", "7tags.com",
    "9ox.net", "a-bc.net", "agedmail.com", "ajaxapp.net", "amilegit.com",
    "anonbox.net", "anonmails.de", "anonymbox.com", "antichef.com",
    "antichef.net", "antispam.de", "baxomale.ht.cx", "beefmilk.com",
    "binkmail.com", "binnary.com", "bio-muesli.info", "bobmail.info",
    "bodhi.lawl.io", "bofthew.com", "bootybay.de", "boun.cr", "bouncr.com",
    "boxformail.in", "boximail.com", "boxtemp.com.br", "breadtimes.press",
    "brennendesreich.de", "broadbandninja.com", "bsnow.net", "bspamfree.org",
    "buffemail.com", "bugmenever.com", "bugmenot.com", "bumpymail.com",
    "bund.us", "bundes-li.ga", "bunsenhoneydew.com", "burnthespam.info",
    "burstmail.info", "buspad.org", "byom.de", "c2.hu", "c51vsgq.com",
    "cachedot.net", "cartelera.org", "casualdx.com", "cellurl.com",
    "centermail.com", "centermail.net", "chammy.info", "cheatmail.de",
    "chielo.com", "childsavetrust.org", "chogmail.com", "choicemail1.com",
    "chong-mail.com", "chong-mail.net", "chong-mail.org", "chumpstakingdumps.com",
    "cndps.com", "co.cc", "cobarekyo1.ml", "coldemail.info", "consumerriot.com",
    "coolandwacky.us", "correo.blogos.net", "cosmorph.com", "courriel.fr.nf",
    "courrieltemporaire.com", "crapmail.org", "crazymailing.com", "csh.ro",
    "cu.cc", "cubiclink.com", "curryworld.de", "cust.in", "cuvox.de",
    "d3p.dk", "daabox.com", "dab.ro", "dacoolest.com", "dandikmail.com",
    "darkharvestfilms.com", "dataarca.com", "datenschutz.ru", "datum2.com",
    "daymail.life", "daymailonline.com", "dayrep.com", "dbunker.com",
    "dcemail.com", "deadaddress.com", "deadfake.cf", "deadfake.ga",
    "deadfake.ml", "deadfake.tk", "deadspam.com", "deagot.com", "delikkt.de",
    "delivrmail.com", "despam.it", "despammed.com", "dev-null.cf",
    "dev-null.ga", "dev-null.gq", "dev-null.ml", "devnullmail.com",
    "dfgggg.org", "digdig.org", "digital-message.com", "digitalmail.info",
    "digitech.pt", "dingbone.com", "disbox.net", "disbox.org",
    "discard.cf", "discard.email", "discard.ga", "discard.gq", "discard.ml",
    "discard.tk", "discardmail.com", "discardmail.de", "disposable.cf",
    "disposable.ga", "disposable.ml", "disposable.site", "disposableaddress.com",
    "disposableemailaddresses.com", "disposableinbox.com", "disposablemails.com",
    "dispose.it", "disposeamail.com", "disposely.xyz", "disposemail.com",
    "disposemymail.com", "disposly.com", "dispostable.com", "divermail.com",
    "divismail.ru", "dlemail.ru", "dmarc.ro", "dmts.fr.nf", "dndent.com",
    "dnsclick.com", "dob.jp", "dodgeit.com", "dodgemail.de", "dodgit.com",
    "dodgit.org", "doiea.com", "domozmail.com", "donemail.ru", "dontreg.com",
    "dontsendmespam.de", "doobee.net", "doquier.tk", "dotman.de", "dotmsg.com",
    "dotslashrage.com", "doublemail.de", "doubtful.com", "dozvon-spb.ru",
    "dr69.site", "drdrb.com", "drdrb.net", "dreamclarify.org", "dred.ru",
    "drewzen.com", "dropcake.de", "dropinboxes.com", "dropjar.com",
    "droplar.com", "dropmail.me", "dropsin.net", "dspwebservices.com",
    "duam.net", "dudmail.com", "dumpandjunk.com", "dumpmail.de",
    "dumpyemail.com", "duskmail.com", "e-mail.com", "e-mail.org",
    "e4ward.com", "easy-trash-mail.com", "easytrashmail.com", "ee2.pl",
    "einrot.com", "einrot.de", "eintagsmail.de", "email-fake.cf",
    "email-fake.com", "email-fake.ga", "email-fake.gq", "email-fake.ml",
    "email-fake.tk", "email-temp.com", "email60.com", "emailage.cf",
    "emailage.ga", "emailage.gq", "emailage.ml", "emailage.tk",
    "emailfake.com", "emailfake.ml", "emailgo.de", "emailondeck.com",
    "emailspam.cf", "emailspam.ga", "emailspam.gq", "emailspam.ml",
    "emailspam.tk", "emailtemporar.ro", "emailtemporario.com.br",
    "emailtmp.com", "emailto.de", "emailwarden.com", "emkei.cf",
    "emkei.ga", "emkei.gq", "emkei.ml", "emkei.tk", "emltmp.com",
    "emz.net", "enterto.com", "ephemail.net", "ephemeral.email",
    "ero-tube.org", "esbano-ru.ru", "escapehatchapp.com", "esemay.com",
    "esgeneri.com", "etgdev.de", "eth2btc.info", "etgdev.de",
    "evopo.com", "evyush.com", "explodemail.com", "express.net.ua",
    "eyepaste.com", "ez.lv", "ezfill.com", "ezstest.com", "f4k.es",
    "facebook-email.cf", "facebook-email.ga", "facebook-email.ml",
    "fake-box.com", "fake-email.pp.ua", "fake-mail.cf", "fake-mail.ga",
    "fake-mail.ml", "fakedemail.com", "fakeinbox.cf", "fakeinbox.com",
    "fakeinbox.ga", "fakeinbox.info", "fakeinbox.ml", "fakeinbox.tk",
    "fakeinformation.com", "fakemail.fr", "fakemail.io", "fakemail.net",
    "fakemailgenerator.com", "fakemailz.com", "fammix.com", "fansworldwide.de",
    "fantasymail.de", "fastacura.com", "fastchevy.com", "fastchrysler.com",
    "fastkawasaki.com", "fastmazda.com", "fastmitsubishi.com", "fastnissan.com",
    "fastsearcher.com", "fastsubaru.com", "fastsuzuki.com", "fasttoyota.com",
    "fastyamaha.com", "fddns.ml", "fdfdsfds.com", "fer-max.net",
    "fettometern.com", "fexbox.org", "fexbox.ru", "fexpost.com",
    "ficken.de", "fightallspam.com", "figshot.com", "filzmail.com",
    "fivemail.de", "fivermail.com", "fixmail.tk", "fizmail.com",
    "flashbox.5july.org", "flashmail.xyz", "fleckens.hu", "flemail.ru",
    "flurred.com", "flyspam.com", "flyzy.net", "forgetmail.com",
    "fornow.eu", "forspam.net", "forward.cat", "fosil.pro",
    "foxja.com", "fr33mail.info", "frapmail.com", "free-email.cf",
    "free-email.ga", "free-temp.net", "freebabysittercam.com",
    "freeblackbootytube.com", "freecat.net", "freedom4you.info",
    "freedrops.org", "freefattymovies.com", "freehotmail.net",
    "freeinbox.email", "freelance-france.eu", "freemails.cf",
    "freemails.ga", "freemails.ml", "freemeil.ga", "freemeil.gq",
    "freemeil.ml", "freeml.net", "freepost.cc", "freerubli.ru",
    "freeschoolgirlvids.com", "freesistercam.com", "freeteenbums.com",
    "freundin.ru", "friendlymail.co.uk", "front14.org", "fuckingduh.com",
    "fuckme69.club", "fucknloveme.top", "fuckxxme.top", "fudgerub.com",
    "fuirio.com", "fukaru.com", "funker.de", "funnymail.de",
    "furusato.tokyo", "fuvk.ru", "fuvk.store", "fynix.sbs",
    "g2xmail.top", "g3xmail.top", "g4hdrop.us", "gafy.net",
    "gamail.top", "gamebcs.com", "garbagemail.org", "gawab.com",
    "gbcmail.win", "gbmail.top", "gcmail.top", "gdmail.top",
    "gedmail.win", "gelitik.in", "genzmaile.com", "genzotp.com",
    "get-mail.cf", "get-mail.ga", "get-mail.ml", "get-mail.tk",
    "get1mail.com", "get2mail.fr", "getairmail.cf", "getairmail.com",
    "getairmail.ga", "getairmail.gq", "getairmail.ml", "getairmail.tk",
    "geteit.com", "getfun.men", "getmail1.com", "getmails.eu",
    "getnada.cc", "getnada.com", "getonemail.com", "getonemail.net",
    "getsimpleemail.com", "gett.icu", "ghosttexter.de", "giantmail.de",
    "ginzi.be", "ginzi.co.uk", "ginzi.es", "ginzi.net",
    "ginzy.co.uk", "ginzy.eu", "girlmail.win", "gishpuppy.com",
    "givememail.club", "givmail.com", "glubex.com", "gmial.com",
    "gmx1mail.top", "gmxmail.top", "gmxmail.win", "go2usa.info",
    "go2vpn.net", "goatmail.uk", "godfare.com", "goemailgo.com",
    "golemico.com", "gomail.in", "goonby.com", "gorillaswithdirtyarmpits.com",
    "goround.info", "gotmail.com", "gotmail.net", "gotmail.org",
    "grandmamail.com", "grandmasmail.com", "great-host.in",
    "greenhousemail.com", "greensloth.com", "grr.la", "gsrv.co.uk",
    "guerillamail.biz", "guerillamail.com", "guerillamail.de",
    "guerillamail.info", "guerillamail.net", "guerillamail.org",
    "guerillamailblock.com", "guerrillamail.biz", "guerrillamail.com",
    "guerrillamail.de", "guerrillamail.info", "guerrillamail.net",
    "guerrillamail.org", "guerrillamailblock.com", "gustr.com",
    "guysmail.com", "gynzi.co.uk", "gynzi.es", "gzb.ro",
    "h8s.org", "haben-wir.com", "habenwir.com", "hacccc.com",
    "hackersquad.tk", "hahawrong.com", "haltospam.com", "hamham.uk",
    "harakirimail.com", "haribu.com", "hartbot.de", "hasanmail.ml",
    "hat-geld.de", "hatespam.org", "hawrong.com", "haydoo.com",
    "hazmatshipping.org", "hccmail.win", "headstrong.de", "heathenhammer.com",
    "heathenhero.com", "hecat.es", "heheee.com", "hellodream.mobi",
    "herp.in", "herpderp.nl", "hezll.com", "hidemail.de",
    "hidemail.pro", "hidemail.us", "hidzz.com", "hidmail.org",
    "highbros.org", "hihi.lol", "hmamail.com", "hoanggiaanh.com",
    "hoanglong.tech", "hopemail.biz", "hornyalwary.top", "hostcalls.com",
    "hostlaba.com", "hot-mail.cf", "hot-mail.ga", "hot-mail.gq",
    "hot-mail.ml", "hot-mail.tk", "hotmai.com", "hotmial.com",
    "hotpop.com", "housat.com", "hpc.tw", "hs.vc", "ht.cx",
    "huangniu8.com", "hudisk.com", "huongdanfb.com", "hushmail.cf",
    "hvastudiesucces.nl", "hwsye.net", "i2pmail.org", "iaoss.com",
    "icantbelieveineedtoexplainthisshit.com", "icemail.club",
    "ichigo.me", "icx.ro", "idf.ovh", "idx4.com", "ieatspam.eu",
    "ieatspam.info", "ieh-mail.de", "iencm.com", "iffymedia.com",
    "ignoremail.com", "ihateyoualot.info", "ihazspam.ca",
    "iheartspam.org", "ikbenspamvrij.nl", "illistnoise.com",
    "ilovespam.com", "imail1.net", "imails.info", "imailt.com",
    "imgof.com", "imgv.de", "imstations.com", "in-ulm.de",
    "inbax.tk", "inbox.si", "inbox2.info", "inboxalias.com",
    "inboxbear.com", "inboxclean.com", "inboxclean.org",
    "inboxed.im", "inboxed.pw", "inboxkitten.com", "inboxnow.ru",
    "inboxnow.store", "inboxproxy.com", "inboxstore.me", "inclusiveprogress.com",
    "incognitomail.com", "incognitomail.net", "incognitomail.org",
    "incq.com", "ind.st", "indieclad.com", "indirect.ws",
    "indomaed.pw", "indomina.cf", "indoserver.stream", "ineec.net",
    "infocom.zp.ua", "inggo.org", "inoutmail.de", "inoutmail.eu",
    "inoutmail.info", "inoutmail.net", "insanony.art", "insanony.one",
    "insanony.store", "instance-email.com", "instant-mail.de",
    "instantemailaddress.com", "instantmail.fr", "instmail.uk",
    "intopwa.com", "intopwa.net", "intopwa.org", "introex.com",
    "investore.co", "iozak.com", "ip4.pp.ua", "ip6.li", "ip6.pp.ua",
    "ipoo.org", "irish2me.com", "iroid.com", "ironiebehindert.de",
    "irssi.tv", "is.af", "isdaq.com", "ishop2k.com", "isosq.com",
    "it2mail.com", "itunesgiftcodegenerator.com", "iwi.net",
    "ixx.io", "j-p.us", "jafps.com", "jaguar-landrover.cf",
    "jaguar-landrover.ga", "jaguar-landrover.gq", "jaguar-landrover.ml",
    "jaguar-landrover.tk", "jamesbond.flu.cc", "jamesbond.igg.biz",
    "jamesbond.nut.cc", "jamesbond.usa.cc", "janproz.com",
    "jcpclothing.ga", "jcpclothing.gq", "jcpclothing.ml", "jdmadventures.com",
    "je-recycle.info", "jet-renovation.fr", "jetable.com",
    "jetable.fr.nf", "jetable.net", "jetable.org", "jetable.pp.ua",
    "jnxjn.com", "job.craigslist.org", "jobbrett.de", "jobs-to-be-done.net",
    "joelonsoftware.com", "joinme.ru", "josefadventures.org",
    "jourrapide.com", "jpco.org", "jsrsolutions.com", "junk1e.com",
    "junkmail.ga", "junkmail.gq", "junkmail.ml", "junkmail.tk",
    "jupimail.com", "just4spam.com", "justemail.ml", "justonemore.site",
    "jv6hgh1.com", "k2pd.com", "kakadua.net", "kalapi.org",
    "kamen-market.ru", "kamsg.com", "kaovo.com", "kariplan.com",
    "kartvelo.com", "kasmail.com", "kaspop.com", "katztube.com",
    "kazelink.com", "kcrw.de", "keepmymail.com", "keinhirn.de",
    "keipino.de", "kekita.com", "kemptvillebaseball.com", "kennedy808.com",
    "kiani.com", "killmail.com", "killmail.net", "kimsdisk.com",
    "kingsq.ga", "kiois.com", "kismail.ru", "kisstwink.com",
    "kitnastar.com", "kitten-mittens.com", "klassmaster.com",
    "klassmaster.net", "klick-tipp.net", "klipsan.com", "kloap.com",
    "klud.de", "klzlk.com", "kmail.li", "kmail.moo.pl", "kmeil.top",
    "kmhow.com", "knol-power.nl", "kobrandly.com", "kobrandly.net",
    "kobrandly.org", "kook.ml", "kopagas.com", "kopaka.net",
    "kormail.xyz", "korona-nedvizhimosti.ru", "koshu.ru",
    "koszmail.pl", "kotsu.xido.com", "kpooa.com", "krsw.tk",
    "krypton.tk", "ks87.ga", "ks87.gq", "ks87.ml", "ks87.tk",
    "kuaixinwen.com", "kulturbetrieb.info", "kumail8.info",
    "kurzepost.de", "kusrc.com", "kwalidd.com", "kwift.net",
    "kwilco.net", "kyal.pl", "l-c-a.us", "l33r.eu", "labetteraverouge.at",
    "labo.ch", "lacedmail.com", "lackmail.net", "lackmail.ru",
    "lacto.info", "lags.us", "lain.ch", "lakelivingstonrealestate.com",
    "lakqs.com", "lamer.com", "landmail.co", "laoeq.com",
    "laotzu.com", "last-chance.pro", "lastmail.co", "lastmail.com",
    "latemodels.com", "lazyinbox.com", "lazyinbox.us", "ldaho.net",
    "ldop.com", "ldtp.com", "le-tim.fr", "lee.mx", "leeching.net",
    "legalrc.loan", "legends.cl", "lell.no", "lenovog4.com",
    "lerbhe.com", "lesbugs.com", "letmeinon.com", "letthemeatspam.com",
    "levy.ml", "lew2.com", "lexisense.com", "lez.se",
    "lgxscreen.com", "lifebyfood.com", "lifetimefriends.info",
    "lifetotech.com", "ligsb.com", "liknos.com", "lillemap.net",
    "lilo.me", "lindenbaumjapan.com", "link2mail.net", "linkedintuts2015.pw",
    "linux.7m.ro", "linuxmail.so", "litedrop.com", "loadby.us",
    "loan101.pro", "loaoa.com", "loapq.com", "locanto1.cl",
    "locantofight.com", "locantowin.com", "locantowsite.com",
    "locateme10.com", "locomodev.net", "login-email.cf", "login-email.ga",
    "login-email.ml", "login-email.tk", "logular.com", "loh.pp.ua",
    "loin.in", "lol.ovpn.to", "lolfreak.net", "lolito.tk",
    "lolmail.biz", "lookugly.com", "lopl.co.cc", "lordsofts.com",
    "lortemail.dk", "losemymail.com", "lovemeleaveme.com",
    "lovemeleaveme.net", "lovemeleaveme.org", "lovemeleaveme.pw",
    "lovesea.gq", "loy.kr", "lpfmgmtltd.com", "lr78.com",
    "lroid.com", "lru.me", "ls-server.ru", "luckymail.org",
    "lukecarriere.com", "lukemail.info", "lukop.dk", "luv2.us",
    "lyfestylecredits.com", "lyricspad.net", "lzoaq.com",
    "m21.cc", "m2r60ff.com", "m4.org", "m4ilweb.info",
    "maboard.com", "mac.hush.com", "macromaid.com", "macromice.info",
    "magamem.com", "magicbox.pl", "magim.be", "magspam.net",
    "maidlow.info", "mail-2-you.com", "mail-address.live",
    "mail-apps.com", "mail-apps.net", "mail-box.ga", "mail-box.gq",
    "mail-box.ml", "mail-cart.com", "mail-center.com", "mail-center.net",
    "mail-easy.fr", "mail-fake.com", "mail-finder.com",
    "mail-hierarchie.com", "mail-hierarchie.net", "mail-hierarchie.org",
    "mail-now.top", "mail-owl.com", "mail-owl.net", "mail-owl.org",
    "mail-share.com", "mail-temporaire.com", "mail-temporaire.fr",
    "mail-tester.com", "mail-today.com", "mail-toplay.com",
    "mail.by", "mail.wtf", "mail0.ga", "mail0.gq", "mail0.ml",
    "mail114.net", "mail1a.de", "mail1st.com", "mail2000.ru",
    "mail21.cc", "mail22.club", "mail2rss.org", "mail2world.com",
    "mail333.com", "mail4trash.com", "mail4you.usa.cc",
    "mail666.cn", "mail7.io", "mail707.com", "mail72.com",
    "mailback.com", "mailbiz.biz", "mailblocks.com", "mailbox.in.ua",
    "mailbox.r2.dns-oarc.net", "mailbox52.ga", "mailbox72.biz",
    "mailbox80.biz", "mailbox82.biz", "mailbox87.de", "mailbox92.biz",
    "mailbox92.com", "mailbox92.fun", "mailbucket.org",
    "mailcat.ga", "mailcat.ga", "mailcat.gq", "mailcat.ml",
    "mailcatch.com", "mailchop.com", "mailcker.com", "mailde.de",
    "mailde.info", "mailde.de", "maildrop.cc", "maildrop.cf",
    "maildrop.ga", "maildrop.gq", "maildrop.ml", "maildu.de",
    "maildx.com", "maileater.com", "mailed.ro", "maileee.com",
    "maileimer.de", "maileme101.com", "mailexpire.com",
    "mailf5.com", "mailfa.tk", "mailfall.com", "mailforspam.com",
    "mailfree.ga", "mailfree.gq", "mailfree.ml", "mailfreeonline.com",
    "mailfs.com", "mailguard.me", "mailgutter.com", "mailhazard.com",
    "mailhazard.us", "mailhz.me", "mailimate.com", "mailin8r.com",
    "mailinater.com", "mailinator.com", "mailinator.net",
    "mailinator.org", "mailinator.us", "mailinator2.com",
    "mailincubator.com", "mailismagic.com", "mailita.tk",
    "mailjunk.cf", "mailjunk.ga", "mailjunk.gq", "mailjunk.ml",
    "mailjunk.tk", "mailmate.com", "mailme.gq", "mailme.ir",
    "mailme.lv", "mailme24.com", "mailmetrash.com", "mailmo.de",
    "mailna.biz", "mailna.co", "mailna.in", "mailna.me",
    "mailnator.com", "mailnesia.com", "mailnull.com", "mailonaut.com",
    "mailorc.com", "mailorg.org", "mailox.biz", "mailox.fun",
    "mailpick.biz", "mailpm.live", "mailpoof.com", "mailpress.gq",
    "mailproxsy.com", "mailrock.biz", "mailsac.com", "mailsac.gq",
    "mailsac.tk", "mailscheap.us", "mailscrap.com", "mailseal.de",
    "mailshell.com", "mailsiphon.com", "mailslapping.com",
    "mailslite.com", "mailsucker.net", "mailt.net", "mailt.top",
    "mailta.info", "mailtemp.info", "mailtemporaire.com",
    "mailtemporaire.fr", "mailtemporaire.org", "mailto.plus",
    "mailtome.de", "mailtothis.com", "mailtraps.com", "mailtrash.net",
    "mailtrix.net", "mailtv.net", "mailtv.tv", "mailwithyou.com",
    "mailzi.ru", "mailzilla.com", "mailzilla.org", "mailzilla.org",
    "makemenaughty.club", "makemetheking.com", "malayalamdtp.com",
    "malinens.com", "mamulenok.ru", "mandraghen.cf", "manifestgenerator.com",
    "mansiondev.com", "manycore.com", "markmurfin.com", "mask03.ru",
    "maskmail.net", "masonline.info", "matamuasu.ga", "matamuasu.ml",
    "matchpol.net", "matra.top", "max-direct.com", "max88.club",
    "maximalbonus.com", "maxprice.co", "mbe.kr", "mbx.cc",
    "mcache.net", "mciek.com", "mdhc.tk", "mebelnu.info",
    "mechanicalresumes.com", "medkabinet.ru", "meepsheep.eu",
    "meinspamschutz.de", "mejjang.xyz", "meltmail.com", "meltmail.net",
    "memsg.site", "merry.pink", "messagebeamer.de", "messwiththebest.de",
    "metadon.org", "metalfan.cl", "metalfan.ga", "metalfan.gq",
    "metalfan.ml", "metalfan.tk", "metaprice.co", "mezimages.net",
    "mfsa.ru", "mfsa.store", "mhz.cf", "mhz.ga", "mhz.gq",
    "mhz.ml", "mhz.tk", "miaferrari.com", "miatadriver.com",
    "midcoastcustoms.com", "midcoastcustoms.net", "midcoastcustoms.org",
    "midlertidig.com", "midlertidig.net", "midlertidig.org",
    "mierdamail.com", "migmail.pl", "migmail2.pl", "migumail.com",
    "mihep.com", "mijnhva.nl", "milavitsaromania.ro", "mildin.org.ua",
    "mindmail.net", "mindsetup.us", "minecraftrabbits.com",
    "minex-coin.com", "minimalv.com", "minmail.net", "mintemail.com",
    "mintemail.net", "mirai.re", "mirmir.tk", "misterpinball.de",
    "mite.tk", "mitie.ga", "mitie.gq", "mitie.ml", "mitie.tk",
    "mixi.gq", "mji.ro", "mjukgansen.nu", "mkpdp.com", "ml8.ca",
    "mm5.se", "mmail.igg.biz", "mmailinater.com", "mnode.org",
    "moakt.cc", "moakt.com", "moakt.ws", "mobi.web.id",
    "mobileninja.co.uk", "mobilevpn.top", "moburl.com",
    "mockmyid.com", "moeri.org", "mofu.be", "mohmal.com",
    "mohmal.in", "mohmal.tech", "molms.com", "momentics.ru",
    "monachat.tk", "monadi.ml", "moncourrier.fr.nf", "monemail.fr.nf",
    "monmail.fr.nf", "monumentmail.com", "mooblan.com",
    "moonmoon.de", "moose-mail.com", "mopa.nl", "mor19.uu.gl",
    "morahdsl.cf", "moreawesomethanyou.com", "morecoolstuff.net",
    "moreorcs.com", "morsin.com", "mortmestres.com", "moruzza.com",
    "motique.de", "mountainregionallibrary.net", "mouser.cf",
    "mouser.ga", "mouser.gq", "mouser.ml", "mouser.tk",
    "mox.pp.ua", "moza.pl", "mozej.com", "mp-j.ga", "mp-j.ga",
    "mp3gears.net", "mr24.co", "msg.mailgang.com", "msgden.com",
    "msgden.net", "msgden.org", "mspeciosa.com", "msrc.ml",
    "msxd.com", "mt2009.com", "mt2014.com", "mt2015.com",
    "mt2016.com", "mt2017.com", "mtmdev.com", "muathegame.com",
    "muchomail.com", "mucincanon.com", "muehlacker.tk",
    "muell.icu", "muell.email", "muell.xyz", "muellemail.com",
    "muellmail.com", "mufux.com", "muggltzel.de", "muimail.com",
    "munoub.com", "musiccode.me", "musician.org", "muskelshirt.de",
    "mutant.me", "muttwalker.net", "mvdmail.com", "mvrht.com",
    "mvrht.net", "mwarner.org", "mx0.wwwnew.eu", "mx18.mailr.eu",
    "mx19.mailr.eu", "mxfuel.com", "mxp.dns-cloud.net",
    "mxp.dnsabr.com", "my10minutemail.com", "mybitti.de",
    "mycleaninbox.net", "myemailboxy.com", "myemailboxy.com",
    "myfullmail.com", "myindohome.services", "myinterserver.ml",
    "mykickassclips.com", "mymail-inbox.com", "mymail90.com",
    "mymailoasis.com", "mymailto.cf", "mymailto.ga",
    "mymailto.ml", "mynetstore.de", "mynetwork.cf", "myopang.com",
    "mypartyclip.de", "myphantomemail.com", "mysamp.de",
    "myspaceinc.com", "myspaceinc.net", "myspacepimpedup.com",
    "myspamless.com", "mystvpn.com", "mysugartime.ru",
    "mytemp.email", "mytempemail.com", "mytempmail.com",
    "mytrashmail.com", "mytrashmail.net", "mytrashmail.org",
    "mywarnernet.net", "mywrld.site", "mywrld.top", "myzx.com",
    "n1nja.org", "nabuma.com", "nada.email", "nada.ltd",
    "nada.pro", "nakedtruth.biz", "nanonym.ch", "napalm51.nut.cc",
    "napalm51.usa.cc", "national.shitposting.agency",
    "nationalgardeningclub.com", "naturalious.com", "nawmin.info",
    "nbox.notif.me", "nctuiem.ga", "nctuiem.gq", "nctuiem.ml",
    "negated.com", "neko2.net", "nekochan.fr", "nekochan.net",
    "neomailbox.com", "nepwk.com", "nervmich.net", "nervt.niet.me",
    "net-list.com", "net.ua", "net1mail.com", "net2mail.com",
    "net3mail.com", "net4you.usa.cc", "netmail3.net",
    "netmails.com", "netmails.net", "netricity.nl", "netris.net",
    "netviewer-france.com", "netzidiot.de", "neverbox.com",
    "nevermail.de", "newbpotato.tk", "newfilm24.ru", "newideasfornewpeople.info",
    "newmail.top", "next.ovh", "nextstopvalhalla.com",
    "nezdiro.org", "nezzart.com", "nfast.net", "nguyenusedcars.com",
    "nh3.ro", "nice-4u.com", "nicknassar.com", "nickrizos.com",
    "nie-podam.pl", "niepodam.pl", "nigge.rs", "nike.coms.hk",
    "nincsmail.com", "nincsmail.hu", "ninfan.com", "nirvanacoin.com",
    "niwl.net", "nko.kr", "nl.szucsatan.net", "nm7.cc",
    "nmail.cf", "nmail.ga", "nmail.gq", "nmail.ml", "nmail.tk",
    "nnh.com", "nnot.net", "no-spam.ws", "no-spammers.com",
    "no-ux.com", "nobulk.com", "noclickemail.com", "nodezine.com",
    "nodnor.cl", "nogmailspam.info", "noicd.com", "noifeelings.com",
    "nokiamail.com", "nolemail.ga", "nomail.cf", "nomail.ga",
    "nomail.gq", "nomail.ml", "nomail.nodns.xyz", "nomail.pw",
    "nomail.xl.cx", "nomail2me.com", "nomail2me.net", "nomail2me.org",
    "nomailthankyou.com", "nomorespamemails.com", "nomail.xl.cx",
    "noref.in", "norihiko.com", "norseforce.com", "northemquest.com",
    "nospam.ze.tc", "nospam4.us", "nospamfor.us", "nospammail.net",
    "nospamthanks.info", "nothingtoseehere.ca", "notif.me",
    "notmail.com", "notmail.net", "notmail.org", "notsharingmy.info",
    "nowhere.org", "nowmymail.com", "nowmymail.net", "npv.kr",
    "nq6.ml", "nthrl.com", "nthrw.com", "ntlhelp.net",
    "nub3z.org", "nullbox.info", "nurfuerspam.de", "nut.cc",
    "nutpa.net", "nuts2trade.com", "nwldx.com", "nwldx.net",
    "nwytg.com", "nwytg.net", "ny7.me", "nypato.com",
    "nyrmusic.com", "o2stk.org", "o3enzyme.com", "o7i.net",
    "oalsp.com", "obfusko.com", "objectmail.com", "obobbo.com",
    "oborudovanieizturcii.ru", "obxpestcontrol.com", "odaymail.com",
    "odnorazovoe.ru", "oepia.com", "oerpub.org", "offshore-pro.ga",
    "ohaaa.de", "ohi.tw", "ohiotestprep.com", "oing.cf", "okclips.net",
    "okrent.us", "okzk.com", "olyply.ru", "omail.pro", "omdo.in",
    "omnievents.org", "one-time.email", "one2mail.info",
    "onebiginbox.com", "onecitymail.com", "onelegalplan.com",
    "onemail1.com", "oneoffemail.com", "onewaymail.com",
    "onlatedotcom.info", "online.ms", "onlineidea.info",
    "onqin.com", "ontyne.biz", "oolus.com", "oopi.org",
    "opayq.com", "opentrash.com", "opmmedia.ga", "opp24.com",
    "optimaweb.me", "opwebw.com", "oranek.com", "ordinaryamerican.net",
    "oreidresume.com", "orgmbx.de", "oroki.de", "oshietechan.link",
    "otherinbox.com", "ourklips.com", "ourpreviewdomain.com",
    "outlawspam.com", "outmail.win", "ovpn.to", "owlpic.com",
    "owlymail.com", "ownsyou.de", "oxopoha.com", "ozyl.de",
    "p33.org", "p71ce1.com", "pa9e.com", "pachilly.com",
    "pagol.tk", "pakadebu.ga", "pancakemail.com", "papierkorb.me",
    "paplease.com", "para2019.ru", "parcel4.net", "parkcrestlakewood.usa.cc",
    "parleasalwebp.zyns.com", "partybombe.de", "partynight.at",
    "passwordmail.com", "pastebitch.com", "patonce.com",
    "paulkippes.com", "pavilionx2.com", "payperex.com", "pbanh.com",
    "pc1520.com", "pcmylife.com", "pcusers.otherinbox.com",
    "pe.hu", "pebkit.ga", "pebkit.gq", "pebkit.ml", "pebkit.tk",
    "pecinan.com", "pecinan.net", "pecinan.org", "pedimed-szczecin.pl",
    "pencalc.xyz", "penis.computer", "penisgoes.in",
    "pepbot.com", "peppe.usa.cc", "pepsi.coms.hk", "personal-email.ml",
    "peterdethier.com", "petertij.com", "petl.ltd", "petrzilka.net",
    "pfui.ru", "phone-elkey.ru", "photo-impact.eu", "photomark.net",
    "pi.vu", "pickuplanet.com", "pietershop.com", "pigeonmail.de",
    "pii.at", "pii.email", "pii.at", "piki.si", "pimpedupmyspace.com",
    "pinehill-seattle.org", "pingir.com", "pinoymail.com",
    "pipeline.ru", "pippop.cf", "pippop.ga", "pippop.gq",
    "pippop.ml", "pippop.tk", "piratesofthecaribbeanfan.com",
    "pjjkp.com", "placemail.online", "ple.ce", "plexolan.de",
    "plhk.ru", "ploae.com", "plw.me", "pm.me", "po-jie.com", "podam.pl",
    "poehali-otdihat.ru", "pojok.ml", "pokemail.net", "pokiemobile.com",
    "polarking.com", "polimi.ml", "politikerclub.de", "polyfaust.com",
    "poly-swarm.com", "pooae.com", "poofy.org", "pookmail.com",
    "poopiebutt.club", "pop3.xyz", "popconn.party", "popesodomy.com",
    "popgmail.com", "popmail.io", "popmailserv.org", "porco.cf",
    "porco.ga", "porco.gq", "porco.ml", "post-shift.ru",
    "post-shift.ru", "postacin.com", "postfach2go.de",
    "postheo.de", "postonline.me", "poutineyourface.com",
    "powered.name", "powlearn.com", "ppetw.com", "pqoia.com",
    "praetorpl.dev", "prazdnik-37.ru", "predatorrat.cf",
    "predatorrat.ga", "predatorrat.gq", "predatorrat.ml",
    "predatorrat.tk", "premium-mail.fr", "premiumperson.website",
    "primabananen.net", "privacy.net", "privatdemail.net",
    "privy-mail.com", "privy-mail.de", "privy-mail.net",
    "privymail.de", "privymail.net", "privymail.org",
    "pro-tag.org", "procrackers.com", "profast.top", "projectclan.com",
    "projectxd.com", "proprietativalcea.ro", "propscore.com",
    "protempmail.com", "protestore.co", "proto2mail.com", "proton.me", "protonmail.ch", "protonmail.com",
    "provamail.com", "providier.com", "provmail.net", "prydirect.info",
    "psh.me", "psles.com", "psoxs.com", "psychedelicwarrior.xyz",
    "pterodactyl.work", "ptp1.xyz", "pubgeres.nl", "pubmail.xyz",
    "pubnic.net", "puglieisi.com", "puji.pro", "pukimail.com",
    "pulpmail.us", "pumps-fashion.com", "punkass.com",
    "purple.flu.cc", "purple.igg.biz", "purple.nut.cc",
    "purple.usa.cc", "put2.net", "putthisinyourspamdatabase.com",
    "pwrby.com", "q314.net", "q5vm7pi9.com", "q7t43q92.com",
    "qacquirep.com", "qafatstore.com", "qasti.com", "qbfree.us",
    "qc.to", "qibl.at", "qipmail.net", "qiq.us", "qisdo.com",
    "qisoa.com", "qjfqhhsd.tk", "qoika.com", "qq.my",
    "qsl.ro", "qt1.ddns.net", "quadrafit.com", "quickinbox.com",
    "quickmail.in", "quickmail.nl", "quickmail.rocks",
    "quickmail.run", "quickreport.info", "qvap.ru", "qvy.me",
    "qwickmail.com", "r0.igg.biz", "r2c-dev.com", "r4nd0m.de",
    "r8r4p0cb.com", "ra3.us", "rabin.ca", "rabiot.reisen",
    "racedriver.com", "radecoratingltd.com", "radiku.ga",
    "radiku.ga", "radiku.ml", "radiku.tk", "raetp9.com",
    "rainmail.biz", "rainwaterstudios.org", "rajeshcon.cf",
    "raketenmann.de", "rancidhome.net", "randomail.net",
    "randomail.io", "rao.kr", "raqid.com", "rarame.club",
    "rawhidefc.org", "rax.la", "raxtest.com", "razumkov.in.ua",
    "rbb.org", "rcpt.at", "rcs7.xyz", "re-gister.com",
    "reality-concept.club", "reallymymail.com", "realtyalerts.ca",
    "rebeca.re", "receiveee.com", "recipeforfailure.com",
    "recode.me", "reconmail.com", "recursor.net", "recyclemail.dk",
    "redchan.it", "reddithub.com", "redfeathercrow.com",
    "redpeanut.com", "reftoken.net", "regbypass.com",
    "regbypass.comsafe-mail.net", "regspaces.tk", "rejectmail.com",
    "remail.cf", "remail.ga", "remail.gq", "remail.ml",
    "remail.tk", "remarkable.rocks", "remote.li", "renraku.in",
    "reptilegenetics.com", "resgedvgfed.tk", "resmail.com",
    "revolvingdoorhoax.org", "rfc822.org", "rhyta.com",
    "rhyta.net", "rich-money.com", "riddermark.de", "rifkian.ga",
    "risingsuntouch.com", "riski.cf", "rklips.com", "rma.ec",
    "rmqkr.net", "rnailinator.com", "ro.lt", "robertspizzabar.com",
    "robot2.cl", "robotmail.me", "robox.agency", "rodtookjing.com",
    "rollin.io", "ronnierage.net", "rootfest.net", "rosebearmobile.com",
    "rotaniliam.com", "rowe-solutions.com", "royal.net",
    "rppkn.com", "rs311e8.com", "rtrtr.com", "rtskiya.ga",
    "rtskiya.ml", "rtskiya.tk", "ru.godaddy.com", "ruafdulactee.com",
    "ruffrey.com", "rumgel.com", "runi.ca", "ruru.be",
    "rustydoor.com", "ruu.kr", "rvb.ro", "rx.dred.ru", "rx.qc.to",
    "s0ny.net", "s33db0x.com", "sabrestlouis.com", "sackboii.com",
    "safaat.com", "safe-mail.net", "safermail.info", "safersignup.de",
    "safetymail.info", "safetypost.de", "saharanight.org",
    "sale.craigslist.org", "salmeow.tk", "salonyfryzjerskie.info",
    "samsclass.info", "sandelf.de", "sandelf.de", "sanfinder.com",
    "sanim.net", "sanstr.com", "sast.ro", "satisfyme.club",
    "satukosong.com", "sausen.com", "saynotospams.com",
    "scatmail.com", "scay.net", "schachrol.com", "schafmail.de",
    "schmeissweg.tk", "schmid.cf", "schmid.ga", "schmid.gq",
    "schmid.ml", "schmid.tk", "schrott-email.de", "scrsot.com",
    "sd3.in", "secmail.pw", "secretemail.de", "secure-mail.biz",
    "secure-mail.cc", "secure-mail.cn", "secured-link.net",
    "securehost.com.es", "seekapps.com", "seekjobs4u.com",
    "sejaa.lv", "selfip.biz", "selfip.com", "selfip.info",
    "selfip.net", "selfip.org", "sellcow.net", "semut-kecil.com",
    "semutkecil.com", "send22u.info", "sendfree.org",
    "sendingspecialgifts.com", "sendspamhere.com", "senseless-entertainment.com",
    "server.ms", "server.gallery", "serverhunter.net", "service4.ml",
    "services391.com", "sexforswingers.com", "sexical.com",
    "sezet.com", "shalar.net", "sharedmailbox.org", "sharklasers.com",
    "sharklasers.com", "shayzam.net", "shieldedmail.com",
    "shieldemail.com", "shiftmail.com", "shinnemo.com",
    "ship-from-to.com", "shipfromto.com", "shiphazmat.org",
    "shipping-regulations.com", "shippingterms.org", "shitmail.de",
    "shitmail.me", "shitmail.org", "shitmail.tk", "shitposting.agency",
    "shmeriously.com", "shortmail.net", "shotmail.ru", "shut.name",
    "shut.ws", "shutup.biz", "shutup.net", "shutup.org",
    "sibmail.com", "sigaint.org", "signal24.ru", "sign-up.website",
    "sikux.com", "silentbox.eu", "silvercoin.life", "sim-sim.ru",
    "simaenaga.com", "simpleitsecurity.info", "sin.cl",
    "sina.com", "sinnlos-mail.de", "siteposter.net", "sizzlemctwizzle.com",
    "sjuaq.com", "skeefmail.com", "skkk.edu.my", "skrx.tk",
    "sky-inbox.com", "sky-ts.de", "slaskpost.se", "slave-auctions.net",
    "slippery.email", "slopsbox.com", "slothmail.net",
    "slushmail.com", "sluteen.com", "sly.io", "smackemail.com",
    "smallker.tk", "smapfree24.com", "smapfree24.de",
    "smapfree24.eu", "smapfree24.info", "smapfree24.org",
    "smarttalent.pw", "smellfear.com", "smellrear.com",
    "smellypotato.tk", "smoothmail.com", "smsforum.ro",
    "snakemail.com", "snapwet.com", "sneakemail.com", "sneakmail.de",
    "snkmail.com", "social-mailer.tk", "socialfurry.org",
    "sofimail.com", "sofort-mail.de", "sofortmail.de",
    "softkey-office.ru", "softpls.asia", "sohu.com", "sohu.net",
    "soisz.com", "solvemail.com", "solvemail.info", "soodon.com",
    "soodon.com", "soozoop.com", "spam-be-gone.com", "spam.2012-2016.ru",
    "spam.care", "spam.de", "spam.fassag.de", "spam.flu.cc",
    "spam.igg.biz", "spam.nut.cc", "spam.usa.cc", "spam4.me",
    "spamail.de", "spamarrest.com", "spamavert.com", "spambob.com",
    "spambob.net", "spambob.org", "spambog.com", "spambog.de",
    "spambog.net", "spambog.ru", "spambox.info", "spambox.irishspringrealty.com",
    "spambox.me", "spamcannon.com", "spamcannon.net", "spamcero.com",
    "spamcon.org", "spamcorptastic.com", "spamcowboy.com",
    "spamcowboy.net", "spamcowboy.org", "spamday.com", "spamex.com",
    "spamfree.eu", "spamfree24.com", "spamfree24.de", "spamfree24.eu",
    "spamfree24.info", "spamfree24.net", "spamfree24.org",
    "spamfree24.xyz", "spamgoes.in", "spamgourmet.com",
    "spamgourmet.net", "spamgourmet.org", "spamherelots.com",
    "spamhereplease.com", "spamhole.com", "spamify.com",
    "spaminator.de", "spamkill.info", "spaml.com", "spaml.de",
    "spamlot.net", "spammotel.com", "spamobox.com", "spamoff.de",
    "spamoff.me", "spamsandwich.com", "spamserver.cf",
    "spamserver.ga", "spamserver.gq", "spamserver.ml",
    "spamserver.tk", "spamslicer.com", "spamsphere.com",
    "spamspot.com", "spamstack.net", "spamthisplease.com",
    "spamtroll.net", "spamwc.cf", "spamwc.ga", "spamwc.gq",
    "spamwc.ml", "spamwc.tk", "speed.1s.fr", "speedgaus.net",
    "sperma.cf", "spikio.com", "spindl-e.com", "spoofmail.de",
    "squizzy.de", "squizzy.eu", "squizzy.net", "sr.ro.lt",
    "sraka.xyz", "sroff.com", "sry.li", "ss-hitler.tk",
    "ss.undo.it", "ssoia.com", "stanford-edu.tk", "stanfordukkon.tk",
    "starlight-breaker.net", "startfu.com", "startkeys.com",
    "statdvr.com", "stathost.net", "statiix.com", "staytv.biz",
    "staytv.info", "staytv.org", "steam-area.com", "steambot.net",
    "stexsy.com", "stinkefinger.net", "stop-my-spam.cf",
    "stop-my-spam.com", "stop-my-spam.ga", "stop-my-spam.gq",
    "stop-my-spam.ml", "stop-my-spam.tk", "stopspam.io",
    "storiqax.com", "storiqax.top", "storj99.com", "storj99.top",
    "streetwisemail.com", "stromox.com", "stuckmail.com",
    "stuffmail.de", "stumpfwerk.com", "stylist-volos.ru",
    "suburbanthug.com", "successforums.com", "suckmyd.com",
    "sudolife.me", "sudolife.net", "sudolife.org", "sudomail.biz",
    "sudomail.com", "sudomail.net", "sudomail.org", "sudoverse.com",
    "sudoverse.net", "sudoverse.org", "sudoweb.net",
    "sudoworld.com", "sudoworld.net", "sudoworld.org",
    "sueddeutsche.de", "suioe.com", "super-auswahl.de",
    "supergreatmail.com", "supermailer.jp", "superrito.com",
    "superstachel.de", "suremail.info", "suremail.info",
    "surveyrnonkey.net", "susi.ml", "sute.jp", "svk.jp",
    "svxr.org", "sweetxxx.de", "swift10minutemail.com",
    "sylvannet.com", "symphonyresume.com", "syncer.net",
    "syosetu.gq", "syujob.accountant", "szerz.com", "t.woeishyang.com",
    "t24e4v7.com", "t3t97d1d.com", "tafmail.com", "tafoi.gr",
    "tagyourself.com", "talkinator.com", "tanukis.org",
    "tapchicuoihoi.com", "taphear.com", "tapi.re", "tarzan.usa.cc",
    "tarzanmail.ml", "tastrg.com", "tb-on-line.net", "tcloud.io",
    "tdf-illustration.com", "techemail.com", "techgroup.me",
    "technikue.ml", "techno5.cl", "teerest.com", "tefl.ro",
    "teleosaurs.xyz", "teleworm.com", "teleworm.us",
    "temp-mail.info", "temp-mail.org", "temp-mail.ru", "temp-mail.top",
    "temp-mail.xyz", "temp-mails.com", "temp-mailbox.com",
    "temp-mailbox.top", "tempail.com", "tempalias.com",
    "tempalias.net", "tempalias.org", "tempe-mail.com",
    "tempemail.biz", "tempemail.co", "tempemail.com",
    "tempemail.net", "tempemail.org", "tempinbox.co.uk",
    "tempinbox.com", "tempmail.co", "tempmail.de", "tempmail.eu",
    "tempmail.it", "tempmail.net", "tempmail.org", "tempmail.pro",
    "tempmail.space", "tempmail.xyz", "tempmail2.com",
    "tempmaildemo.com", "tempmailer.com", "tempmailer.de",
    "tempmailer.net", "tempmailer.org", "tempmailo.com",
    "tempmails.cf", "tempmails.ga", "tempmails.gq", "tempmails.ml",
    "tempmails.tk", "tempomail.fr", "tempomail.org",
    "temporarily.de", "temporarioemail.com.br", "temporary-mail.net",
    "temporary-mail.org", "temporaryemail.net", "temporaryemail.us",
    "temporaryforwarding.com", "temporaryinbox.com",
    "temporarymail.ga", "temporarymail.net", "temporarymail.org",
    "temporarymailaddress.com", "tempthe.net", "tempymail.com",
    "ternaklele.ga", "test.com", "test.de", "testudine.com",
    "thanksnospam.info", "thankyou2010.com", "thc.st",
    "theaviors.com", "thebear.tk", "thebestreminder.com",
    "thecloudindex.com", "thedirhq.info", "thelightningmail.net",
    "thelimestrees.com", "thembones.com.au", "themostemail.com",
    "theopposition.club", "thescrappermovie.com", "theteastory.info",
    "thietbivanphong.asia", "thisisnotmyrealemail.com",
    "thismail.net", "thisurl.website", "thnikka.com",
    "throam.com", "throwam.com", "throwaway.email", "throwaway.email",
    "throwaway.ml", "throwaway.pp.ua", "throwawaymail.com",
    "throwawaymail.org", "throya.com", "thunk.org", "thxmate.com",
    "tiapz.com", "tic.ec", "tidni.com", "timgiarevn.com",
    "timkassouf.com", "tinoza.org", "tinyurl24.com", "tlpn.org",
    "tmail.com", "tmail.ws", "tmailinator.com", "tmails.net",
    "tmails.top", "tmp.emeraldwebmail.com", "tmpail.net",
    "tmpbox.net", "tmpeml.com", "tmpeml.info", "tmpeml.org",
    "tmpjr.me", "tmpmail.net", "tmpmail.org", "tmpmail.ru",
    "tmpmailbox.com", "tmpmailer.com", "tmpmailer.org",
    "tmpmail.net", "toddsbighug.com", "toiea.com", "toi.kr",
    "toiea.com", "tokenmail.de", "tonne.to", "toomail.biz",
    "toon.ml", "top1post.com", "topinrock.cf", "topofertasdehoy.com",
    "topranklist.de", "toprumours.com", "torm.xyz", "toss.pw",
    "tosunkaya.com", "totalvista.com", "totesmail.com",
    "tp-qa-mail.com", "tqoai.com", "tradermail.info", "trash-amil.com",
    "trash-amill.com", "trash-amill.net", "trash-mail.at",
    "trash-mail.cf", "trash-mail.ga", "trash-mail.gq", "trash-mail.ml",
    "trash-mail.tk", "trash-mail.com", "trash-mail.de", "trash-mail.ga",
    "trash-mail.gq", "trash-mail.ml", "trash-mail.tk", "trash2009.com",
    "trash2010.com", "trash2011.com", "trash247.com", "trash247.eu",
    "trashbox.eu", "trashcanmail.com", "trashdevil.com",
    "trashdevil.de", "trashemail.de", "trashmail.at", "trashmail.com",
    "trashmail.de", "trashmail.ga", "trashmail.gq", "trashmail.io",
    "trashmail.me", "trashmail.net", "trashmail.org", "trashmail.ws",
    "trashmailer.com", "trashmailer.de", "trashmailer.net",
    "trashmailer.org", "trashmails.com", "trashme.me", "trashymail.com",
    "trashymail.net", "trashymail.org", "trasz.com", "travala10.com",
    "trickmail.net", "trillianpro.com", "trimix.cn", "tritium.engineering",
    "tryalert.com", "tryninja.io", "tryzoe.com", "ts-by-tashkent.cf",
    "ts-by-tashkent.ga", "ts-by-tashkent.gq", "ts-by-tashkent.ml",
    "ts-by-tashkent.tk", "ts93crz8f5ss.cf", "ts93crz8f5ss.ga",
    "ts93crz8f5ss.gq", "ts93crz8f5ss.ml", "ts93crz8f5ss.tk",
    "ttirv.org", "ttz.im", "tuofs.com", "turbo.coms.hk",
    "turbo.dk", "turoid.com", "turual.com", "tvchd.com",
    "tverya.com", "twkly.ml", "twocowmail.net", "twoweirdtricks.com",
    "txrs.tk", "tyhe.ro", "tyldd.com", "tympe.net",
    "u14269.gq", "u14269.ml", "u2t.xyz", "u6lvty2.com",
    "ua3jx7n0w3.com", "uber-mail.com", "ubismail.net", "ucandobest.com",
    "ucche.us", "ucup.in", "ucylu.com", "uemail99.com",
    "ufacturing.com", "uggsrock.com", "uguuchantele.com", "uhhu.ru",
    "uiu.us", "ujijima.jp", "uk.flu.cc", "uk.igg.biz", "uk.nut.cc",
    "uk.usa.cc", "umail.net", "umail2.com", "umail365.com",
    "umy.kr", "undo.it", "unicredit.tk", "unids.com",
    "unimark.org", "unit7lahaina.com", "unmail.ru", "unpastore.co",
    "upliftnow.com", "uplipht.com", "uploadnolimit.com",
    "urfunktion.se", "urhen.com", "uroid.com", "us.af", "us.flu.cc",
    "us.igg.biz", "us.nut.cc", "us.usa.cc", "used-product.fr",
    "userbeam.com", "username.e4ward.com", "username.e4ward.org",
    "username.igg.biz", "username.nut.cc", "username.usa.cc",
    "userscloud.com", "ushijima.com", "utiket.us", "uu.gl",
    "uuroalaldoot.com", "uvy.kr", "uwork4.us", "uyhip.com",
    "v8.dev", "vaasfc4.tk", "vaati.org", "valemail.net",
    "valhalladev.com", "vanacken.com", "vankin.de", "vba.de",
    "vcbox.pro", "vddaz.com", "vdig.com", "vedula.com",
    "veo.kr", "verdejo.com", "veryday.ch", "veryday.eu",
    "veryday.info", "veryrealemail.com", "vesa.pw", "vfemail.net",
    "vickaherb.ga", "vickaherb.gq", "vickaherb.ml", "vickaherb.tk",
    "viditag.com", "viewcastmedia.com", "viewcastmedia.net",
    "viewcastmedia.org", "vikingsonly.com", "vinernet.com",
    "vip.163.com", "vip.188.com", "vip.qq.com", "vip.sohu.com",
    "vip.sohu.net", "vip.tom.com", "vipepe.com", "vipmail.name",
    "vipmail.pw", "viralplays.com", "virtualmail.gq", "virtualmail.ml",
    "virtualmail.tk", "visa.coms.hk", "visa.dnsabr.com",
    "visa.dns-cloud.net", "vixletdev.com", "vkcode.ru",
    "vmani.com", "vmpanda.com", "vnedu.com", "vogds.com",
    "voltaer.com", "vomoto.com", "vorga.org", "votiputox.org",
    "voxelcore.com", "vpn.st", "vpn33.top", "vps30.com",
    "vps911.com", "vradportal.com", "vremonte24.ru", "vrmtr.com",
    "vsimcard.com", "vss6.com", "vtxmail.us", "vubby.com",
    "vuiy.pw", "vuzimail.com", "vztc.com", "w3internet.co.uk",
    "w4i3em6r.com", "w918bsq.com", "w9yxf0hm.com", "wakingupesther.com",
    "walala.org", "walkmail.net", "walkmail.ru", "wallm.com",
    "wants.dicksinmybutt.com", "warau-kadani.com", "warnednl2.com",
    "watch-harry-potter.com", "watchever.biz", "watchfull.net",
    "watchiron.com", "wazabi.cl", "wbdev.tech", "wbml.net",
    "web-contact.info", "web-emailbox.eu", "web-ideal.fr",
    "web-mail.pp.ua", "web2mailco.com", "webcontact-france.fr",
    "webemail.me", "webm4il.info", "webmail.top", "webmail.uu.gl",
    "webtrip.ch", "webuser.in", "wee.my", "wefjo.gq",
    "weg-werf-email.de", "weg-werf-email.de", "wegwerf-email-addressen.de",
    "wegwerf-email-adressen.de", "wegwerf-email.de", "wegwerf-email.net",
    "wegwerf-emails.de", "wegwerf-emails.net", "wegwerfadresse.de",
    "wegwerfemail.adresse.de", "wegwerfemail.com", "wegwerfemail.de",
    "wegwerfemail.info", "wegwerfemail.net", "wegwerfemail.org",
    "wegwerfemailadresse.com", "wegwerfmail.adresse.de",
    "wegwerfmail.com", "wegwerfmail.de", "wegwerfmail.info",
    "wegwerfmail.net", "wegwerfmail.org", "wegwerpmailadres.nl",
    "weirdstuff.com", "welikecookies.com", "wemel.top", "wetrainbayarea.com",
    "wetrainbayarea.org", "wfgdfhj.tk", "whatiaas.com",
    "whatifanalytics.com", "whatpaas.com", "whatsaas.com",
    "wh copy.com", "wh4f.org", "whaas.com", "whartontickets.com",
    "whatsmyname.com", "whtjddn.33mail.com", "whopy.com",
    "whtjddn.33mail.com", "wibblesmith.com", "wicked-game.com",
    "wickedgame.cf", "wickedgame.ga", "wickedgame.gq",
    "wickedgame.ml", "wickedgame.tk", "wickmail.net", "wiemei.com",
    "wifimaven.com", "wikidocuslaura.com", "wilemail.com",
    "willhackforfood.biz", "willselfdestruct.com", "wimsg.com",
    "winemaven.info", "wins.com.br", "wishan.net", "wiz2.site",
    "wlist.ro", "wmail.cf", "wmail.club", "wmail.tk", "wolfsmail.tk",
    "wolfsmail.tk", "wollan.info", "worldspace.link", "wovz.cf",
    "wovz.ga", "wovz.gq", "wovz.ml", "wovz.tk", "wpg.im",
    "wr9v6at.com", "writeme.com", "wronghead.com", "ws.gy",
    "wudet.men", "wuespdj.xyz", "wupics.com", "wuzup.net",
    "wuzupmail.net", "wwjmp.com", "wwwnew.eu", "wxnw.net",
    "wyvernia.net", "wzukbdwd.com", "x24.com", "x4y.cl",
    "x5a9m8ugq.com", "xag.co", "xag.co.cc", "xag.ga", "xag.gq",
    "xag.ml", "xag.tk", "xag.xn--9kq967o.com", "xbaby69.top",
    "xcode.ro", "xcodes.net", "xcompress.com", "xcpy.com",
    "xemaps.com", "xents.com", "xgaming.ca", "xing886.uu.gl",
    "xinzk1ul.com", "xjoi.com", "xl.cx", "xmail.com", "xmail.net",
    "xmail.org", "xmails.net", "xmaily.com", "xn--9kq967o.com",
    "xn--bck1b9a5dre4c.com", "xn--wkr7l.com", "xoxy.net",
    "xpectmore.com", "xprice.co", "xrho.com", "xsilence.fr",
    "xtrars.ml", "xwaretech.com", "xwaretech.info", "xwaretech.net",
    "xww.ro", "xxhamsterxx.ga", "xxi2.com", "xxlocanto.us",
    "xxolocanto.us", "xxqx3802.com", "xy9ce.tk", "xyzfree.net",
    "xyzmail.men", "xyzmail.xyz", "xzapmail.com", "yabai.com",
    "yadavnaresh.com.np", "yahoo.tech", "yahooproduct.com",
    "yamail.win", "yandex.cf", "yandex.ga", "yandex.gq",
    "yandex.ml", "yandex.tk", "yandex.ua", "yapped.net",
    "yapped.net", "ycare.de", "yclub.biz", "ye.vc", "yedi.org",
    "yeehaa.com", "yep.it", "yepmail.net", "yert.ga", "yert.tk",
    "yesaccounts.net", "yevme.com", "yogamaven.com", "yogotex.com",
    "yop.email", "yop.ze.gy", "yopmail.com", "yopmail.fr",
    "yopmail.gq", "yopmail.info", "yopmail.net", "yopmail.org",
    "yopmail.pp.ua", "yordanmail.cf", "yordanmail.ga",
    "you-spam.com", "yougotgoated.com", "youmail.ga", "youmailr.com",
    "yourdomain.com", "youremail.cf", "youremail.ga", "youremail.gq",
    "youremail.ml", "youremail.tk", "yourmail.de", "yourspamgoesto.space",
    "yourtube.ml", "yroid.com", "yspend.com", "ytpayy.com",
    "yugasandwich.com", "yui.it", "yuoia.com", "yupmail.fr",
    "yupmail.gq", "yupmail.ml", "yurok.ru", "z1p.biz",
    "z5cpw9pg8oiiuwyl.ga", "z7az14m.com", "z86.ru", "z86.store",
    "zain.site", "zainmax.net", "zaktouni.fr", "zane.rocks",
    "zapzapmail.com", "zasve.com", "zavio.nl", "zbpe.com",
    "zchatz.ga", "zdenka.net", "ze.gy", "ze.tc", "zebins.com",
    "zebins.eu", "zehnminuten.de", "zehnminutenmail.de",
    "zehnminutenmail.eu", "zehnminutenmail.net", "zehnminutenmail.org",
    "zel.ml", "zelow.no", "zepp.dk", "zerodog.ga", "zerodog.gq",
    "zerodog.ml", "zerodog.tk", "zeroknow.ga", "zeroknow.gq",
    "zeroknow.ml", "zeroknow.tk", "zetmail.com", "zexeet9i5l49ocke.cf",
    "zexeet9i5l49ocke.ga", "zexeet9i5l49ocke.gq", "zexeet9i5l49ocke.ml",
    "zexeet9i5l49ocke.tk", "zf4r3ie.tk", "zhaoyuan.edu.cn",
    "zhcne.com", "zheweiyi.com", "zhorachu.com", "ziggo.nl",
    "zipcad.com", "zippymail.info", "zipzap.de", "zipzap.in",
    "zipzaps.de", "zipo1.gq", "zipo1.ml", "zipo2.gq", "zipo2.ml",
    "zippiex.com", "zippymail.info", "zipzap.de", "zipzap.in",
    "zipzaps.de", "zixoa.com", "zkcckw.tk", "zmail.net",
    "zmail.org", "zmail.ru", "zoaxe.com", "zoemail.com",
    "zoemail.net", "zoemail.org", "zoetropes.org", "zomg.info",
    "zomg.info", "zoutlook.com", "zp.ua", "zsero.com",
    "zumpul.com", "zv68.com", "zxcv.com", "zxcvbnm.com",
    "zxcvbnm.tk", "zydecofan.com", "zylpu.ru", "zymuying.com",
    "zzi.us", "zzrgg.com", "zzz.com",
})


def is_disposable_email(email: str) -> bool:
    """Return True if the email domain is a known disposable/temporary email provider."""
    if not email or "@" not in email:
        return False
    domain = email.strip().lower().split("@")[-1]
    if not domain:
        return False
    return domain in DISPOSABLE_DOMAINS
