"""Speakeasy daily collect — single source of truth for loot_box + armoury inventory."""

SPEAKEASY_DAILY_CASH = 50_000_000
SPEAKEASY_DAILY_BULLETS = 1_000
SPEAKEASY_DAILY_LOOT_PIECES = 10
SPEAKEASY_DAILY_POINTS = 25
SPEAKEASY_COOLDOWN_HOURS = 24
